In [4]:
def apply_sparse_cca(X, Z, X_cols=None, Z_cols=None, 
                     standardize=True, 
                     find_best_n=True,
                     find_best_penalty=True,
                     penalty_range=None,
                     n_components=None,
                     penaltyu=None,
                     penaltyv=None,
                     n_splits=5,
                     random_state=42,
                     do_permutation_test=True,
                     n_permutations=1000,
                     visualize=True,
                     verbose=True):
    
    # 데이터 준비
    if isinstance(X, pd.DataFrame):
        X = X.values
    if isinstance(Z, pd.DataFrame):
        Z = Z.values
    
    # 표준화
    if standardize:
        X = ((X - X.mean(axis=0)) / (X.std(axis=0) + 1e-12))
        Z = ((Z - Z.mean(axis=0)) / (Z.std(axis=0) + 1e-12))
    
    # 1. 최적 컴포넌트 수 결정
    if find_best_n:
        if verbose:
            print("=" * 50)
            print("Finding optimal number of components...")
            print("=" * 50)

        max_k = min(2, X.shape[1], Z.shape[1], X.shape[0] - 1)

        if max_k < 1:
            raise ValueError("Not enough samples/features to run CCA (max_k < 1).")

        # ✅ Z가 1개(또는 min이 1)면 탐색 생략하고 1로 고정
        if max_k == 1:
            best_n = 1
            if verbose:
                print("max_k==1 -> set n_components(best_n)=1 (skip search)")
        else:
            cca = CCA(n_components=max_k)
            U_cca, V_cca = cca.fit_transform(X, Z)

            cors = []
            for i in range(max_k):
                r = np.corrcoef(U_cca[:, i], V_cca[:, i])[0, 1]
                cors.append(r)
                if verbose:
                    print(f"Component {i+1}: correlation = {r:.4f}")

            # 급격히 떨어지는 지점 찾기
            best_n = 1
            for i in range(len(cors) - 1):
                if cors[i] - cors[i + 1] > 0.1:
                    best_n = i + 1
                    break
            else:
                best_n = len([c for c in cors if c > 0.1])

            best_n = max(1, min(best_n, max_k))

            if verbose:
                print(f"\nRecommended n_components: {best_n}\n") 
    else:
        if n_components is None:
            raise ValueError("n_components must be specified when find_best_n=False")
        best_n = n_components
    
    # 2. 최적 penalty 파라미터 찾기
    if find_best_penalty:
        if verbose:
            print("=" * 50)
            print("Grid search for best penalty parameters...")
            print("=" * 50)
        
        if penalty_range is None:
            penalty_range = np.arange(0.1, 1.0, 0.1)
        
        kf = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        best_score = -np.inf
        best_penaltyu = None
        best_penaltyv = None
        results_grid = []
        
        for penaltyu, penaltyv in itertools.product(penalty_range, penalty_range):
            cv_scores = []
            
            for train_idx, val_idx in kf.split(X):
                X_train, X_val = X[train_idx], X[val_idx]
                Z_train, Z_val = Z[train_idx], Z[val_idx]
                
                try:
                    U, V, D = pmd(X_train.T @ Z_train, K=best_n,
                                 penaltyu=penaltyu, penaltyv=penaltyv,
                                 standardize=False)
                    
                    X_scores = X_val @ U[:, :best_n]
                    Z_scores = Z_val @ V[:, :best_n]
                    
                    corrs = []
                    for k in range(best_n):
                        rk = np.corrcoef(X_scores[:, k], Z_scores[:, k])[0, 1]
                        if not np.isnan(rk):
                            corrs.append(rk)
                    
                    if len(corrs) > 0:
                        cv_scores.append(np.mean(corrs))
                except:
                    continue
            
            if len(cv_scores) > 0:
                mean_score = np.mean(cv_scores)
                results_grid.append((penaltyu, penaltyv, mean_score))
                
                if mean_score > best_score:
                    best_score = mean_score
                    best_penaltyu = penaltyu
                    best_penaltyv = penaltyv
        
        if verbose:
            print(f"Best penaltyu: {best_penaltyu:.3f}")
            print(f"Best penaltyv: {best_penaltyv:.3f}")
            print(f"Best CV score: {best_score:.4f}\n")
    else:
        if penaltyu is None or penaltyv is None:
            raise ValueError("penaltyu and penaltyv must be specified when find_best_penalty=False")
        best_penaltyu = penaltyu
        best_penaltyv = penaltyv
    
    # 3. 전체 데이터에 Sparse CCA 적용
    if verbose:
        print("=" * 50)
        print("Applying Sparse CCA with best parameters...")
        print(f"penaltyu = {best_penaltyu:.3f}, penaltyv = {best_penaltyv:.3f}, n_components = {best_n}")
        print("=" * 50)
    
    U, V, D = pmd(X.T @ Z, K=best_n,
                 penaltyu=best_penaltyu,
                 penaltyv=best_penaltyv,
                 standardize=False)
    
    X_scores = X @ U[:, :best_n]
    Z_scores = Z @ V[:, :best_n]
    
    # 각 컴포넌트의 canonical correlation 계산
    sparse_cors = []
    for k in range(best_n):
        rk = np.corrcoef(X_scores[:, k], Z_scores[:, k])[0, 1]
        sparse_cors.append(rk)
        if verbose:
            print(f"Sparse CCA Component {k+1}: correlation = {rk:.4f}")
    
    if verbose:
        print(f"\nAverage correlation: {np.mean(sparse_cors):.4f}\n")
    
    # 4. Weights 확인
    if X_cols is None:
        X_cols = [f'X_{i}' for i in range(X.shape[1])]
    if Z_cols is None:
        Z_cols = [f'Z_{i}' for i in range(Z.shape[1])]
    
    X_weights_dict = {}
    Z_weights_dict = {}
    
    for k in range(best_n):
        x_weights = pd.Series(U[:, k], index=X_cols)
        z_weights = pd.Series(V[:, k], index=Z_cols)
        
        if verbose:
            print(f"=== Component {k+1} ===")
            print("\nX Weights:")
            print(x_weights.sort_values(key=abs, ascending=False))
            print(f"Non-zero weights: {(x_weights != 0).sum()} / {len(x_weights)}")
            print("\nZ Weights:")
            print(z_weights.sort_values(key=abs, ascending=False))
            print(f"Non-zero weights: {(z_weights != 0).sum()} / {len(z_weights)}\n")
        
        X_weights_dict[f'Component_{k+1}'] = x_weights
        Z_weights_dict[f'Component_{k+1}'] = z_weights
    
    # 5. 시각화
    if visualize:
        fig, axes = plt.subplots(1, best_n, figsize=(6*best_n, 5))
        if best_n == 1:
            axes = [axes]
        
        for k in range(best_n):
            axes[k].scatter(X_scores[:, k], Z_scores[:, k], alpha=0.6)
            axes[k].set_xlabel(f'X Canonical Score (Component {k+1})')
            axes[k].set_ylabel(f'Z Canonical Score (Component {k+1})')
            axes[k].set_title(f'Component {k+1}: r = {sparse_cors[k]:.4f}')
            axes[k].grid(True, alpha=0.3)
        
        plt.tight_layout()
        plt.show()
    
    # 6. Permutation Test
    permutation_pvalue = None
    if do_permutation_test:
        if verbose:
            print("\n" + "=" * 50)
            print("Permutation Test for Statistical Significance")
            print("=" * 50)
        
        def sparse_cca_statistic(X, Z, penaltyu, penaltyv, n_components):
            """Sparse CCA를 수행하고 canonical correlation의 합을 반환"""
            try:
                U, V, D = pmd(X.T @ Z, K=n_components,
                             penaltyu=penaltyu, penaltyv=penaltyv, standardize=False)
                
                X_scores = X @ U[:, :n_components]
                Z_scores = Z @ V[:, :n_components]
                
                corrs = []
                for k in range(n_components):
                    rk = np.corrcoef(X_scores[:, k], Z_scores[:, k])[0, 1]
                    if not np.isnan(rk):
                        corrs.append(rk)
                
                stat = np.sum(np.array(corrs)**2) if len(corrs) > 0 else 0.0
                return stat
            except:
                return 0.0
        
        r_obs = sparse_cca_statistic(X, Z, best_penaltyu, best_penaltyv, best_n)
        if verbose:
            print(f"Observed statistic (sum of squared correlations): {r_obs:.6f}")
            print(f"Running {n_permutations} permutations...")
        
        rng = np.random.default_rng(random_state)
        r_perm = []
        
        for i in range(n_permutations):
            idx = rng.permutation(X.shape[0])
            X_perm = X[idx, :]
            r_perm.append(sparse_cca_statistic(X_perm, Z, best_penaltyu, best_penaltyv, best_n))
            
            if verbose and (i + 1) % 100 == 0:
                print(f"  Completed {i+1}/{n_permutations} permutations...")
        
        r_perm = np.array(r_perm)
        # permutation_pvalue = np.mean(r_perm >= r_obs)
        permutation_pvalue = (np.sum(r_perm >= r_obs) + 1) / (n_permutations + 1)
        
        if verbose:
            print(f"\nPermutation p-value: {permutation_pvalue:.4f}")
            print(f"95% percentile of permuted statistics: {np.percentile(r_perm, 95):.6f}")
            print(f"99% percentile of permuted statistics: {np.percentile(r_perm, 99):.6f}")
        
        if visualize:
            plt.figure(figsize=(10, 6))
            plt.hist(r_perm, bins=50, alpha=0.7, edgecolor='black', label='Permuted statistics')
            plt.axvline(r_obs, color='red', linestyle='--', linewidth=2, label=f'Observed ({r_obs:.4f})')
            plt.axvline(np.percentile(r_perm, 95), color='orange', linestyle=':', linewidth=2, label='95th percentile')
            plt.xlabel('Test Statistic (Sum of Squared Correlations)')
            plt.ylabel('Frequency')
            plt.title(f'Permutation Test Distribution\np-value = {permutation_pvalue:.4f}')
            plt.legend()
            plt.grid(True, alpha=0.3)
            plt.show()
    
    # 결과 반환
    results = {
        'best_n': best_n,
        'best_penaltyu': best_penaltyu,
        'best_penaltyv': best_penaltyv,
        'correlations': sparse_cors,
        'X_weights': X_weights_dict,
        'Z_weights': Z_weights_dict,
        'X_scores': X_scores,
        'Z_scores': Z_scores,
        'permutation_pvalue': permutation_pvalue
    }
    
    return results

In [5]:
def run_plsr(
    X,
    y,
    n_components=1,
    x_cols=None,
    scale=True,
    verbose=True,
    do_permutation=True,
    n_permutations=1000,
    cv_splits=5,
    random_state=42,
):

    if hasattr(X, "values"):
        if x_cols is None:
            x_cols = list(X.columns)
        X_mat = X.values
    else:
        X_mat = np.asarray(X)
        if x_cols is None:
            x_cols = [f"X{i+1}" for i in range(X_mat.shape[1])]

    # y를 2D로 맞추기
    if hasattr(y, "values"):
        y_mat = np.asarray(y).reshape(-1, 1) if y.ndim == 1 else y.values
    else:
        y_arr = np.asarray(y)
        y_mat = y_arr.reshape(-1, 1) if y_arr.ndim == 1 else y_arr

    # 스케일링
    if scale:
        scaler_X = StandardScaler()
        scaler_y = StandardScaler()
        X_scaled = scaler_X.fit_transform(X_mat)
        y_scaled = scaler_y.fit_transform(y_mat)
    else:
        X_scaled = X_mat
        y_scaled = y_mat

    # PLS 적합
    pls = PLSRegression(n_components=n_components)
    pls.fit(X_scaled, y_scaled)

    # 예측 및 상관계수
    y_pred = pls.predict(X_scaled)
    r, p = pearsonr(y_scaled[:, 0], y_pred[:, 0])

    # Weights만 확인
    weights = pd.Series(pls.x_weights_[:, 0], index=x_cols).sort_values(key=abs, ascending=False)

    if verbose:
        print(f"PLSR Component 1과 y의 correlation: {r:.4f} (p={p:.4f})")
        print("\n=== PLSR Weights ===")
        print(weights)

    # Permutation test
    perm_p = None
    cv_score = None
    if do_permutation:
        try:
            pls_perm = PLSRegression(n_components=n_components)
            cv_score, perm_scores, perm_p = permutation_test_score(
                pls_perm,
                X_scaled,
                y_scaled.ravel(),
                scoring="r2",
                n_permutations=n_permutations,
                cv=cv_splits,
                random_state=random_state,
            )
            if verbose:
                print(f"\nPermutation test (R2) -> CV R2: {cv_score:.4f}, p_perm: {perm_p:.4f}")
        except Exception as e:
            if verbose:
                print(f"Permutation test failed: {e}")

    results = {
        "pls": pls,
        "r": r,
        "p": p,
        "weights": weights,
        "y_true_scaled": y_scaled[:, 0],
        "y_pred_scaled": y_pred[:, 0],
        "perm_p": perm_p,
        "cv_r2": cv_score,
    }

    return results

## 수정사항

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import svd
from statsmodels.multivariate.cancorr import CanCorr
from sparsecca import pmd
import seaborn as sns
import pingouin as pg
from sklearn.cross_decomposition import PLSRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import permutation_test_score
from scipy.stats import pearsonr
from impyute.imputation.cs import mice
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
import missingno as msno
import miceforest as mf
from sklearn.cross_decomposition import CCA
from sklearn.model_selection import KFold
import itertools

path = 'C:\\Users\\nva_kist\\Desktop\\minsun\\KIST\\BioMarker\\Merge_v2.xlsx'
df = pd.read_excel(path)

cols = ['B',	'CD11b','HLADR','NK','NKT1','T',
        'NKT2',	'MAIT'	,'gd1T','gd2T',	'ConvT%',
'CD8+T','CD4+T','CD8+Treg','CD4+Treg','CD20T','CD4trm','CD8trm','MAITtrm','GD1Ttrm',	
'GD2Ttrm','CD4grzk', 'CD8grzk','MAITgrzK','GD1TgrzK','GD2TgrzK','Transitional B',
'Memory B','Early Plasma B ','Plasma B','ABC'
]

# % 제거하기
df[cols] = (df[cols]
            .replace(r'^\s*$', pd.NA, regex=True) 
            .replace({',': ''}, regex=True)
            .replace({'%': ''}, regex=True)   
            .apply(pd.to_numeric, errors='coerce')
            *100)      

# unnamed 인 column 제거 
df = df.loc[:, ~df.columns.str.contains(r'^Unnamed')]

In [7]:
#Sex column 0,1로 바꾸기
df['Sex_01'] = df['Sex'].map({'F': 0, 'M': 1})
print(df['Sex_01'].head())

0    0
1    1
2    1
3    0
4    1
Name: Sex_01, dtype: int64

### PCA로 column 추가하기

In [8]:
# PCA로 column 추가
from sklearn.decomposition import PCA

pca_groups = {
    "CD8":  ['CD8+T', 'CD8trm', 'CD8grzk'],
    "CD8_1":['CD8trm', 'CD8grzk'],
    "CD8_2":['CD8+T', 'CD8trm'],
    "CD8_3":['CD8+T', 'CD8grzk'],

    "CD4":   ['CD4+T', 'CD4trm', 'CD4grzk'],
    "CD4_1": ['CD4trm', 'CD4grzk'],
    "CD4_2": ['CD4+T', 'CD4trm'],
    "CD4_3": ['CD4+T', 'CD4grzk'],
    
    "MAIT":   ['MAIT', 'MAITtrm', 'MAITgrzK'],
    "MAIT_1": ['MAITtrm', 'MAITgrzK'],
    "MAIT_2": ['MAIT', 'MAITtrm'],
    "MAIT_3": ['MAIT', 'MAITgrzK'],

    "GD1T":   ['gd1T', 'GD1Ttrm', 'GD1TgrzK'],
    "GD1T_1": ['GD1Ttrm', 'GD1TgrzK'],
    "GD1T_2": ['gd1T', 'GD1Ttrm'],
    "GD1T_3": ['gd1T', 'GD1TgrzK'],

    "GD2T":   ['gd2T', 'GD2Ttrm', 'GD2TgrzK'],
    "GD2T_1": ['GD2Ttrm', 'GD2TgrzK'],
    "GD2T_2": ['gd2T', 'GD2Ttrm'],
    "GD2T_3": ['gd2T', 'GD2TgrzK'],

}

pca_info = {}

df = df.copy()

def add_pc1_score(df, cols, out_col):
    # 컬럼 존재 체크
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise KeyError(f"[{out_col}] df2에 없는 컬럼이 있어요: {missing}")

    # 결측 없는 행만 PCA 계산
    tmp = df[cols].dropna()
    if tmp.shape[0] < 3:
        # 표본이 너무 적으면 그냥 NaN 채우고 메타만 남김
        df[out_col] = np.nan
        return {"explained_var_pc1": np.nan, "loadings_pc1": None, "n_used": int(tmp.shape[0])}

    # 표준화 -> PCA(PC1)
    Z = StandardScaler().fit_transform(tmp.values)
    pca = PCA(n_components=1)
    pc1 = pca.fit_transform(Z).ravel()

    # PC1 부호는 임의라서, 해석 편하게 "첫 변수"와 양의 상관이 되도록 정렬(원하면 바꾸셔도 됨)
    if np.corrcoef(pc1, Z[:, 0])[0, 1] < 0:
        pc1 = -pc1
        loadings = -pca.components_[0]
    else:
        loadings = pca.components_[0]

    # df에 넣기: 계산된 행만 채우고 나머지는 NaN 유지
    s = pd.Series(np.nan, index=df.index)
    s.loc[tmp.index] = pc1
    df[out_col] = s

    info = {
        "explained_var_pc1": float(pca.explained_variance_ratio_[0]),
        "loadings_pc1": dict(zip(cols, loadings)),
        "n_used": int(tmp.shape[0])
    }
    return info

for gname, cols in pca_groups.items():
    out_col = f"{gname}_PC1"
    info = add_pc1_score(df, cols, out_col)

# 확인
print(df[[f"{k}_PC1" for k in pca_groups.keys()]].head())

    CD8_PC1  CD8_1_PC1  CD8_2_PC1  CD8_3_PC1   CD4_PC1  CD4_1_PC1  CD4_2_PC1  \
0       NaN        NaN        NaN        NaN       NaN        NaN        NaN
1  1.270096   0.795941   1.864011   1.916927 -0.890699   0.267301  -0.968928
2       NaN        NaN        NaN        NaN       NaN        NaN        NaN
3       NaN        NaN        NaN        NaN       NaN        NaN        NaN
4 -2.447762  -2.941932  -0.139552  -0.317396 -3.121833  -2.890633  -2.414740

   CD4_3_PC1  MAIT_PC1  MAIT_1_PC1  MAIT_2_PC1  MAIT_3_PC1  GD1T_PC1  \
0        NaN       NaN         NaN         NaN         NaN       NaN
1  -1.359545 -0.493880   -0.309122   -1.019099    0.590695 -0.979231
2        NaN       NaN         NaN         NaN         NaN       NaN
3        NaN       NaN         NaN         NaN         NaN       NaN
4  -2.417959  0.496095   -0.233762    0.920678   -1.052133 -1.116262

   GD1T_1_PC1  GD1T_2_PC1  GD1T_3_PC1  GD2T_PC1  GD2T_1_PC1  GD2T_2_PC1  \
0         NaN         NaN         NaN       NaN         NaN         NaN
1   -0.866555   -1.284471   -0.433218 -0.260042   -0.019487   -0.275673
2         NaN         NaN         NaN       NaN         NaN         NaN
3         NaN         NaN         NaN       NaN         NaN         NaN
4   -0.970049   -1.017372   -1.064107  1.460894   -1.878240    0.429710

   GD2T_3_PC1
0         NaN
1   -0.738160
2         NaN
3         NaN
4    0.394068

In [9]:
df1 = df.iloc[:22]
df2 = df.iloc[22:]
print(df1.shape, df2.shape)

(22, 86) (22, 86)

In [10]:
df.columns

Index(['ID', 'Sex', 'Age', 'BMI', 'AST', 'ALT', 'ALP', 'Bilirubin', 'Protein',
       'Albumin', 'PT', 'APTT', 'Cholesterol', 'TG', 'LDL', 'HDL', 'R_Glucose',
       'F_Glucose', 'HbA1c', 'BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl', 'Amylase',
       'CRP', 'B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T', 'NKT2', 'MAIT', 'gd1T',
       'gd2T', 'ConvT%', 'CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg', 'CD20T',
       'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm', 'CD4grzk',
       'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK', 'Transitional B',
       'Memory B', 'Early Plasma B ', 'Plasma B', 'ABC', 'CD11c+CD206-',
       'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1',
       'Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4', 'Gulucose', 'Sex_01',
       'CD8_PC1', 'CD8_1_PC1', 'CD8_2_PC1', 'CD8_3_PC1', 'CD4_PC1',
       'CD4_1_PC1', 'CD4_2_PC1', 'CD4_3_PC1', 'MAIT_PC1', 'MAIT_1_PC1',
       'MAIT_2_PC1', 'MAIT_3_PC1', 'GD1T_PC1', 'GD1T_1_PC1', 'GD1T_2_PC1',
       'GD1T_3_PC1', 'GD2T_PC1', 'GD2T_1_PC1', 'GD2T_2_PC1', 'GD2T_3_PC1'],
      dtype='object')

### Task 1 . 통제변수 추가


통제변수 기존에는 BMI 성별만

추가: 콜레스테롤, gulucose + KUMC AMC동시에 가지고 있는 column

In [53]:
all_cols = [ 'B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T', 'NKT2', 'MAIT', 'gd1T',
       'gd2T', 'ConvT%', 'CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg', 'CD20T',
       'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm', 'CD4grzk',
       'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK', 'Transitional B',
       'Memory B', 'Early Plasma B ', 'Plasma B', 'ABC', 'CD11c+CD206-',
       'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1',
       'Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4']

rows = []
for c in all_cols:
    # 컬럼별 필요한 값만 결측치 제거
    df_c = df.dropna(subset=['Age', 'BMI', c]).copy()

    if df_c.shape[0] < 6:
        rows.append({"var": c, "r": None, "p": None, "n": df_c.shape[0], "note": "SKIP (n too small)"})
        continue

    res = pg.partial_corr(
        data=df_c, x='Age', y=c, covar=['BMI', 'Sex_01'], method='pearson'
    )

    rows.append({
        "var": c,
        "r": float(res['r'].iloc[0]),
        "p": float(res['p-val'].iloc[0]),
        "n": int(res['n'].iloc[0]),
        "note": ""
    })

out = pd.DataFrame(rows)

out_sorted = out.sort_values(by="p", ascending=True, na_position="last").reset_index(drop=True)

for _, row in out_sorted.iterrows():
    if pd.isna(row["p"]):
        print(f"[SKIP] Age vs {row['var']}: n={row['n']} {row['note']}".strip())
    else:
        print(f"Age vs {row['var']} | r={row['r']:.3f}, p={row['p']:.4g}, n={row['n']}")

Age vs ConvT% | r=0.496, p=0.003334, n=35
Age vs NKT2 | r=-0.422, p=0.01442, n=35
Age vs T | r=0.348, p=0.02391, n=44
Age vs HLADR | r=-0.324, p=0.03647, n=44
Age vs CD11c-CD206+ | r=0.298, p=0.05519, n=44
Age vs CD11b | r=-0.262, p=0.09348, n=44
Age vs gd2T | r=-0.286, p=0.1061, n=35
Age vs gd1T | r=-0.277, p=0.1191, n=35
Age vs Plasma B | r=0.243, p=0.1213, n=44
Age vs CD20T | r=0.233, p=0.1372, n=44
Age vs NK | r=-0.203, p=0.1974, n=44
Age vs CD11c-CD206- | r=0.201, p=0.2018, n=44
Age vs Transitional B | r=-0.180, p=0.2542, n=44
Age vs MAIT | r=-0.199, p=0.2671, n=35
Age vs CD8+Treg | r=0.194, p=0.2795, n=35
Age vs MAITtrm | r=-0.181, p=0.3146, n=35
Age vs GD1TgrzK | r=0.180, p=0.3688, n=29
Age vs MAITgrzK | r=0.149, p=0.4067, n=35
Age vs CD8+T | r=0.149, p=0.4078, n=35
Age vs CD4+Treg | r=0.148, p=0.4117, n=35
Age vs CD11c+CD206- | r=-0.127, p=0.4246, n=44
Age vs NKT1 | r=-0.120, p=0.4472, n=44
Age vs GD2TgrzK | r=0.137, p=0.4482, n=35
Age vs Early Plasma B  | r=0.120, p=0.4497, n=44
Age vs CD4trm | r=-0.136, p=0.4516, n=35
Age vs CD4+T | r=-0.133, p=0.4607, n=35
Age vs CD4grzk | r=-0.129, p=0.4746, n=35
Age vs Dectin-1+4 | r=0.108, p=0.4969, n=44
Age vs CD8trm | r=-0.120, p=0.5077, n=35
Age vs B | r=0.100, p=0.5272, n=44
Age vs CD8grzk | r=-0.107, p=0.5531, n=35
Age vs Dectin-1+1 | r=-0.072, p=0.6518, n=44
Age vs Dectin-1+3 | r=-0.059, p=0.7088, n=44
Age vs CD11c+CD206+ | r=-0.051, p=0.7472, n=44
Age vs Dectin-1+2 | r=-0.049, p=0.7556, n=44
Age vs ABC | r=0.026, p=0.8715, n=44
Age vs GD2Ttrm | r=0.025, p=0.8891, n=35
Age vs Memory B | r=0.021, p=0.8963, n=44
Age vs GD1Ttrm | r=0.013, p=0.9488, n=29

In [54]:
import numpy as np
import pandas as pd

from plotnine import (
    ggplot, aes, geom_point, geom_hline, geom_vline, geom_text,
    labs, theme_bw, theme, element_text,
    scale_color_manual, scale_size_area, scale_x_log10,
    guides
)

# =========================
# 0) 데이터 준비 (안전장치 포함)
# =========================
plot_df = out_sorted.copy()

# p, r 숫자형 강제 (문자/이상치 방지)
plot_df["p"] = pd.to_numeric(plot_df["p"], errors="coerce")
plot_df["r"] = pd.to_numeric(plot_df["r"], errors="coerce")

# 필요한 값 결측 제거 + log 축 대비(p>0)
plot_df = plot_df.dropna(subset=["p", "r"]).copy()
plot_df = plot_df[plot_df["p"] > 0].copy()

# 유의성(핑크/하늘)
plot_df["sig"] = np.where(plot_df["p"] < 0.05, "p<0.05", "ns")

# 부호(테두리)
plot_df["corr_dir"] = np.where(plot_df["r"] < 0, "negative", "positive")

# |r| 클수록 점 크게
plot_df["abs_r"] = plot_df["r"].abs()

# 라벨: p<0.05만
label_df = plot_df[plot_df["p"] < 0.05].copy()

# =========================
# 1) Plot
# =========================
p = (
    ggplot(plot_df, aes(x="p", y="r"))
    + geom_hline(yintercept=0, linetype="dashed", alpha=0.6)
    + geom_vline(xintercept=0.05, linetype="dashed", alpha=0.6)
    + scale_x_log10()  # p-value를 log 스케일로 펼쳐서 보기 좋게

    # 1) 채움(유의성): 꽉 찬 원 (stroke=0으로 테두리 제거)
    + geom_point(aes(color="sig", size="abs_r"),
                 alpha=0.85, shape="o", stroke=0)

    # 2) 테두리(부호): 빈 원(테두리만) 덮기
    + geom_point(aes(color="corr_dir", size="abs_r"),
                 alpha=0.95, shape="o", fill=None, stroke=1.8)

    # 색 매핑 (요청대로 유지)
    + scale_color_manual(values={
        "ns": "#F8766D",
        "p<0.05": "#00BFC4",
        "negative": "#00BFC4",
        "positive": "#F8766D"
    })

    # 점 크기 차이
    + scale_size_area(max_size=25)

    # p<0.05 라벨
    + geom_text(
        label_df, aes(label="var"),
        size=8, va="bottom", ha="left",
        nudge_y=0.01, nudge_x=0.02,
        show_legend=False
    )

    + labs(
        title="Partial correlation: Age vs immune features (covar: BMI)",
        x="p-value",
        y="partial r"
    )

    # ✅ 범례 완전 삭제 (color, size 전부)
    + guides(color="none", size="none")

    + theme_bw()
    + theme(
        figure_size=(10, 6),
        axis_text=element_text(size=10),
        axis_title=element_text(size=12),
    )
)

# =========================
# 2) 저장
# =========================
p.save(r"C:/Users/nva_kist/Desktop/minsun/KIST/BioMarker/1.png", dpi=300, verbose=False)
print("Saved:", r"C:/Users/nva_kist/Desktop/minsun/KIST/BioMarker/1.png")

Saved: C:/Users/nva_kist/Desktop/minsun/KIST/BioMarker/1.png

##### Age와 관련있는 면역세포 : HLADR, T, NKT2, ConvT, (CD11c-CD206+)

#####  통제변수 다르게 하며 결과 분석하기

In [57]:
import statsmodels.api as sm

def partial_corr_df(df, x, y, covars):
    cols = [x, y] + list(covars)
    d = df[cols].dropna().copy()
    n = len(d)
    if n < 6:
        return {"n": n, "r": np.nan, "p": np.nan}

    Xc = sm.add_constant(d[covars]) if len(covars) > 0 else None

    if len(covars) == 0:
        r, p = pearsonr(d[x], d[y])
        return {"n": n, "r": r, "p": p}

    rx = sm.OLS(d[x], Xc).fit().resid
    ry = sm.OLS(d[y], Xc).fit().resid
    r, p = pearsonr(rx, ry)
    return {"n": n, "r": r, "p": p}

def run_models(df, x, y_list, cov_sets, title=None, fix_n=False):
    # fix_n=True면 모든 모델에서 동일한 complete-case로 고정(비교 공정)
    if fix_n:
        all_covs = sorted({c for cov in cov_sets.values() for c in cov})
        base_cols = [x] + y_list + all_covs
        df_use = df[base_cols].dropna().copy()
    else:
        df_use = df

    rows = []
    if title:
        print(f"\n========== {title} ==========")

    for y in y_list:
        line = []
        for mname, covars in cov_sets.items():
            out = partial_corr_df(df_use, x, y, covars)
            rows.append({"y": y, "model": mname, **out})
            # 스크린샷 스타일 출력
            line.append(f"{mname}: r={out['r']:.3f}, p={out['p']:.4f}, n={out['n']}")
        print(f"{x} vs {y} | " + " | ".join(line))

    res = pd.DataFrame(rows)

    # 변화량 계산: 기준 모델 하나 잡기
    pivot_r = res.pivot(index="y", columns="model", values="r")
    base = list(cov_sets.keys())[0]  # 첫 모델을 기준으로(원하면 바꾸세요)
    for m in cov_sets.keys():
        pivot_r[f"delta_r({m}-{base})"] = pivot_r[m] - pivot_r[base]

    return res, pivot_r

# ===== 사용 예시 =====
# 1) 모델 정의
cov_sets = {
    "M0_sex": ["Sex_01"],
    "M1_BMI": ["BMI"],
    "M2_sex_BMI": ["Sex_01", "BMI"],
    "M3_sex_BMI_c": ["Sex_01", "BMI", "Cholesterol"],
    "M4_sex_BMI_g": ["Sex_01", "BMI", "Gulucose"],
}

# 2) 분석할 면역 변수 리스트
tsubset_vars = ['B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T', 'NKT2', 'MAIT', 'gd1T',
       'gd2T', 'ConvT%', 'CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg', 'CD20T',
       'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm', 'CD4grzk',
       'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK', 'Transitional B',
       'Memory B', 'Early Plasma B ', 'Plasma B', 'ABC', 'CD11c+CD206-',
       'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1',
       'Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4', 'CD8_PC1', 'CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1']

# 3) 실행
res_long, res_delta = run_models(df, x="Age", y_list=tsubset_vars, cov_sets=cov_sets,
                                 title="면역세포", fix_n=True)

# res_long: (y, model, r, p, n) long-format
# res_delta: 모델별 r + delta_r 테이블
print("\n--- delta table (r 변화) ---")
print(res_delta)

# p<=0.1인 결과만 뽑아서 보기
sig = (
    res_long
    .dropna(subset=["p"])
    .query("p <= 0.1")
    .sort_values(["p", "model", "y"])
)

print(f"Significant (p<=0.1) rows: {len(sig)}")
print(sig[["y", "model", "n", "r", "p"]].to_string(index=False))

========== 면역세포 ==========
Age vs B | M0_sex: r=0.010, p=0.9595, n=27 | M1_BMI: r=0.031, p=0.8790, n=27 | M2_sex_BMI: r=0.049, p=0.8096, n=27 | M3_sex_BMI_c: r=-0.054, p=0.7888, n=27 | M4_sex_BMI_g: r=0.023, p=0.9089, n=27
Age vs CD11b | M0_sex: r=-0.120, p=0.5517, n=27 | M1_BMI: r=-0.089, p=0.6582, n=27 | M2_sex_BMI: r=-0.083, p=0.6803, n=27 | M3_sex_BMI_c: r=-0.041, p=0.8379, n=27 | M4_sex_BMI_g: r=-0.064, p=0.7505, n=27
Age vs HLADR | M0_sex: r=-0.324, p=0.0993, n=27 | M1_BMI: r=-0.319, p=0.1054, n=27 | M2_sex_BMI: r=-0.304, p=0.1234, n=27 | M3_sex_BMI_c: r=-0.229, p=0.2496, n=27 | M4_sex_BMI_g: r=-0.278, p=0.1601, n=27
Age vs NK | M0_sex: r=-0.390, p=0.0440, n=27 | M1_BMI: r=-0.348, p=0.0752, n=27 | M2_sex_BMI: r=-0.405, p=0.0363, n=27 | M3_sex_BMI_c: r=-0.357, p=0.0679, n=27 | M4_sex_BMI_g: r=-0.402, p=0.0375, n=27
Age vs NKT1 | M0_sex: r=-0.135, p=0.5034, n=27 | M1_BMI: r=-0.123, p=0.5405, n=27 | M2_sex_BMI: r=-0.124, p=0.5392, n=27 | M3_sex_BMI_c: r=-0.070, p=0.7293, n=27 | M4_sex_BMI_g: r=-0.095, p=0.6378, n=27
Age vs T | M0_sex: r=0.383, p=0.0485, n=27 | M1_BMI: r=0.363, p=0.0628, n=27 | M2_sex_BMI: r=0.366, p=0.0606, n=27 | M3_sex_BMI_c: r=0.382, p=0.0492, n=27 | M4_sex_BMI_g: r=0.371, p=0.0570, n=27
Age vs NKT2 | M0_sex: r=-0.525, p=0.0049, n=27 | M1_BMI: r=-0.513, p=0.0062, n=27 | M2_sex_BMI: r=-0.524, p=0.0050, n=27 | M3_sex_BMI_c: r=-0.522, p=0.0053, n=27 | M4_sex_BMI_g: r=-0.539, p=0.0037, n=27
Age vs MAIT | M0_sex: r=-0.127, p=0.5284, n=27 | M1_BMI: r=-0.088, p=0.6628, n=27 | M2_sex_BMI: r=-0.067, p=0.7402, n=27 | M3_sex_BMI_c: r=0.004, p=0.9824, n=27 | M4_sex_BMI_g: r=-0.002, p=0.9925, n=27
Age vs gd1T | M0_sex: r=-0.333, p=0.0892, n=27 | M1_BMI: r=-0.376, p=0.0533, n=27 | M2_sex_BMI: r=-0.386, p=0.0465, n=27 | M3_sex_BMI_c: r=-0.384, p=0.0477, n=27 | M4_sex_BMI_g: r=-0.346, p=0.0769, n=27
Age vs gd2T | M0_sex: r=-0.251, p=0.2069, n=27 | M1_BMI: r=-0.241, p=0.2257, n=27 | M2_sex_BMI: r=-0.227, p=0.2546, n=27 | M3_sex_BMI_c: r=-0.315, p=0.1091, n=27 | M4_sex_BMI_g: r=-0.222, p=0.2667, n=27
Age vs ConvT% | M0_sex: r=0.515, p=0.0060, n=27 | M1_BMI: r=0.507, p=0.0070, n=27 | M2_sex_BMI: r=0.504, p=0.0074, n=27 | M3_sex_BMI_c: r=0.517, p=0.0058, n=27 | M4_sex_BMI_g: r=0.491, p=0.0093, n=27
Age vs CD8+T | M0_sex: r=0.264, p=0.1831, n=27 | M1_BMI: r=0.279, p=0.1586, n=27 | M2_sex_BMI: r=0.264, p=0.1825, n=27 | M3_sex_BMI_c: r=0.175, p=0.3830, n=27 | M4_sex_BMI_g: r=0.264, p=0.1836, n=27
Age vs CD4+T | M0_sex: r=-0.268, p=0.1760, n=27 | M1_BMI: r=-0.287, p=0.1473, n=27 | M2_sex_BMI: r=-0.280, p=0.1577, n=27 | M3_sex_BMI_c: r=-0.175, p=0.3834, n=27 | M4_sex_BMI_g: r=-0.308, p=0.1175, n=27
Age vs CD8+Treg | M0_sex: r=0.280, p=0.1573, n=27 | M1_BMI: r=0.301, p=0.1276, n=27 | M2_sex_BMI: r=0.356, p=0.0687, n=27 | M3_sex_BMI_c: r=0.305, p=0.1223, n=27 | M4_sex_BMI_g: r=0.466, p=0.0143, n=27
Age vs CD4+Treg | M0_sex: r=0.222, p=0.2659, n=27 | M1_BMI: r=0.229, p=0.2501, n=27 | M2_sex_BMI: r=0.264, p=0.1840, n=27 | M3_sex_BMI_c: r=0.281, p=0.1552, n=27 | M4_sex_BMI_g: r=0.336, p=0.0863, n=27
Age vs CD20T | M0_sex: r=0.363, p=0.0626, n=27 | M1_BMI: r=0.359, p=0.0660, n=27 | M2_sex_BMI: r=0.355, p=0.0691, n=27 | M3_sex_BMI_c: r=0.246, p=0.2161, n=27 | M4_sex_BMI_g: r=0.321, p=0.1023, n=27
Age vs CD4trm | M0_sex: r=-0.088, p=0.6639, n=27 | M1_BMI: r=-0.108, p=0.5916, n=27 | M2_sex_BMI: r=-0.078, p=0.6996, n=27 | M3_sex_BMI_c: r=0.008, p=0.9682, n=27 | M4_sex_BMI_g: r=-0.061, p=0.7622, n=27
Age vs CD8trm | M0_sex: r=0.042, p=0.8338, n=27 | M1_BMI: r=0.042, p=0.8370, n=27 | M2_sex_BMI: r=0.081, p=0.6867, n=27 | M3_sex_BMI_c: r=0.098, p=0.6261, n=27 | M4_sex_BMI_g: r=0.095, p=0.6379, n=27
Age vs MAITtrm | M0_sex: r=-0.070, p=0.7290, n=27 | M1_BMI: r=-0.079, p=0.6953, n=27 | M2_sex_BMI: r=-0.082, p=0.6851, n=27 | M3_sex_BMI_c: r=-0.007, p=0.9717, n=27 | M4_sex_BMI_g: r=-0.029, p=0.8857, n=27
Age vs GD1Ttrm | M0_sex: r=-0.063, p=0.7564, n=27 | M1_BMI: r=-0.015, p=0.9393, n=27 | M2_sex_BMI: r=-0.035, p=0.8607, n=27 | M3_sex_BMI_c: r=-0.087, p=0.6656, n=27 | M4_sex_BMI_g: r=-0.103, p=0.6086, n=27
Age vs GD2Ttrm | M0_sex: r=0.091, p=0.6511, n=27 | M1_BMI: r=0.129, p=0.5204, n=27 | M2_sex_BMI: r=0.126, p=0.5312, n=27 | M3_sex_BMI_c: r=0.061, p=0.7631, n=27 | M4_sex_BMI_g: r=0.165, p=0.4118, n=27
Age vs CD4grzk | M0_sex: r=-0.069, p=0.7312, n=27 | M1_BMI: r=-0.119, p=0.5545, n=27 | M2_sex_BMI: r=-0.092, p=0.6472, n=27 | M3_sex_BMI_c: r=-0.057, p=0.7789, n=27 | M4_sex_BMI_g: r=-0.084, p=0.6755, n=27
Age vs CD8grzk | M0_sex: r=0.144, p=0.4751, n=27 | M1_BMI: r=0.113, p=0.5743, n=27 | M2_sex_BMI: r=0.189, p=0.3457, n=27 | M3_sex_BMI_c: r=0.261, p=0.1880, n=27 | M4_sex_BMI_g: r=0.196, p=0.3277, n=27
Age vs MAITgrzK | M0_sex: r=0.118, p=0.5563, n=27 | M1_BMI: r=0.093, p=0.6450, n=27 | M2_sex_BMI: r=0.107, p=0.5961, n=27 | M3_sex_BMI_c: r=0.064, p=0.7510, n=27 | M4_sex_BMI_g: r=0.109, p=0.5891, n=27
Age vs GD1TgrzK | M0_sex: r=0.175, p=0.3816, n=27 | M1_BMI: r=0.183, p=0.3613, n=27 | M2_sex_BMI: r=0.205, p=0.3059, n=27 | M3_sex_BMI_c: r=0.281, p=0.1563, n=27 | M4_sex_BMI_g: r=0.177, p=0.3779, n=27
Age vs GD2TgrzK | M0_sex: r=0.147, p=0.4638, n=27 | M1_BMI: r=0.172, p=0.3916, n=27 | M2_sex_BMI: r=0.160, p=0.4252, n=27 | M3_sex_BMI_c: r=0.157, p=0.4341, n=27 | M4_sex_BMI_g: r=0.202, p=0.3113, n=27
Age vs Transitional B | M0_sex: r=-0.290, p=0.1425, n=27 | M1_BMI: r=-0.247, p=0.2143, n=27 | M2_sex_BMI: r=-0.290, p=0.1421, n=27 | M3_sex_BMI_c: r=-0.318, p=0.1061, n=27 | M4_sex_BMI_g: r=-0.306, p=0.1207, n=27
Age vs Memory B | M0_sex: r=0.038, p=0.8509, n=27 | M1_BMI: r=0.026, p=0.8970, n=27 | M2_sex_BMI: r=0.071, p=0.7248, n=27 | M3_sex_BMI_c: r=0.040, p=0.8434, n=27 | M4_sex_BMI_g: r=0.089, p=0.6586, n=27
Age vs Early Plasma B  | M0_sex: r=0.189, p=0.3458, n=27 | M1_BMI: r=0.174, p=0.3861, n=27 | M2_sex_BMI: r=0.182, p=0.3640, n=27 | M3_sex_BMI_c: r=0.234, p=0.2408, n=27 | M4_sex_BMI_g: r=0.171, p=0.3935, n=27
Age vs Plasma B | M0_sex: r=0.311, p=0.1143, n=27 | M1_BMI: r=0.262, p=0.1864, n=27 | M2_sex_BMI: r=0.292, p=0.1396, n=27 | M3_sex_BMI_c: r=0.321, p=0.1031, n=27 | M4_sex_BMI_g: r=0.295, p=0.1353, n=27
Age vs ABC | M0_sex: r=0.227, p=0.2548, n=27 | M1_BMI: r=0.226, p=0.2578, n=27 | M2_sex_BMI: r=0.253, p=0.2030, n=27 | M3_sex_BMI_c: r=0.297, p=0.1328, n=27 | M4_sex_BMI_g: r=0.286, p=0.1482, n=27
Age vs CD11c+CD206- | M0_sex: r=-0.025, p=0.9000, n=27 | M1_BMI: r=-0.065, p=0.7488, n=27 | M2_sex_BMI: r=-0.085, p=0.6730, n=27 | M3_sex_BMI_c: r=-0.009, p=0.9646, n=27 | M4_sex_BMI_g: r=-0.117, p=0.5623, n=27
Age vs CD11c+CD206+ | M0_sex: r=-0.060, p=0.7677, n=27 | M1_BMI: r=-0.044, p=0.8287, n=27 | M2_sex_BMI: r=-0.004, p=0.9834, n=27 | M3_sex_BMI_c: r=-0.020, p=0.9194, n=27 | M4_sex_BMI_g: r=0.068, p=0.7373, n=27
Age vs CD11c-CD206+ | M0_sex: r=0.107, p=0.5944, n=27 | M1_BMI: r=0.140, p=0.4871, n=27 | M2_sex_BMI: r=0.137, p=0.4958, n=27 | M3_sex_BMI_c: r=0.085, p=0.6728, n=27 | M4_sex_BMI_g: r=0.115, p=0.5672, n=27
Age vs CD11c-CD206- | M0_sex: r=0.125, p=0.5340, n=27 | M1_BMI: r=0.153, p=0.4470, n=27 | M2_sex_BMI: r=0.123, p=0.5406, n=27 | M3_sex_BMI_c: r=-0.025, p=0.9028, n=27 | M4_sex_BMI_g: r=0.085, p=0.6748, n=27
Age vs Dectin-1+1 | M0_sex: r=-0.250, p=0.2076, n=27 | M1_BMI: r=-0.310, p=0.1154, n=27 | M2_sex_BMI: r=-0.316, p=0.1081, n=27 | M3_sex_BMI_c: r=-0.219, p=0.2721, n=27 | M4_sex_BMI_g: r=-0.322, p=0.1012, n=27
Age vs Dectin-1+2 | M0_sex: r=-0.283, p=0.1523, n=27 | M1_BMI: r=-0.354, p=0.0701, n=27 | M2_sex_BMI: r=-0.358, p=0.0667, n=27 | M3_sex_BMI_c: r=-0.282, p=0.1538, n=27 | M4_sex_BMI_g: r=-0.401, p=0.0383, n=27
Age vs Dectin-1+3 | M0_sex: r=-0.158, p=0.4308, n=27 | M1_BMI: r=-0.275, p=0.1653, n=27 | M2_sex_BMI: r=-0.257, p=0.1949, n=27 | M3_sex_BMI_c: r=-0.276, p=0.1634, n=27 | M4_sex_BMI_g: r=-0.277, p=0.1620, n=27
Age vs Dectin-1+4 | M0_sex: r=-0.006, p=0.9754, n=27 | M1_BMI: r=-0.037, p=0.8543, n=27 | M2_sex_BMI: r=-0.036, p=0.8577, n=27 | M3_sex_BMI_c: r=0.000, p=0.9989, n=27 | M4_sex_BMI_g: r=-0.068, p=0.7366, n=27
Age vs CD8_PC1 | M0_sex: r=0.154, p=0.4435, n=27 | M1_BMI: r=0.142, p=0.4806, n=27 | M2_sex_BMI: r=0.205, p=0.3055, n=27 | M3_sex_BMI_c: r=0.231, p=0.2458, n=27 | M4_sex_BMI_g: r=0.216, p=0.2782, n=27
Age vs CD4_PC1 | M0_sex: r=-0.187, p=0.3494, n=27 | M1_BMI: r=-0.219, p=0.2713, n=27 | M2_sex_BMI: r=-0.197, p=0.3258, n=27 | M3_sex_BMI_c: r=-0.097, p=0.6305, n=27 | M4_sex_BMI_g: r=-0.198, p=0.3220, n=27
Age vs MAIT_PC1 | M0_sex: r=0.002, p=0.9905, n=27 | M1_BMI: r=0.037, p=0.8540, n=27 | M2_sex_BMI: r=0.057, p=0.7791, n=27 | M3_sex_BMI_c: r=0.029, p=0.8846, n=27 | M4_sex_BMI_g: r=0.056, p=0.7819, n=27
Age vs GD1T_PC1 | M0_sex: r=0.005, p=0.9809, n=27 | M1_BMI: r=0.030, p=0.8806, n=27 | M2_sex_BMI: r=0.029, p=0.8864, n=27 | M3_sex_BMI_c: r=0.043, p=0.8305, n=27 | M4_sex_BMI_g: r=-0.012, p=0.9532, n=27
Age vs GD2T_PC1 | M0_sex: r=-0.199, p=0.3208, n=27 | M1_BMI: r=-0.222, p=0.2657, n=27 | M2_sex_BMI: r=-0.211, p=0.2918, n=27 | M3_sex_BMI_c: r=-0.202, p=0.3113, n=27 | M4_sex_BMI_g: r=-0.249, p=0.2105, n=27

--- delta table (r 변화) ---
model              M0_sex    M1_BMI  M2_sex_BMI  M3_sex_BMI_c  M4_sex_BMI_g  \
y
ABC              0.227022  0.225633    0.252985      0.296782      0.285924
B                0.010257  0.030742    0.048654     -0.054063      0.023112
CD11b           -0.119817 -0.089201   -0.083107     -0.041305     -0.064171
CD11c+CD206+    -0.059625 -0.043687   -0.004192     -0.020449      0.067679
CD11c+CD206-    -0.025378 -0.064623   -0.085105     -0.008962     -0.116641
CD11c-CD206+     0.107247  0.139699    0.136955      0.085145      0.115199
CD11c-CD206-     0.125132  0.152700    0.123147     -0.024666      0.084604
CD20T            0.363133  0.358948    0.355074      0.246039      0.321222
CD4+T           -0.268321 -0.286525   -0.279697     -0.174706     -0.308446
CD4+Treg         0.221950  0.229228    0.263628      0.281272      0.336281
CD4_PC1         -0.187366 -0.219490   -0.196568     -0.096937     -0.198076
CD4grzk         -0.069314 -0.118972   -0.092261     -0.056669     -0.084415
CD4trm          -0.087599 -0.108069   -0.077824      0.008041     -0.061077
CD8+T            0.264140  0.279069    0.264468      0.174881      0.263850
CD8+Treg         0.279956  0.300583    0.355559      0.304698      0.466028
CD8_PC1          0.153859  0.141761    0.204815      0.231254      0.216459
CD8grzk          0.143514  0.113123    0.188748      0.261328      0.195799
CD8trm           0.042375  0.041541    0.081340      0.098198      0.094864
ConvT%           0.514834  0.506708    0.503929      0.516783      0.490977
Dectin-1+1      -0.250484 -0.310164   -0.316210     -0.219160     -0.322249
Dectin-1+2      -0.283194 -0.353990   -0.357995     -0.282248     -0.400784
Dectin-1+3      -0.158133 -0.274828   -0.257431     -0.276056     -0.276905
Dectin-1+4      -0.006236 -0.037087   -0.036216      0.000269     -0.067863
Early Plasma B   0.188722  0.173753    0.181826      0.233670      0.171084
GD1T_PC1         0.004834  0.030328    0.028866      0.043215     -0.011867
GD1TgrzK         0.175368  0.182843    0.204613      0.280575      0.176726
GD1Ttrm         -0.062596 -0.015379   -0.035427     -0.087130     -0.103162
GD2T_PC1        -0.198563 -0.222037   -0.210537     -0.202408     -0.248953
GD2TgrzK         0.147179  0.171764    0.160037      0.157023      0.202389
GD2Ttrm          0.091163  0.129276    0.125973      0.060843      0.164656
HLADR           -0.323881 -0.318532   -0.303844     -0.229472     -0.278116
MAIT            -0.126849 -0.087914   -0.066897      0.004462     -0.001890
MAIT_PC1         0.002412  0.037152    0.056622      0.029314      0.055873
MAITgrzK         0.118418  0.092864    0.106774      0.064028      0.108797
MAITtrm         -0.069907 -0.079010   -0.081787     -0.007159     -0.029042
Memory B         0.037949  0.026152    0.071029      0.039898      0.089085
NK              -0.390462 -0.348055   -0.404547     -0.356547     -0.402306
NKT1            -0.134565 -0.123154   -0.123555     -0.069830     -0.094877
NKT2            -0.525236 -0.513178   -0.524498     -0.521569     -0.538739
Plasma B         0.311006  0.262244    0.291850      0.320504      0.294963
T                0.383202  0.362952    0.365841      0.382060      0.370715
Transitional B  -0.289858 -0.246968   -0.290156     -0.317946     -0.305901
gd1T            -0.333475 -0.375964   -0.386383     -0.384498     -0.346244
gd2T            -0.250845 -0.241082   -0.227118     -0.315365     -0.221573

model            delta_r(M0_sex-M0_sex)  delta_r(M1_BMI-M0_sex)  \
y
ABC                                 0.0               -0.001389
B                                   0.0                0.020485
CD11b                               0.0                0.030616
CD11c+CD206+                        0.0                0.015938
CD11c+CD206-                        0.0               -0.039246
CD11c-CD206+                        0.0                0.032452
CD11c-CD206-                        0.0                0.027568
CD20T                               0.0               -0.004186
CD4+T                               0.0               -0.018204
CD4+Treg                            0.0                0.007279
CD4_PC1                             0.0               -0.032124
CD4grzk                             0.0               -0.049658
CD4trm                              0.0               -0.020470
CD8+T                               0.0                0.014929
CD8+Treg                            0.0                0.020626
CD8_PC1                             0.0               -0.012099
CD8grzk                             0.0               -0.030390
CD8trm                              0.0               -0.000834
ConvT%                              0.0               -0.008126
Dectin-1+1                          0.0               -0.059680
Dectin-1+2                          0.0               -0.070796
Dectin-1+3                          0.0               -0.116695
Dectin-1+4                          0.0               -0.030851
Early Plasma B                      0.0               -0.014969
GD1T_PC1                            0.0                0.025494
GD1TgrzK                            0.0                0.007475
GD1Ttrm                             0.0                0.047216
GD2T_PC1                            0.0               -0.023474
GD2TgrzK                            0.0                0.024585
GD2Ttrm                             0.0                0.038113
HLADR                               0.0                0.005349
MAIT                                0.0                0.038935
MAIT_PC1                            0.0                0.034741
MAITgrzK                            0.0               -0.025554
MAITtrm                             0.0               -0.009102
Memory B                            0.0               -0.011796
NK                                  0.0                0.042407
NKT1                                0.0                0.011411
NKT2                                0.0                0.012058
Plasma B                            0.0               -0.048762
T                                   0.0               -0.020250
Transitional B                      0.0                0.042891
gd1T                                0.0               -0.042489
gd2T                                0.0                0.009763

model            delta_r(M2_sex_BMI-M0_sex)  delta_r(M3_sex_BMI_c-M0_sex)  \
y
ABC                                0.025963                      0.069760
B                                  0.038396                     -0.064320
CD11b                              0.036710                      0.078512
CD11c+CD206+                       0.055432                      0.039175
CD11c+CD206-                      -0.059728                      0.016416
CD11c-CD206+                       0.029708                     -0.022102
CD11c-CD206-                      -0.001985                     -0.149798
CD20T                             -0.008059                     -0.117094
CD4+T                             -0.011376                      0.093615
CD4+Treg                           0.041679                      0.059323
CD4_PC1                           -0.009201                      0.090430
CD4grzk                           -0.022947                      0.012645
CD4trm                             0.009776                      0.095641
CD8+T                              0.000328                     -0.089259
CD8+Treg                           0.075602                      0.024741
CD8_PC1                            0.050956                      0.077394
CD8grzk                            0.045234                      0.117814
CD8trm                             0.038965                      0.055824
ConvT%                            -0.010905                      0.001950
Dectin-1+1                        -0.065726                      0.031324
Dectin-1+2                        -0.074801                      0.000946
Dectin-1+3                        -0.099298                     -0.117923
Dectin-1+4                        -0.029980                      0.006504
Early Plasma B                    -0.006896                      0.044947
GD1T_PC1                           0.024032                      0.038381
GD1TgrzK                           0.029245                      0.105207
GD1Ttrm                            0.027169                     -0.024534
GD2T_PC1                          -0.011974                     -0.003845
GD2TgrzK                           0.012858                      0.009844
GD2Ttrm                            0.034810                     -0.030320
HLADR                              0.020037                      0.094409
MAIT                               0.059952                      0.131311
MAIT_PC1                           0.054210                      0.026903
MAITgrzK                          -0.011644                     -0.054389
MAITtrm                           -0.011880                      0.062749
Memory B                           0.033080                      0.001949
NK                                -0.014085                      0.033915
NKT1                               0.011011                      0.064736
NKT2                               0.000738                      0.003667
Plasma B                          -0.019157                      0.009498
T                                 -0.017361                     -0.001142
Transitional B                    -0.000297                     -0.028088
gd1T                              -0.052908                     -0.051024
gd2T                               0.023727                     -0.064520

model            delta_r(M4_sex_BMI_g-M0_sex)
y
ABC                                  0.058902
B                                    0.012855
CD11b                                0.055646
CD11c+CD206+                         0.127304
CD11c+CD206-                        -0.091264
CD11c-CD206+                         0.007952
CD11c-CD206-                        -0.040528
CD20T                               -0.041911
CD4+T                               -0.040125
CD4+Treg                             0.114331
CD4_PC1                             -0.010710
CD4grzk                             -0.015101
CD4trm                               0.026522
CD8+T                               -0.000290
CD8+Treg                             0.186071
CD8_PC1                              0.062600
CD8grzk                              0.052286
CD8trm                               0.052489
ConvT%                              -0.023856
Dectin-1+1                          -0.071765
Dectin-1+2                          -0.117590
Dectin-1+3                          -0.118772
Dectin-1+4                          -0.061628
Early Plasma B                      -0.017638
GD1T_PC1                            -0.016701
GD1TgrzK                             0.001358
GD1Ttrm                             -0.040566
GD2T_PC1                            -0.050390

In [70]:
import numpy as np
import pandas as pd
from plotnine import *

# =========================
# 0) 데이터 준비
# =========================
plot_df = res_long.dropna(subset=["r", "p"]).copy()

# (선택) 숫자형 강제 변환
plot_df["r"] = pd.to_numeric(plot_df["r"], errors="coerce")
plot_df["p"] = pd.to_numeric(plot_df["p"], errors="coerce")
plot_df = plot_df.dropna(subset=["r", "p"]).copy()

# ✅ x축 라벨 매핑
label_map = {
    "M0_sex": "sex",
    "M1_BMI": "BMI",
    "M2_sex_BMI": "sex + BMI",
    "M3_sex_BMI_c": "sex + BMI + Cholesterol",
    "M4_sex_BMI_g": "sex + BMI + Glucose",
}
plot_df["model"] = plot_df["model"].map(label_map)

# ✅ 원하는 순서 고정
new_order = ["sex", "BMI", "sex + BMI", "sex + BMI + Cholesterol", "sex + BMI + Glucose"]
plot_df["model"] = pd.Categorical(plot_df["model"], categories=new_order, ordered=True)

# =========================
# 1) 유의성 구간 나누기
# =========================
sig_df = plot_df[plot_df["p"] < 0.05].copy()
mid_df = plot_df[(plot_df["p"] >= 0.05) & (plot_df["p"] < 0.1)].copy()
# p>=0.1 은 표시 안 함

# =========================
# 2) Heatmap + 표시 오버레이
# =========================
p_heat = (
    ggplot(plot_df, aes(x="model", y="y", fill="r"))
    + geom_tile()

    # ✅ 0.05 <= p < 0.1 : 작은 점(·)
    + geom_text(
        mid_df,
        aes(x="model", y="y", label="'·'"),
        inherit_aes=False,
        size=15,
        alpha=0.7
    )

    # ✅ p < 0.05 : 별(*)
    + geom_text(
        sig_df,
        aes(x="model", y="y", label="'*'"),
        inherit_aes=False,
        size=15,
        alpha=0.95
    )

    + scale_fill_gradient2(low="#00BFC4", mid="white", high="#F8766D")
    + labs(
        title="Age & Immune cell by covariate (*: p<0.05, ·: 0.05≤p<0.1)",
        x="Covariates (model)",
        y="Immune feature",
        fill="r"
    )
    + theme_bw()
    + theme(
        figure_size=(12, 12),
        axis_text_y=element_text(size=7),
        axis_text_x=element_text(size=9)
    )
)

print(p_heat)

# =========================
# 3) 저장
# =========================
p_heat.save("heatmap_r_by_model_pgroup.png", dpi=300, verbose=False)
print("Saved: heatmap_r_by_model_pgroup.png")

<ggplot: (1200 x 1200)>
Saved: heatmap_r_by_model_pgroup.png

In [71]:
from plotnine import *

rank_df = (
    res_long.dropna(subset=["p","r"])
    .assign(p=lambda d: pd.to_numeric(d["p"], errors="coerce"))
    .dropna(subset=["p"])
    .query("p > 0")
    .copy()
)

# ✅ 모델 라벨 매핑(이전에 쓰던거)
label_map = {
    "M0_sex": "sex",
    "M1_BMI": "BMI",
    "M2_sex_BMI": "sex + BMI",
    "M3_sex_BMI_c": "sex + BMI + Cholesterol",
    "M4_sex_BMI_g": "sex + BMI + Glucose",
}
rank_df["model"] = rank_df["model"].map(label_map)

# ✅ -log10(p) (클수록 더 유의)
rank_df["mlog10p"] = -np.log10(rank_df["p"])

# 예: 모델별 Top 10
topN = 10
top_df = (rank_df.sort_values(["model","p"])
                  .groupby("model")
                  .head(topN)
                  .copy())

p_rank = (
    ggplot(top_df, aes(x="reorder(y, mlog10p)", y="mlog10p", fill="r"))
    + geom_col()
    + coord_flip()
    + facet_wrap("~model", scales="free_y")
    + scale_fill_gradient2(low="#00BFC4", mid="white", high="#F8766D")
    + labs(title=f"Top {topN} smallest p-values per model", x="Immune feature", y="-log10(p)", fill="r")
    + theme_bw()
    + theme(figure_size=(12, 8), axis_text=element_text(size=8))
)

print(p_rank)
p_rank.save("p_rank_topN_by_model.png", dpi=300, verbose=False)

<ggplot: (1200 x 800)>

## Task2 - (1)KUMC 분석

In [ ]:
# 하나씩 test해보자

# df1 - KUMC, 결측치 제거 후 sCCA 진행 

# 1) 그룹 정의
X_groups = {
    "Metabolic": ['R_Glucose', 'Cholesterol'],
    "Liver": ['AST', 'ALT', 'ALP', 'Bilirubin', 'Protein', 'Albumin'],
    "Liver1" : ['AST', 'ALT', 'ALP'],
    "Liver2" : ['Bilirubin', 'Protein', 'Albumin'],
    "Kidney": ['BUN', 'Cr'],
    "ETC": ['Amylase', 'CRP'],
    "All": ['AST', 'ALT', 'ALP', 'Bilirubin', 'Protein', 'Albumin', 
               'Cholesterol', 'R_Glucose', 'BUN', 'Cr', 'Amylase', 'CRP']
               }

# 박사님 그룹
Z_groups = {"GD2T": ['gd2T','GD2Ttrm', 'GD2TgrzK'],
            "GD2T_1" : ['GD2T_1_PC1', 'gd2T'],
            "GD2T_2": ['GD2Ttrm', 'GD2TgrzK'],
            "GD2T_3": ['gd2T']}

rows = []
for x_name, X_cols in X_groups.items():
    for z_name, Z_cols in Z_groups.items():
        use_cols = X_cols + Z_cols

        # 결측치 있는 행 제거 
        df_clean = df1.dropna(subset=use_cols).copy()
        n = df_clean.shape[0]

        if n < 6:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": "SKIP(n too small)"
            })
            continue

        X = df_clean[X_cols]
        Z = df_clean[Z_cols]


        try:
            results = apply_sparse_cca(
                X, Z,
                X_cols=X_cols, Z_cols=Z_cols,
                verbose=False,
                visualize=False
            )

            r = results.get("correlations", None)
            p = results.get("permutation_pvalue", None)

            r1 = float(r[0]) if isinstance(r, (list, tuple, np.ndarray)) else float(r)

            rows.append({
                "X_group": x_name,
                "Z_group": z_name,
                "n": n,
                "r1": r1,
                "p_perm": p,
                "status": "OK"
            })

        except Exception as e:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": f"FAIL: {type(e).__name__}"
            })

res_df = pd.DataFrame(rows)
res_df_sorted = res_df.sort_values(["status", "p_perm"], ascending=[True, True])
print(res_df_sorted)

      X_group Z_group   n        r1    p_perm status
3       Liver    GD2T  12  0.838574  0.074925     OK
4       Liver  GD2T_1  12  0.826399  0.085914     OK
7      Liver1  GD2T_1  12  0.650609  0.242757     OK
6      Liver1    GD2T  12  0.652845  0.250749     OK
0   Metabolic    GD2T  11  0.604961  0.260739     OK
10     Liver2  GD2T_1  13  0.557880  0.311688     OK
17        ETC  GD2T_2  11  0.429867  0.388611     OK
18        All    GD2T  10  0.794259  0.407592     OK
11     Liver2  GD2T_2  13  0.432814  0.450549     OK
19        All  GD2T_1  10  0.667012  0.471528     OK
16        ETC  GD2T_1  11  0.426885  0.488511     OK
13     Kidney  GD2T_1  13  0.373213  0.590410     OK
9      Liver2    GD2T  13  0.443645  0.614386     OK
15        ETC    GD2T  11  0.417031  0.631369     OK
20        All  GD2T_2  10  0.716708  0.650350     OK
12     Kidney    GD2T  13  0.373213  0.672328     OK
1   Metabolic  GD2T_1  11  0.404530  0.692308     OK
8      Liver1  GD2T_2  12  0.370781  0.706294     OK
2   Metabolic  GD2T_2  11  0.299448  0.792208     OK
5       Liver  GD2T_2  12  0.451042  0.822178     OK
14     Kidney  GD2T_2  13  0.245863  0.838162     OK

In [18]:
# df1 - KUMC, 결측치 제거 후 sCCA 진행 
# 전체 df1 & 면역세포

# 1) 그룹 정의
X_groups = {
    "Metabolic": ['R_Glucose', 'Cholesterol'],
    "Liver": ['AST', 'ALT', 'ALP', 'Bilirubin', 'Protein', 'Albumin'],
    "Liver1" : ['AST', 'ALT', 'ALP','Bilirubin'],
    "Liver2" : [ 'Protein', 'Albumin'],
    "Kidney": ['BUN', 'Cr'],
    "ETC": ['Amylase', 'CRP'],
    # "All": ['AST', 'ALT', 'ALP', 'Bilirubin', 'Protein', 'Albumin', 
    #            'Cholesterol', 'R_Glucose', 'BUN', 'Cr', 'Amylase', 'CRP']
               }

# 박사님 그룹
Z_groups = {
    "B" : ["Transitional B", "Memory B", "Early Plasma B ", "Plasma B", "ABC"],
    "T" : ['NKT2', 'MAIT', 'gd1T','gd2T', 'ConvT%'],
    "ConvT": ['CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg'],
    "PAN": ['B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T'], 
    "CD8":  ['CD8+T', 'CD8trm', 'CD8grzk'],
    "CD4":  ['CD4+T',  'CD4trm', 'CD4grzk'],
    "MAIT": ['MAIT', 'MAITtrm', 'MAITgrzK'],
    "CD20T":["CD20T"],
    "GD1T": ['gd1T','GD1Ttrm', 'GD1TgrzK'],
    "GD2T": ['gd2T','GD2Ttrm', 'GD2TgrzK'],
    "PCA" : ['CD8_PC1','CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1'],
    "CD11c": ['CD11c+CD206-', 'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1','Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4'],
    "Detectin":[ 'Dectin-1+1','Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4'],
    "CD11c_1" :['CD11c+CD206-', 'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-']
}


rows = []
for x_name, X_cols in X_groups.items():
    for z_name, Z_cols in Z_groups.items():
        use_cols = X_cols + Z_cols

        # 결측치 있는 행 제거 
        df_clean = df1.dropna(subset=use_cols).copy()
        n = df_clean.shape[0]

        if n < 6:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": "SKIP(n too small)"
            })
            continue

        X = df_clean[X_cols]
        Z = df_clean[Z_cols]


        try:
            results = apply_sparse_cca(
                X, Z,
                X_cols=X_cols, Z_cols=Z_cols,
                verbose=False,
                visualize=False
            )

            r = results.get("correlations", None)
            p = results.get("permutation_pvalue", None)

            r1 = float(r[0]) if isinstance(r, (list, tuple, np.ndarray)) else float(r)

            rows.append({
                "X_group": x_name,
                "Z_group": z_name,
                "n": n,
                "r1": r1,
                "p_perm": p,
                "status": "OK"
            })

        except Exception as e:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": f"FAIL: {type(e).__name__}"
            })

res_df = pd.DataFrame(rows)
res_df_sorted1 = res_df.sort_values(["status", "p_perm"], ascending=[True, True])
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
res_df_sorted1

      X_group   Z_group   n        r1    p_perm status
16      Liver     ConvT  12  0.860993  0.006993     OK
56     Kidney         B  22  0.606120  0.020979     OK
82        ETC  Detectin  18  0.615581  0.022977     OK
42     Liver2         B  22  0.676248  0.024975     OK
29     Liver1         T  12  0.818518  0.032967     OK
74        ETC       CD8  11  0.867487  0.035964     OK
59     Kidney       PAN  22  0.687289  0.037962     OK
81        ETC     CD11c  18  0.615581  0.047952     OK
32     Liver1       CD8  12  0.837781  0.054945     OK
23      Liver      GD2T  12  0.838574  0.074925     OK
50     Liver2      GD1T  13  0.652967  0.075924     OK
14      Liver         B  21  0.662184  0.084915     OK
73        ETC       PAN  18  0.708071  0.120879     OK
37     Liver1      GD2T  12  0.770170  0.132867     OK
68     Kidney  Detectin  22  0.464461  0.157842     OK
2   Metabolic     ConvT  11  0.663624  0.167832     OK
48     Liver2      MAIT  13  0.561877  0.183816     OK
5   Metabolic       CD4  11  0.661196  0.184815     OK
30     Liver1     ConvT  12  0.749598  0.191808     OK
67     Kidney     CD11c  22  0.575182  0.202797     OK
83        ETC   CD11c_1  18  0.486563  0.205794     OK
40     Liver1  Detectin  21  0.543751  0.206793     OK
15      Liver         T  12  0.734030  0.212787     OK
10  Metabolic       PCA  11  0.706002  0.221778     OK
1   Metabolic         T  11  0.717775  0.240759     OK
9   Metabolic      GD2T  11  0.604961  0.260739     OK
49     Liver2     CD20T  22  0.287881  0.264735     OK
7   Metabolic     CD20T  20  0.371683  0.274725     OK
57     Kidney         T  13  0.648361  0.280719     OK
70        ETC         B  18  0.543063  0.280719     OK
6   Metabolic      MAIT  11  0.641067  0.294705     OK
60     Kidney       CD8  13  0.618213  0.294705     OK
52     Liver2       PCA  13  0.580060  0.300699     OK
18      Liver       CD8  12  0.684973  0.302697     OK
69     Kidney   CD11c_1  22  0.419036  0.302697     OK
46     Liver2       CD8  13  0.525747  0.358641     OK
77        ETC     CD20T  18  0.310227  0.363636     OK
55     Liver2   CD11c_1  22  0.372331  0.372627     OK
51     Liver2      GD2T  13  0.408487  0.382617     OK
64     Kidney      GD1T  13  0.550691  0.389610     OK
8   Metabolic      GD1T  11  0.565875  0.399600     OK
45     Liver2       PAN  22  0.445274  0.406593     OK
43     Liver2         T  13  0.545466  0.409590     OK
54     Liver2  Detectin  22  0.342453  0.432567     OK
28     Liver1         B  21  0.484439  0.463536     OK
66     Kidney       PCA  13  0.541086  0.472527     OK
12  Metabolic  Detectin  20  0.373243  0.483516     OK
36     Liver1      GD1T  12  0.550946  0.489510     OK
80        ETC       PCA  11  0.583703  0.489510     OK
26      Liver  Detectin  21  0.529274  0.500500     OK
72        ETC     ConvT  11  0.533183  0.507493     OK
75        ETC       CD4  11  0.505944  0.514486     OK
53     Liver2     CD11c  22  0.354884  0.527473     OK
22      Liver      GD1T  12  0.695847  0.537463     OK
58     Kidney     ConvT  13  0.441750  0.541459     OK
39     Liver1     CD11c  21  0.605636  0.555445     OK
4   Metabolic       CD8  11  0.542845  0.560440     OK
61     Kidney       CD4  13  0.523979  0.560440     OK
0   Metabolic         B  20  0.385317  0.576424     OK
27      Liver   CD11c_1  21  0.520353  0.597403     OK
79        ETC      GD2T  11  0.417031  0.631369     OK
24      Liver       PCA  12  0.594496  0.638362     OK
63     Kidney     CD20T  22  0.184636  0.648352     OK
65     Kidney      GD2T  13  0.373213  0.672328     OK
25      Liver     CD11c  21  0.515411  0.685315     OK
31     Liver1       PAN  21  0.480528  0.685315     OK
38     Liver1       PCA  12  0.586686  0.705295     OK
11  Metabolic     CD11c  20  0.373243  0.707293     OK
76        ETC      MAIT  11  0.395577  0.729271     OK
47     Liver2       CD4  13  0.332282  0.737263     OK
41     Liver1   CD11c_1  21  0.419531  0.746254     OK
21      Liver     CD20T  21  0.263724  0.767233     OK
33     Liver1       CD4  12  0.490264  0.784216     OK
13  Metabolic   CD11c_1  20  0.308035  0.794206     OK
62     Kidney      MAIT  13  0.363122  0.814186     OK
78        ETC      GD1T  11  0.498957  0.823177     OK
20      Liver      MAIT  12  0.572958  0.825175     OK
34     Liver1      MAIT  12  0.572134  0.843157     OK
44     Liver2     ConvT  13  0.230686  0.843157     OK
17      Liver       PAN  21  0.444546  0.879121     OK
71        ETC         T  11  0.371518  0.917083     OK
3   Metabolic       PAN  20  0.279021  0.940060     OK
35     Liver1     CD20T  21  0.090499  0.985015     OK
19      Liver       CD4  12  0.303638  1.000000     OK

### Task2- ssca df2에 적용

In [19]:
#df2로 동일한 진행 - 결측치는 삭제하고 sparse cca, 간신장대사 나눠서 진행

# 1) df2용 그룹 정의 

X_groups = {
    "Liver":   ['AST', 'ALT', 'ALP', 'Bilirubin', 'Albumin', 'PT', 'APTT'],
    "Liver1" : ['AST', 'ALT', 'ALP', 'PT', 'APTT', 'Bilirubin'] , 
    "Liver2":["Albumin"],
    "Metabolic": ['TG', 'LDL',  'F_Glucose', 'HbA1c', 'Cholesterol','HDL'],
    "HDL": ['HDL'],
    "Metaboilic1":['TG', 'LDL',  'F_Glucose', 'HbA1c', 'Cholesterol'],
    "Kidney": ['BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl'],
    "Kidney1": ['BUN', 'Cr'],
    "Kidney2": ['GFR(CKD_EPI)', 'CrCl'],
}


# 박사님 그룹
Z_groups = {
    "B" : ["Transitional B", "Memory B", "Early Plasma B ", "Plasma B", "ABC"],
    "T" : ['NKT2', 'MAIT', 'gd1T','gd2T', 'ConvT%'],
    "ConvT": ['CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg'],
    "PAN": ['B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T'], 
    "CD8":  ['CD8+T', 'CD8trm', 'CD8grzk'],
    "CD4":  ['CD4+T',  'CD4trm', 'CD4grzk'],
    "MAIT": ['MAIT', 'MAITtrm', 'MAITgrzK'],
    "GD1T": ['gd1T','GD1Ttrm', 'GD1TgrzK'],
    "GD2T": ['gd2T','GD2Ttrm', 'GD2TgrzK'],
    "PCA" : ['CD8_PC1','CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1'],
    "CD11c": ['CD11c+CD206-', 'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1','Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4'],
    "Detectin":[ 'Dectin-1+1','Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4'],
    "CD11c_1" :['CD11c+CD206-', 'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-']
}


rows = []
for x_name, X_cols in X_groups.items():
    for z_name, Z_cols in Z_groups.items():
        use_cols = X_cols + Z_cols

        # 조합별 결측치 행 제거
        df_clean = df2.dropna(subset=use_cols).copy()
        n = df_clean.shape[0]

        if n < 6:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": "SKIP(n too small)"
            })
            continue

        X = df_clean[X_cols]
        Z = df_clean[Z_cols]

        try:
            results = apply_sparse_cca(
                X, Z,
                X_cols=X_cols, Z_cols=Z_cols,
                verbose=False,
                visualize=False
            )

            r = results.get("correlations", None)
            p = results.get("permutation_pvalue", None)

            r1 = float(r[0]) if isinstance(r, (list, tuple, np.ndarray)) else float(r)

            rows.append({
                "X_group": x_name,
                "Z_group": z_name,
                "n": n,
                "r1": r1,
                "p_perm": p,
                "status": "OK"
            })

        except Exception as e:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": f"FAIL: {type(e).__name__}"
            })

res_df = pd.DataFrame(rows)

res_df_sorted2 = res_df.sort_values(["status", "p_perm"], ascending=[True, True])
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
res_df_sorted2

C:\Users\nva_kist\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\nva_kist\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\nva_kist\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\nva_kist\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\nva_kist\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\nva_kist\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

         X_group   Z_group   n        r1    p_perm status
34        Liver2      GD2T  22  0.718038  0.000999     OK
8          Liver      GD2T  22  0.775333  0.003996     OK
15        Liver1     ConvT  22  0.755233  0.003996     OK
2          Liver     ConvT  22  0.758536  0.005994     OK
110      Kidney2      MAIT  22  0.544622  0.045954     OK
55           HDL       PAN  22  0.577672  0.046953     OK
77   Metaboilic1   CD11c_1  22  0.659663  0.067932     OK
71   Metaboilic1      MAIT  22  0.639751  0.080919     OK
84        Kidney      MAIT  22  0.544622  0.090909     OK
91       Kidney1         B  22  0.549385  0.092907     OK
35        Liver2       PCA  16  0.563627  0.097902     OK
51     Metabolic   CD11c_1  22  0.643688  0.097902     OK
73   Metaboilic1      GD2T  22  0.639214  0.107892     OK
47     Metabolic      GD2T  22  0.643715  0.115884     OK
79        Kidney         T  22  0.611599  0.142857     OK
105      Kidney2         T  22  0.515236  0.144855     OK
45     Metabolic      MAIT  22  0.617614  0.147852     OK
63           HDL  Detectin  22  0.390577  0.163836     OK
85        Kidney      GD1T  16  0.694696  0.174825     OK
19        Liver1      MAIT  22  0.538614  0.182817     OK
58           HDL      MAIT  22  0.416007  0.194805     OK
14        Liver1         T  22  0.602213  0.196803     OK
6          Liver      MAIT  22  0.538614  0.203796     OK
18        Liver1       CD4  22  0.569407  0.233766     OK
22        Liver1       PCA  16  0.654984  0.242757     OK
42     Metabolic       PAN  22  0.605146  0.244755     OK
27        Liver2         T  22  0.394318  0.251748     OK
13        Liver1         B  22  0.416945  0.253746     OK
7          Liver      GD1T  16  0.519989  0.259740     OK
49     Metabolic     CD11c  22  0.657738  0.259740     OK
5          Liver       CD4  22  0.535281  0.268731     OK
78        Kidney         B  22  0.552046  0.272727     OK
92       Kidney1         T  22  0.439702  0.274725     OK
60           HDL      GD2T  22  0.385905  0.291708     OK
59           HDL      GD1T  16  0.437770  0.323676     OK
62           HDL     CD11c  22  0.388022  0.329670     OK
102      Kidney1  Detectin  22  0.352106  0.351648     OK
98       Kidney1      GD1T  16  0.489559  0.352647     OK
68   Metaboilic1       PAN  22  0.553050  0.353646     OK
20        Liver1      GD1T  16  0.484028  0.363636     OK
26        Liver2         B  22  0.371924  0.370629     OK
107      Kidney2       PAN  22  0.539439  0.410589     OK
40     Metabolic         T  22  0.532142  0.411588     OK
111      Kidney2      GD1T  16  0.456034  0.432567     OK
113      Kidney2       PCA  16  0.559629  0.433566     OK
116      Kidney2   CD11c_1  22  0.380406  0.454545     OK
9          Liver       PCA  16  0.589415  0.457542     OK
75   Metaboilic1     CD11c  22  0.600887  0.472527     OK
66   Metaboilic1         T  22  0.527823  0.486513     OK
1          Liver         T  22  0.462350  0.494505     OK
67   Metaboilic1     ConvT  22  0.469937  0.504496     OK
24        Liver1  Detectin  22  0.409989  0.506494     OK
89        Kidney  Detectin  22  0.352106  0.522478     OK
109      Kidney2       CD4  22  0.369362  0.529471     OK
50     Metabolic  Detectin  22  0.390577  0.561439     OK
41     Metabolic     ConvT  22  0.488198  0.573427     OK
21        Liver1      GD2T  22  0.509269  0.595405     OK
37        Liver2  Detectin  22  0.228086  0.595405     OK
112      Kidney2      GD2T  22  0.387234  0.597403     OK
64           HDL   CD11c_1  22  0.258658  0.610390     OK
81        Kidney       PAN  22  0.558242  0.612388     OK
11         Liver  Detectin  22  0.452495  0.616384     OK
57           HDL       CD4  22  0.254914  0.618382     OK
104      Kidney2         B  22  0.355056  0.621379     OK
87        Kidney       PCA  16  0.466667  0.641359     OK
90        Kidney   CD11c_1  22  0.380406  0.644356     OK
56           HDL       CD8  22  0.202700  0.652348     OK
94       Kidney1       PAN  22  0.442418  0.679321     OK
114      Kidney2     CD11c  22  0.381015  0.693307     OK
70   Metaboilic1       CD4  22  0.399811  0.694306     OK
61           HDL       PCA  16  0.298697  0.702298     OK
72   Metaboilic1      GD1T  16  0.501567  0.706294     OK
46     Metabolic      GD1T  16  0.505727  0.710290     OK
30        Liver2       CD8  22  0.181639  0.713287     OK
52           HDL         B  22  0.263285  0.742258     OK
69   Metaboilic1       CD8  22  0.338650  0.745255     OK
108      Kidney2       CD8  22  0.290533  0.746254     OK
3          Liver       PAN  22  0.484286  0.751249     OK
54           HDL     ConvT  22  0.210819  0.754246     OK
0          Liver         B  22  0.460225  0.755245     OK
33        Liver2      GD1T  16  0.248347  0.764236     OK
76   Metaboilic1  Detectin  22  0.331658  0.791209     OK
101      Kidney1     CD11c  22  0.362889  0.791209     OK
43     Metabolic       CD8  22  0.338650  0.793207     OK
103      Kidney1   CD11c_1  22  0.292777  0.809191     OK
4          Liver       CD8  22  0.411551  0.813187     OK
86        Kidney      GD2T  22  0.357007  0.814186     OK
99       Kidney1      GD2T  22  0.317431  0.816184     OK
83        Kidney       CD4  22  0.205173  0.839161     OK
95       Kidney1       CD8  22  0.235032  0.850150     OK
39     Metabolic         B  22  0.334255  0.854146     OK
93       Kidney1     ConvT  22  0.237024  0.854146     OK
106      Kidney2     ConvT  22  0.252729  0.860140     OK
17        Liver1       CD8  22  0.398867  0.865135     OK
29        Liver2       PAN  22  0.303670  0.870130     OK
23        Liver1     CD11c  22  0.409989  0.887113     OK
16        Liver1       PAN  22  0.468764  0.898102     OK
28        Liver2     ConvT  22  0.127337  0.901099     OK
36        Liver2     CD11c  22  0.247459  0.907093     OK
65   Metaboilic1         B  22  0.305063  0.908092     OK
100      Kidney1       PCA  16  0.363329  0.912088     OK
82        Kidney       CD8  22  0.290338  0.913087     OK
115      Kidney2  Detectin  22  0.191481  0.914086     OK
38        Liver2   CD11c_1  22  0.138191  0.918082     OK
96       Kidney1       CD4  22  0.176694  0.929071     OK
88        Kidney     CD11c  22  0.366586  0.930070     OK
97       Kidney1      MAIT  22  0.193250  0.939061     OK
10         Liver     CD11c  22  0.419048  0.947053     OK
53           HDL         T  22  0.130579  0.955045     OK
31        Liver2       CD4  22  0.096630  0.958042     OK
44     Metabolic       CD4  22  0.294630  0.961039     OK
74   Metaboilic1       PCA  16  0.342588  0.966034     OK
32        Liver2      MAIT  22  0.087373  0.972028     OK
48     Metabolic       PCA  16  0.401293  0.973027     OK
25        Liver1   CD11c_1  22  0.296447  0.975025     OK
12         Liver   CD11c_1  22  0.301760  0.983017     OK
80        Kidney     ConvT  22  0.177581  0.996004     OK

## scca에서 통제한 후에

In [16]:
import statsmodels.api as sm

# -----------------------------
# 0) residualize helper
# -----------------------------
def residualize_df(mat_df: pd.DataFrame, cov_df: pd.DataFrame) -> pd.DataFrame:
    """
    mat_df: (n x p) matrix dataframe (X or Z)
    cov_df: (n x k) covariates dataframe (BMI, Sex_01 etc.)
    return: residualized mat_df (same shape/cols)
    """
    Xc = sm.add_constant(cov_df.astype(float), has_constant="add")
    resid = {}
    for col in mat_df.columns:
        y = mat_df[col].astype(float).values
        fit = sm.OLS(y, Xc).fit()
        resid[col] = fit.resid
    return pd.DataFrame(resid, index=mat_df.index)

# -----------------------------
# 1) 그룹 정의 (원본 그대로)
# -----------------------------
X_groups = {
    "Metabolic": ['R_Glucose', 'Cholesterol'],
    "Liver": ['AST', 'ALT', 'ALP', 'Bilirubin', 'Protein', 'Albumin'],
    "Kidney": ['BUN', 'Cr'],
    "ETC": ['Amylase', 'CRP']}


Z_groups = {
    "B" : ["Transitional B", "Memory B", "Early Plasma B ", "Plasma B", "ABC"],
    "T" : ['NKT2', 'MAIT', 'gd1T','gd2T', 'ConvT%'],
    "ConvT": ['CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg'],
    "PAN": ['B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T'],
    "CD8":  ['CD8+T', 'CD8trm', 'CD8grzk'],
    "CD4":  ['CD4+T',  'CD4trm', 'CD4grzk'],
    "MAIT": ['MAIT', 'MAITtrm', 'MAITgrzK'],
    "CD20T":["CD20T"],
    "GD1T": ['gd1T','GD1Ttrm', 'GD1TgrzK'],
    "GD2T": ['gd2T','GD2Ttrm', 'GD2TgrzK'],
    "PCA" : ['CD8_PC1','CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1'],
    "CD11c": ['CD11c+CD206-', 'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-',
              'Dectin-1+1','Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4'],
    "Detectin":[ 'Dectin-1+1','Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4'],
    "CD11c_1" :['CD11c+CD206-', 'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-']
}

# -----------------------------
# 2) covariates 지정
# -----------------------------
COVARS = ["BMI"]   # <- 요청한 컬럼명

# -----------------------------
# 3) 실행 (BMI, Sex_01 통제한 sCCA)
# -----------------------------
rows = []
for x_name, X_cols in X_groups.items():
    for z_name, Z_cols in Z_groups.items():

        use_cols = X_cols + Z_cols + COVARS

        # 결측치 있는 행 제거 (covariate까지 포함해서 complete-case)
        df_clean = df1.dropna(subset=use_cols).copy()
        n = df_clean.shape[0]

        if n < 6:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": "SKIP(n too small)"
            })
            continue

        # 원본 행렬
        X_raw = df_clean[X_cols]
        Z_raw = df_clean[Z_cols]
        cov = df_clean[COVARS].astype(float)

        # ✅ 통제: residualize
        X = residualize_df(X_raw, cov)
        Z = residualize_df(Z_raw, cov)

        try:
            results = apply_sparse_cca(
                X, Z,
                X_cols=X_cols, Z_cols=Z_cols,
                verbose=False,
                visualize=False
            )

            r = results.get("correlations", None)
            p = results.get("permutation_pvalue", None)
            r1 = float(r[0]) if isinstance(r, (list, tuple, np.ndarray)) else float(r)

            rows.append({
                "X_group": x_name,
                "Z_group": z_name,
                "n": n,
                "r1": r1,
                "p_perm": p,
                "status": "OK",
                "covars": "BMI+Sex_01"
            })

        except Exception as e:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": f"FAIL: {type(e).__name__}",
                "covars": "BMI+Sex_01"
            })

res_df_adj = pd.DataFrame(rows)

# 보기 좋게 정렬 (OK만 위로 + p_perm 오름차순)
res_df_sorted1_adj = (
    res_df_adj
    .assign(status_rank=lambda d: (d["status"] != "OK").astype(int))
    .sort_values(["status_rank", "p_perm"], ascending=[True, True])
    .drop(columns=["status_rank"])
)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

res_df_sorted1_adj

      X_group   Z_group   n        r1    p_perm status      covars
16      Liver     ConvT  12  0.900481  0.001998     OK  BMI+Sex_01
28     Kidney         B  22  0.606126  0.019980     OK  BMI+Sex_01
54        ETC  Detectin  18  0.624277  0.022977     OK  BMI+Sex_01
45        ETC       PAN  18  0.755322  0.039960     OK  BMI+Sex_01
50        ETC      GD1T  11  0.778242  0.044955     OK  BMI+Sex_01
31     Kidney       PAN  22  0.610306  0.045954     OK  BMI+Sex_01
14      Liver         B  21  0.671605  0.097902     OK  BMI+Sex_01
53        ETC     CD11c  18  0.627933  0.098901     OK  BMI+Sex_01
55        ETC   CD11c_1  18  0.565778  0.102897     OK  BMI+Sex_01
22      Liver      GD1T  12  0.789781  0.107892     OK  BMI+Sex_01
46        ETC       CD8  11  0.753006  0.108891     OK  BMI+Sex_01
40     Kidney  Detectin  22  0.482626  0.145854     OK  BMI+Sex_01
52        ETC       PCA  11  0.694192  0.161838     OK  BMI+Sex_01
23      Liver      GD2T  12  0.764108  0.190809     OK  BMI+Sex_01
39     Kidney     CD11c  22  0.569868  0.192807     OK  BMI+Sex_01
9   Metabolic      GD2T  11  0.653597  0.209790     OK  BMI+Sex_01
1   Metabolic         T  11  0.697265  0.223776     OK  BMI+Sex_01
7   Metabolic     CD20T  20  0.394620  0.227772     OK  BMI+Sex_01
36     Kidney      GD1T  13  0.612886  0.235764     OK  BMI+Sex_01
47        ETC       CD4  11  0.587261  0.257742     OK  BMI+Sex_01
42        ETC         B  18  0.540531  0.262737     OK  BMI+Sex_01
5   Metabolic       CD4  11  0.605824  0.265734     OK  BMI+Sex_01
29     Kidney         T  13  0.608966  0.269730     OK  BMI+Sex_01
32     Kidney       CD8  13  0.553908  0.337662     OK  BMI+Sex_01
26      Liver  Detectin  21  0.607484  0.340659     OK  BMI+Sex_01
20      Liver      MAIT  12  0.669888  0.346653     OK  BMI+Sex_01
10  Metabolic       PCA  11  0.671364  0.347652     OK  BMI+Sex_01
2   Metabolic     ConvT  11  0.591438  0.356643     OK  BMI+Sex_01
41     Kidney   CD11c_1  22  0.426591  0.361638     OK  BMI+Sex_01
15      Liver         T  12  0.727515  0.418581     OK  BMI+Sex_01
49        ETC     CD20T  18  0.307790  0.433566     OK  BMI+Sex_01
38     Kidney       PCA  13  0.582600  0.476523     OK  BMI+Sex_01
18      Liver       CD8  12  0.660332  0.508492     OK  BMI+Sex_01
13  Metabolic   CD11c_1  20  0.398310  0.514486     OK  BMI+Sex_01
12  Metabolic  Detectin  20  0.384664  0.550450     OK  BMI+Sex_01
24      Liver       PCA  12  0.769198  0.576424     OK  BMI+Sex_01
0   Metabolic         B  20  0.346322  0.582418     OK  BMI+Sex_01
8   Metabolic      GD1T  11  0.584534  0.582418     OK  BMI+Sex_01
30     Kidney     ConvT  13  0.455549  0.587413     OK  BMI+Sex_01
27      Liver   CD11c_1  21  0.517886  0.608392     OK  BMI+Sex_01
33     Kidney       CD4  13  0.426222  0.626374     OK  BMI+Sex_01
35     Kidney     CD20T  22  0.192970  0.632368     OK  BMI+Sex_01
37     Kidney      GD2T  13  0.374398  0.674326     OK  BMI+Sex_01
51        ETC      GD2T  11  0.398231  0.700300     OK  BMI+Sex_01
21      Liver     CD20T  21  0.268043  0.748252     OK  BMI+Sex_01
11  Metabolic     CD11c  20  0.377527  0.754246     OK  BMI+Sex_01
48        ETC      MAIT  11  0.398226  0.788212     OK  BMI+Sex_01
25      Liver     CD11c  21  0.544549  0.802198     OK  BMI+Sex_01
43        ETC         T  11  0.463964  0.806194     OK  BMI+Sex_01
6   Metabolic      MAIT  11  0.401049  0.807193     OK  BMI+Sex_01
34     Kidney      MAIT  13  0.389761  0.819181     OK  BMI+Sex_01
4   Metabolic       CD8  11  0.389559  0.846154     OK  BMI+Sex_01
17      Liver       PAN  21  0.447980  0.856144     OK  BMI+Sex_01
3   Metabolic       PAN  20  0.319501  0.899101     OK  BMI+Sex_01
44        ETC     ConvT  11  0.281533  0.938062     OK  BMI+Sex_01
19      Liver       CD4  12  0.328419  1.000000     OK  BMI+Sex_01

In [21]:
import statsmodels.api as sm
# df2통제후
# -----------------------------
# 0) residualize helper
# -----------------------------
def residualize_df(mat_df: pd.DataFrame, cov_df: pd.DataFrame) -> pd.DataFrame:
    """
    mat_df: (n x p) matrix dataframe (X or Z)
    cov_df: (n x k) covariates dataframe (BMI, Sex_01 etc.)
    return: residualized mat_df (same shape/cols)
    """
    Xc = sm.add_constant(cov_df.astype(float), has_constant="add")
    resid = {}
    for col in mat_df.columns:
        y = mat_df[col].astype(float).values
        fit = sm.OLS(y, Xc).fit()
        resid[col] = fit.resid
    return pd.DataFrame(resid, index=mat_df.index)

# -----------------------------
# 1) 그룹 정의 (원본 그대로)
# -----------------------------

X_groups = {
    "Liver":   ['AST', 'ALT', 'ALP', 'Bilirubin', 'Albumin', 'PT', 'APTT'],
    "Liver1" : ['AST', 'ALT', 'ALP', 'PT', 'APTT', 'Bilirubin'] , 
    "Liver2":["Albumin"],
    "Metabolic": ['TG', 'LDL',  'F_Glucose', 'HbA1c', 'Cholesterol','HDL'],
    "HDL": ['HDL'],
    "Metaboilic1":['TG', 'LDL',  'F_Glucose', 'HbA1c', 'Cholesterol'],
    "Kidney": ['BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl'],
    "Kidney1": ['BUN', 'Cr'],
    "Kidney2": ['GFR(CKD_EPI)', 'CrCl'],
}


Z_groups = {
    "B" : ["Transitional B", "Memory B", "Early Plasma B ", "Plasma B", "ABC"],
    "T" : ['NKT2', 'MAIT', 'gd1T','gd2T', 'ConvT%'],
    "ConvT": ['CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg'],
    "PAN": ['B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T'],
    "CD8":  ['CD8+T', 'CD8trm', 'CD8grzk'],
    "CD4":  ['CD4+T',  'CD4trm', 'CD4grzk'],
    "MAIT": ['MAIT', 'MAITtrm', 'MAITgrzK'],
    "CD20T":["CD20T"],
    "GD1T": ['gd1T','GD1Ttrm', 'GD1TgrzK'],
    "GD2T": ['gd2T','GD2Ttrm', 'GD2TgrzK'],
    "PCA" : ['CD8_PC1','CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1'],
    "CD11c": ['CD11c+CD206-', 'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-',
              'Dectin-1+1','Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4'],
    "Detectin":[ 'Dectin-1+1','Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4'],
    "CD11c_1" :['CD11c+CD206-', 'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-']
}

# -----------------------------
# 2) covariates 지정
# -----------------------------
COVARS = ["BMI", 'Sex_01']   # <- 요청한 컬럼명

# -----------------------------
# 3) 실행 (BMI, Sex_01 통제한 sCCA)
# -----------------------------
rows = []
for x_name, X_cols in X_groups.items():
    for z_name, Z_cols in Z_groups.items():

        use_cols = X_cols + Z_cols + COVARS

        # 결측치 있는 행 제거 (covariate까지 포함해서 complete-case)
        df_clean = df2.dropna(subset=use_cols).copy()
        n = df_clean.shape[0]

        if n < 6:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": "SKIP(n too small)"
            })
            continue

        # 원본 행렬
        X_raw = df_clean[X_cols]
        Z_raw = df_clean[Z_cols]
        cov = df_clean[COVARS].astype(float)

        # ✅ 통제: residualize
        X = residualize_df(X_raw, cov)
        Z = residualize_df(Z_raw, cov)

        try:
            results = apply_sparse_cca(
                X, Z,
                X_cols=X_cols, Z_cols=Z_cols,
                verbose=False,
                visualize=False
            )

            r = results.get("correlations", None)
            p = results.get("permutation_pvalue", None)
            r1 = float(r[0]) if isinstance(r, (list, tuple, np.ndarray)) else float(r)

            rows.append({
                "X_group": x_name,
                "Z_group": z_name,
                "n": n,
                "r1": r1,
                "p_perm": p,
                "status": "OK",
                "covars": "BMI+Sex_01"
            })

        except Exception as e:
            rows.append({
                "X_group": x_name, "Z_group": z_name,
                "n": n, "r1": np.nan, "p_perm": np.nan,
                "status": f"FAIL: {type(e).__name__}",
                "covars": "BMI+Sex_01"
            })

res_df_adj = pd.DataFrame(rows)

# 보기 좋게 정렬 (OK만 위로 + p_perm 오름차순)
res_df_sorted1_adj = (
    res_df_adj
    .assign(status_rank=lambda d: (d["status"] != "OK").astype(int))
    .sort_values(["status_rank", "p_perm"], ascending=[True, True])
    .drop(columns=["status_rank"])
)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

res_df_sorted1_adj

         X_group   Z_group   n        r1    p_perm status      covars
37        Liver2      GD2T  22  0.739573  0.000999     OK  BMI+Sex_01
26        Liver1  Detectin  22  0.698093  0.002997     OK  BMI+Sex_01
9          Liver      GD2T  22  0.772969  0.003996     OK  BMI+Sex_01
59           HDL       PAN  22  0.716883  0.004995     OK  BMI+Sex_01
16        Liver1     ConvT  22  0.752618  0.007992     OK  BMI+Sex_01
2          Liver     ConvT  22  0.760004  0.013986     OK  BMI+Sex_01
53     Metabolic     CD11c  22  0.699935  0.020979     OK  BMI+Sex_01
12         Liver  Detectin  22  0.672616  0.028971     OK  BMI+Sex_01
118      Kidney2      MAIT  22  0.528346  0.049950     OK  BMI+Sex_01
15        Liver1         T  22  0.566483  0.053946     OK  BMI+Sex_01
76   Metaboilic1      MAIT  22  0.630563  0.059940     OK  BMI+Sex_01
19        Liver1       CD4  22  0.667071  0.072927     OK  BMI+Sex_01
92        Kidney      GD1T  16  0.694244  0.072927     OK  BMI+Sex_01
122      Kidney2       PCA  16  0.698037  0.077922     OK  BMI+Sex_01
24        Liver1       PCA  16  0.739490  0.078921     OK  BMI+Sex_01
48     Metabolic      MAIT  22  0.627172  0.078921     OK  BMI+Sex_01
5          Liver       CD4  22  0.656453  0.086913     OK  BMI+Sex_01
23        Liver1      GD2T  22  0.602070  0.096903     OK  BMI+Sex_01
38        Liver2       PCA  16  0.570637  0.102897     OK  BMI+Sex_01
90        Kidney      MAIT  22  0.528346  0.102897     OK  BMI+Sex_01
10         Liver       PCA  16  0.733243  0.103896     OK  BMI+Sex_01
83   Metaboilic1   CD11c_1  22  0.558596  0.119880     OK  BMI+Sex_01
51     Metabolic      GD2T  22  0.617166  0.127872     OK  BMI+Sex_01
79   Metaboilic1      GD2T  22  0.606364  0.128871     OK  BMI+Sex_01
54     Metabolic  Detectin  22  0.560091  0.133866     OK  BMI+Sex_01
106      Kidney1      GD1T  16  0.588088  0.134865     OK  BMI+Sex_01
55     Metabolic   CD11c_1  22  0.556921  0.141858     OK  BMI+Sex_01
110      Kidney1  Detectin  22  0.473063  0.143856     OK  BMI+Sex_01
68           HDL  Detectin  22  0.387840  0.148851     OK  BMI+Sex_01
67           HDL     CD11c  22  0.497942  0.165834     OK  BMI+Sex_01
20        Liver1      MAIT  22  0.542383  0.170829     OK  BMI+Sex_01
64           HDL      GD1T  16  0.515573  0.178821     OK  BMI+Sex_01
81   Metaboilic1     CD11c  22  0.656452  0.179820     OK  BMI+Sex_01
98       Kidney1         B  22  0.505083  0.182817     OK  BMI+Sex_01
62           HDL      MAIT  22  0.421820  0.186813     OK  BMI+Sex_01
119      Kidney2     CD20T  22  0.385063  0.189810     OK  BMI+Sex_01
6          Liver      MAIT  22  0.542383  0.190809     OK  BMI+Sex_01
85        Kidney         T  22  0.583348  0.197802     OK  BMI+Sex_01
65           HDL      GD2T  22  0.415420  0.215784     OK  BMI+Sex_01
96        Kidney  Detectin  22  0.461880  0.222777     OK  BMI+Sex_01
63           HDL     CD20T  22  0.259293  0.225774     OK  BMI+Sex_01
25        Liver1     CD11c  22  0.698225  0.228771     OK  BMI+Sex_01
71   Metaboilic1         T  22  0.548654  0.231768     OK  BMI+Sex_01
8          Liver      GD1T  16  0.506696  0.233766     OK  BMI+Sex_01
94        Kidney       PCA  16  0.636776  0.242757     OK  BMI+Sex_01
29        Liver2         T  22  0.392851  0.244755     OK  BMI+Sex_01
109      Kidney1     CD11c  22  0.473063  0.249750     OK  BMI+Sex_01
82   Metaboilic1  Detectin  22  0.444600  0.272727     OK  BMI+Sex_01
43     Metabolic         T  22  0.539090  0.294705     OK  BMI+Sex_01
46     Metabolic       CD8  22  0.470278  0.304695     OK  BMI+Sex_01
28        Liver2         B  22  0.385260  0.307692     OK  BMI+Sex_01
77   Metaboilic1     CD20T  22  0.426373  0.316683     OK  BMI+Sex_01
35        Liver2     CD20T  22  0.221860  0.326673     OK  BMI+Sex_01
1          Liver         T  22  0.511989  0.328671     OK  BMI+Sex_01
49     Metabolic     CD20T  22  0.385117  0.334665     OK  BMI+Sex_01
115      Kidney2       PAN  22  0.477044  0.335664     OK  BMI+Sex_01
52     Metabolic       PCA  16  0.620389  0.338661     OK  BMI+Sex_01
74   Metaboilic1       CD8  22  0.471293  0.342657     OK  BMI+Sex_01
125      Kidney2   CD11c_1  22  0.383876  0.360639     OK  BMI+Sex_01
99       Kidney1         T  22  0.428669  0.379620     OK  BMI+Sex_01
44     Metabolic     ConvT  22  0.494347  0.385614     OK  BMI+Sex_01
3          Liver       PAN  22  0.587885  0.389610     OK  BMI+Sex_01
91        Kidney     CD20T  22  0.403445  0.402597     OK  BMI+Sex_01
22        Liver1      GD1T  16  0.504877  0.413586     OK  BMI+Sex_01
56           HDL         B  22  0.365476  0.418581     OK  BMI+Sex_01
45     Metabolic       PAN  22  0.577397  0.423576     OK  BMI+Sex_01
72   Metaboilic1     ConvT  22  0.442912  0.433566     OK  BMI+Sex_01
40        Liver2  Detectin  22  0.279901  0.437562     OK  BMI+Sex_01
84        Kidney         B  22  0.503804  0.437562     OK  BMI+Sex_01
95        Kidney     CD11c  22  0.473063  0.439560     OK  BMI+Sex_01
78   Metaboilic1      GD1T  16  0.526372  0.443556     OK  BMI+Sex_01
18        Liver1       CD8  22  0.509779  0.453546     OK  BMI+Sex_01
113      Kidney2         T  22  0.400709  0.464535     OK  BMI+Sex_01
14        Liver1         B  22  0.479842  0.469530     OK  BMI+Sex_01
124      Kidney2  Detectin  22  0.314156  0.469530     OK  BMI+Sex_01
17        Liver1       PAN  22  0.517819  0.475524     OK  BMI+Sex_01
120      Kidney2      GD1T  16  0.433032  0.477522     OK  BMI+Sex_01
73   Metaboilic1       PAN  22  0.357582  0.492507     OK  BMI+Sex_01
11         Liver     CD11c  22  0.682847  0.495504     OK  BMI+Sex_01
105      Kidney1     CD20T  22  0.266788  0.496503     OK  BMI+Sex_01
4          Liver       CD8  22  0.520120  0.517483     OK  BMI+Sex_01
69           HDL   CD11c_1  22  0.265560  0.555445     OK  BMI+Sex_01
117      Kidney2       CD4  22  0.366629  0.557443     OK  BMI+Sex_01
97        Kidney   CD11c_1  22  0.383876  0.559441     OK  BMI+Sex_01
87        Kidney       PAN  22  0.498369  0.563437     OK  BMI+Sex_01
50     Metabolic      GD1T  16  0.525760  0.577423     OK  BMI+Sex_01
60           HDL       CD8  22  0.226783  0.594406     OK  BMI+Sex_01
75   Metaboilic1       CD4  22  0.422089  0.594406     OK  BMI+Sex_01
103      Kidney1       CD4  22  0.342932  0.610390     OK  BMI+Sex_01
102      Kidney1       CD8  22  0.304185  0.637363     OK  BMI+Sex_01
47     Metabolic       CD4  22  0.422089  0.641359     OK  BMI+Sex_01
116      Kidney2       CD8  22  0.317153  0.658342     OK  BMI+Sex_01
112      Kidney2         B  22  0.320449  0.662338     OK  BMI+Sex_01
108      Kidney1       PCA  16  0.397747  0.670330     OK  BMI+Sex_01
36        Liver2      GD1T  16  0.283346  0.671329     OK  BMI+Sex_01
123      Kidney2     CD11c  22  0.380147  0.675325     OK  BMI+Sex_01
58           HDL     ConvT  22  0.227543  0.689311     OK  BMI+Sex_01
21        Liver1     CD20T  22  0.279431  0.693307     OK  BMI+Sex_01
32        Liver2       CD8  22  0.187185  0.704296     OK  BMI+Sex_01
101      Kidney1       PAN  22  0.366932  0.711289     OK  BMI+Sex_01
88        Kidney       CD8  22  0.393106  0.728272     OK  BMI+Sex_01
89        Kidney       CD4  22  0.454254  0.740260     OK  BMI+Sex_01
7          Liver     CD20T  22  0.279431  0.743257     OK  BMI+Sex_01
80   Metaboilic1       PCA  16  0.514547  0.746254     OK  BMI+Sex_01
66           HDL       PCA  16  0.288245  0.754246     OK  BMI+Sex_01
61           HDL       CD4  22  0.195288  0.756244     OK  BMI+Sex_01
100      Kidney1     ConvT  22  0.284697  0.757243     OK  BMI+Sex_01
0          Liver         B  22  0.460754  0.778222     OK  BMI+Sex_01
111      Kidney1   CD11c_1  22  0.278984  0.798202     OK  BMI+Sex_01
39        Liver2     CD11c  22  0.284355  0.816184     OK  BMI+Sex_01
121      Kidney2      GD2T  22  0.238254  0.836164     OK  BMI+Sex_01
31        Liver2       PAN  22  0.305276  0.845155     OK  BMI+Sex_01
114      Kidney2     ConvT  22  0.246032  0.860140     OK  BMI+Sex_01
86        Kidney     ConvT  22  0.288555  0.877123     OK  BMI+Sex_01
41        Liver2   CD11c_1  22  0.147706  0.891109     OK  BMI+Sex_01
93        Kidney      GD2T  22  0.279021  0.915085     OK  BMI+Sex_01
104      Kidney1      MAIT  22  0.181285  0.918082     OK  BMI+Sex_01
107      Kidney1      GD2T  22  0.226197  0.918082     OK  BMI+Sex_01
30        Liver2     ConvT  22  0.113601  0.926074     OK  BMI+Sex_01
70   Metaboilic1         B  22  0.286921  0.932068     OK  BMI+Sex_01
34        Liver2      MAIT  22  0.125151  0.942058     OK  BMI+Sex_01
33        Liver2       CD4  22  0.096381  0.962038     OK  BMI+Sex_01
42     Metabolic         B  22  0.286921  0.964036     OK  BMI+Sex_01
27        Liver1   CD11c_1  22  0.254095  0.974026     OK  BMI+Sex_01
13         Liver   CD11c_1  22  0.254095  0.983017     OK  BMI+Sex_01
57           HDL         T  22  0.108820  0.988012     OK  BMI+Sex_01

### Task2 - Tsubset에 대해 plsr 돌리기 , 1:다

In [ ]:
df.columns

Index(['ID', 'Sex', 'Age', 'BMI', 'AST', 'ALT', 'ALP', 'Bilirubin', 'Protein',
       'Albumin', 'PT', 'APTT', 'Cholesterol', 'TG', 'LDL', 'HDL', 'R_Glucose',
       'F_Glucose', 'HbA1c', 'BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl', 'Amylase',
       'CRP', 'B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T', 'NKT2', 'MAIT', 'gd1T',
       'gd2T', 'ConvT%', 'CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg', 'CD20T',
       'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm', 'CD4grzk',
       'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK', 'Transitional B',
       'Memory B', 'Early Plasma B ', 'Plasma B', 'ABC', 'CD11c+CD206-',
       'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1',
       'Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4', 'Gulucose', 'Sex_01',
       'CD8_PC1', 'CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1', 'MAIT2_PC1',
       'MAIT_1_PC1', 'GD2T_1_PC1'],
      dtype='object')

#### 간 & df1 plsr

In [ ]:
sep = "_" * 90

X_cols = ['AST', 'ALT', 'ALP', 'Bilirubin', 'Protein', 'Albumin']

y_candidates = [
    'CD8_PC1', 'CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1', 'MAIT_1_PC1',
    'GD2T_1_PC1', 'CD8_1_PC1', 'CD8_2_PC1', 'CD8_3_PC1', 'CD4_1_PC1',
    'CD4_2_PC1', 'CD4_3_PC1', 'MAIT_2_PC1', 'MAIT_3_PC1', 'GD1T_1_PC1',
    'GD1T_2_PC1', 'GD1T_3_PC1', 'GD2T_2_PC1', 'GD2T_3_PC1',
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환"""
    n = len(y)
    n_splits = min(n_splits, n)  # 안전
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def perm_pvalue_plsr_cv(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5,
                        n_perm=1000, random_state=42, statistic="abs_r"):
    """
    permutation p-value (CV 포함) 계산
    statistic:
      - "abs_r" : |corr(y, yhat_cv)|
      - "r2"    : corr(y, yhat_cv)^2
    """
    y = y.astype(float).to_numpy()
    y_pred = cv_pred_plsr(X, y, n_components=n_components, n_splits=n_splits, random_state=random_state)
    if y_pred is None:
        return np.nan, np.nan

    # 관측 통계량
    if np.std(y) < 1e-12 or np.std(y_pred) < 1e-12:
        r_obs = np.nan
        stat_obs = np.nan
    else:
        r_obs, _ = pearsonr(y, y_pred)
        stat_obs = abs(r_obs) if statistic == "abs_r" else (r_obs ** 2)

    if not np.isfinite(stat_obs):
        return r_obs, np.nan

    rng = np.random.default_rng(random_state)
    ge = 0

    # permutation: y를 셔플해서 CV를 다시 수행
    for _ in range(n_perm):
        y_perm = rng.permutation(y)
        y_perm_pred = cv_pred_plsr(X, y_perm, n_components=n_components, n_splits=n_splits, random_state=random_state)
        if y_perm_pred is None or np.std(y_perm_pred) < 1e-12:
            stat_perm = 0.0
        else:
            r_perm, _ = pearsonr(y_perm, y_perm_pred)
            stat_perm = abs(r_perm) if statistic == "abs_r" else (r_perm ** 2)

        if stat_perm >= stat_obs:
            ge += 1

    p_perm = (ge + 1) / (n_perm + 1)
    return r_obs, p_perm


def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등할 수 있어서, fold weight는 full-fit weight에 맞춰 부호 정렬합니다.
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    # x_weights_: (p, n_components), coef_: (p, 1)
    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    # 기준 방향(컴포넌트1만 정렬 기준으로 씀)
    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)  # (n_splits, p)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col]

    try:
        r_obs, p_perm = perm_pvalue_plsr_cv(
            X, y,
            n_components=1,
            n_splits=5,
            n_perm=1000,
            random_state=42,
            statistic="abs_r"  
        )

        print(f"obs_r = {r_obs:.4f}" if np.isfinite(r_obs) else "obs_r = NaN")
        print(f"perm_p = {p_perm:.4f}" if np.isfinite(p_perm) else "perm_p = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, y,
            n_components=1,
            n_splits=5,
            random_state=42
        )

        # 보기 좋게 합치기
        w_tbl = full_tbl.join(cv_tbl, how="left")

        # coef 절대값 기준 정렬 (기여 큰 순)
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_obs": r_obs, "p_perm": p_perm, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": f"FAIL: {type(e).__name__}"})

# 마지막 요약: permutation p-value 기준 정렬
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("p_perm", ascending=True, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by permutation p-value)")
print(sep)
print(res_ok[["y_col", "n", "r_obs", "p_perm"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/30] TSubset = CD8_PC1
n = 12
obs_r = -0.5334
perm_p = 0.1548
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6412 -0.5286     0.5494    0.1414
Protein         0.4752 -0.2945     0.3231    0.4123
ALT            -0.5644  0.0218    -0.5107    0.1564
Bilirubin      -0.0157  0.0200     0.0299    0.2401
ALP            -0.2037  0.0031    -0.1975    0.2612
AST             0.0521 -0.0022     0.0495    0.1514
------------------------------------------------------------
__________________________________________________________________________________________
[2/30] TSubset = CD4_PC1
n = 12
obs_r = -0.7388
perm_p = 0.0300
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.5539 -0.2892     0.4255    0.2121
Bilirubin       0.2945 -0.2383     0.0456    0.4312
Protein         0.5603 -0.2199     0.4987    0.1258
AST             0.5032 -0.0136     0.1799    0.4710
ALT            -0.0941  0.0023    -0.1397    0.2006
ALP             0.1745 -0.0017     0.1739    0.3141
------------------------------------------------------------
__________________________________________________________________________________________
[3/30] TSubset = MAIT_PC1
n = 12
obs_r = 0.0473
perm_p = 0.9121
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.2837 -0.4903     0.3066    0.2988
Protein         0.5063 -0.4244     0.4454    0.1195
Albumin         0.2506 -0.2794     0.1950    0.2145
ALT             0.5427 -0.0283     0.4907    0.1200
AST             0.4320 -0.0250     0.3929    0.1785
ALP             0.3454 -0.0072     0.2663    0.2419
------------------------------------------------------------
__________________________________________________________________________________________
[4/30] TSubset = GD1T_PC1
n = 12
obs_r = 0.4005
perm_p = 0.3566
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.5793 -0.5859     0.5209    0.1128
Protein         0.6140 -0.4667     0.5691    0.0577
Bilirubin       0.0972 -0.1523     0.1029    0.2895
AST             0.5216 -0.0273     0.5129    0.1111
ALT            -0.0738  0.0035    -0.0289    0.1636
ALP            -0.0205  0.0004    -0.0305    0.1506
------------------------------------------------------------
__________________________________________________________________________________________
[5/30] TSubset = GD2T_PC1
n = 12
obs_r = -0.0850
perm_p = 0.8422
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.3020 -0.6319    -0.3012    0.2223
Albumin         0.4620  0.6238     0.3794    0.2065
Protein         0.5697  0.5782     0.4755    0.1994
ALT            -0.2784 -0.0176    -0.2962    0.1775
ALP             0.5412  0.0136     0.5055    0.1524
AST            -0.0207 -0.0014    -0.0255    0.2401
------------------------------------------------------------
__________________________________________________________________________________________
[6/30] TSubset = MAIT_1_PC1
n = 12
obs_r = -0.8470
perm_p = 0.0030
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6533  0.2659     0.4946    0.2250
Protein         0.6918  0.2117     0.6519    0.0585
Bilirubin       0.0207  0.0131    -0.0164    0.1655
ALT            -0.2355 -0.0045    -0.0585    0.3227
AST             0.1256  0.0026     0.1834    0.1274
ALP             0.1512  0.0011     0.2591    0.2841
------------------------------------------------------------
__________________________________________________________________________________________
[7/30] TSubset = GD2T_1_PC1
n = 12
obs_r = -0.3416
perm_p = 0.4565
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6297 -0.5425     0.5024    0.1919
Albumin         0.4611 -0.5285     0.3314    0.2852
Bilirubin      -0.1944  0.3453    -0.2087    0.2350
ALT            -0.2313  0.0124    -0.2720    0.2279
ALP             0.5392 -0.0115     0.5006    0.1859
AST             0.0941 -0.0056     0.0723    0.2659
------------------------------------------------------------
__________________________________________________________________________________________
[8/30] TSubset = CD8_1_PC1
n = 12
obs_r = -0.7417
perm_p = 0.0190
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6612 -0.5082     0.5254    0.1906
Protein         0.5590 -0.3229     0.3388    0.4837
Bilirubin       0.0883 -0.1052     0.1203    0.2626
ALT            -0.4476  0.0161    -0.4030    0.1694
AST             0.1695 -0.0067     0.1541    0.1729
ALP            -0.1164  0.0017    -0.1372    0.2987
------------------------------------------------------------
__________________________________________________________________________________________
[9/30] TSubset = CD8_2_PC1
n = 12
obs_r = 0.3216
perm_p = 0.4436
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.2943  0.5016     0.2711    0.1007
Albumin        -0.2963 -0.3258    -0.3241    0.0702
ALT             0.7380  0.0380     0.7140    0.0398
Protein         0.0294  0.0243     0.0201    0.1700
AST             0.3911  0.0223     0.3958    0.0844
ALP             0.3565  0.0073     0.2898    0.1890
------------------------------------------------------------
__________________________________________________________________________________________
[10/30] TSubset = CD8_3_PC1
n = 12
obs_r = 0.0902
perm_p = 0.8521
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.5116 -0.5219    -0.4917    0.0954
Bilirubin       0.2479  0.3919     0.1985    0.1540
Protein        -0.2714 -0.2081    -0.2400    0.2590
ALT             0.6678  0.0319     0.6169    0.0883
AST             0.1421  0.0075     0.1567    0.2500
ALP             0.3701  0.0070     0.3188    0.1517
------------------------------------------------------------
__________________________________________________________________________________________
[11/30] TSubset = CD4_1_PC1
n = 12
obs_r = -0.6603
perm_p = 0.0629
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6594 -0.3203     0.5178    0.1146
Protein         0.5061 -0.1848     0.2922    0.3940
Bilirubin       0.0367 -0.0276     0.0568    0.3421
ALT            -0.4901  0.0111    -0.4122    0.2992
AST             0.2467 -0.0062     0.2183    0.1832
ALP            -0.0819  0.0007    -0.0810    0.3398
------------------------------------------------------------
__________________________________________________________________________________________
[12/30] TSubset = CD4_2_PC1
n = 12
obs_r = -0.7494
perm_p = 0.0230
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.4637 -0.3649     0.3014    0.3127
Albumin         0.5121 -0.2600     0.3323    0.3852
Protein         0.5270 -0.2011     0.2812    0.4086
AST             0.3894 -0.0102     0.2904    0.2097
ALP             0.2966 -0.0028     0.2855    0.3496
ALT            -0.0735  0.0017    -0.0318    0.3341
------------------------------------------------------------
__________________________________________________________________________________________
[13/30] TSubset = CD4_3_PC1
n = 12
obs_r = -0.4767
perm_p = 0.2258
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.2430 -0.2311     0.1671    0.2876
Protein         0.4083 -0.1883     0.2651    0.3545
Albumin         0.2289 -0.1404     0.1441    0.3696
AST             0.7183 -0.0228     0.6006    0.1261
ALT             0.3867 -0.0111     0.3191    0.1607
ALP             0.2374 -0.0027     0.2083    0.2867
------------------------------------------------------------
__________________________________________________________________________________________
[14/30] TSubset = MAIT_2_PC1
n = 12
obs_r = 0.1351
perm_p = 0.7802
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.4306 -0.8663     0.4073    0.2434
Protein         0.2504 -0.2443     0.2632    0.1220
ALT             0.7154 -0.0435     0.6568    0.1299
AST             0.4038 -0.0272     0.3781    0.1696
Albumin        -0.0204  0.0264     0.0011    0.1667
ALP             0.2768 -0.0067     0.2188    0.1756
------------------------------------------------------------
__________________________________________________________________________________________
[15/30] TSubset = MAIT_3_PC1
n = 12
obs_r = -0.3719
perm_p = 0.2018
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6468 -0.6247     0.6033    0.0404
Albumin         0.4742 -0.6092     0.4674    0.0471
Bilirubin      -0.1073  0.2137    -0.1288    0.0719
AST             0.3830 -0.0255     0.3117    0.2171
ALT             0.2246 -0.0135     0.0533    0.3762
ALP             0.3849 -0.0092     0.3499    0.1594
------------------------------------------------------------
__________________________________________________________________________________________
[16/30] TSubset = GD1T_1_PC1
n = 12
obs_r = 0.4220
perm_p = 0.3397
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6195 -0.6537     0.5737    0.0762
Protein         0.6274 -0.4977     0.5940    0.0324
Bilirubin       0.0592 -0.0968     0.0722    0.2855
AST             0.4447 -0.0243     0.4370    0.0980
ALT            -0.1461  0.0072    -0.1034    0.1304
ALP            -0.0067  0.0001    -0.0168    0.1536
------------------------------------------------------------
__________________________________________________________________________________________
[17/30] TSubset = GD1T_2_PC1
n = 12
obs_r = -0.1247
perm_p = 0.7872
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.4031 -0.5535     0.3021    0.2935
Protein         0.1964 -0.1308     0.1821    0.1639
Albumin        -0.0927  0.0822    -0.0887    0.2139
AST             0.6538 -0.0300     0.6172    0.0699
ALT             0.5338 -0.0221     0.4957    0.1701
ALP             0.2793 -0.0046     0.2629    0.1499
------------------------------------------------------------
__________________________________________________________________________________________
[18/30] TSubset = GD1T_3_PC1
n = 12
obs_r = -0.0633
perm_p = 0.8891
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.3407 -0.2653     0.2675    0.1996
Protein         0.3660 -0.2143     0.2782    0.2938
Bilirubin       0.0981 -0.1184     0.1224    0.2184
AST             0.7285 -0.0294     0.6910    0.0580
ALP            -0.4407  0.0064    -0.4134    0.1763
ALT             0.1239 -0.0045     0.1374    0.0532
------------------------------------------------------------
__________________________________________________________________________________________
[19/30] TSubset = GD2T_2_PC1
n = 12
obs_r = 0.1188
perm_p = 0.7652
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.3931 -0.7117    -0.3662    0.1881
Albumin         0.4017  0.4693     0.3637    0.1644
Protein         0.4584  0.4025     0.4041    0.2047
ALT            -0.2742 -0.0150    -0.2803    0.1337
ALP             0.6045  0.0132     0.5589    0.1401
AST            -0.1828 -0.0111    -0.1561    0.2279
------------------------------------------------------------
__________________________________________________________________________________________
[20/30] TSubset = GD2T_3_PC1
n = 12
obs_r = 0.3541
perm_p = 0.3566
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.4445 -0.8600    -0.4359    0.1540
Albumin         0.4735  0.5910     0.4357    0.1208
Protein         0.4754  0.4461     0.4287    0.1786
ALT            -0.3648 -0.0213    -0.3593    0.0953
ALP             0.4451  0.0104     0.4438    0.1130
AST            -0.1452 -0.0094    -0.1602    0.1177
------------------------------------------------------------
__________________________________________________________________________________________
[21/30] TSubset = CD4trm
n = 12
obs_r = -0.3849
perm_p = 0.3556
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6381 -4.8556     0.5512    0.0705
Protein         0.4336 -2.4800     0.2627    0.3682
Bilirubin       0.1556 -1.8352     0.1289    0.2905
ALT            -0.6164  0.2196    -0.5349    0.2344
AST            -0.0105  0.0041    -0.0063    0.1555
ALP            -0.0232  0.0033     0.0108    0.3182
------------------------------------------------------------
__________________________________________________________________________________________
[22/30] TSubset = CD8trm
n = 12
obs_r = -0.6169
perm_p = 0.1009
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.6215 -3.9907    -0.4336    0.2506
Protein        -0.3905 -1.8847    -0.1689    0.5352
Bilirubin      -0.1262 -1.2560    -0.0953    0.3144
ALT             0.6595  0.1983     0.4710    0.1983
AST             0.0585  0.0195     0.0302    0.2077
ALP             0.0835  0.0100     0.0072    0.3988
------------------------------------------------------------
__________________________________________________________________________________________
[23/30] TSubset = MAITtrm
n = 12
obs_r = -0.4407
perm_p = 0.3097
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.7467  10.8235     0.6009    0.2418
Albumin        -0.3994  -3.7354    -0.2773    0.3032
Protein        -0.3467  -2.4375    -0.1927    0.4212
ALT             0.3081   0.1349     0.2642    0.3081
AST            -0.0986  -0.0478    -0.0511    0.2142
ALP            -0.2410  -0.0420    -0.1980    0.2190
------------------------------------------------------------
__________________________________________________________________________________________
[24/30] TSubset = GD1Ttrm
n = 12
obs_r = -0.0088
perm_p = 0.9840
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6040 -6.1454     0.5535    0.0835
Albumin         0.4413 -5.9730     0.3807    0.1913
Bilirubin       0.2428 -5.0933     0.1671    0.3372
AST             0.4375 -0.3068     0.3738    0.1752
ALP             0.4306 -0.1087     0.3797    0.2012
ALT             0.0687 -0.0435     0.0602    0.2514
------------------------------------------------------------
__________________________________________________________________________________________
[25/30] TSubset = GD2Ttrm
n = 12
obs_r = -0.5446
perm_p = 0.1918
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6026 -8.7398     0.4446    0.2112
Albumin         0.3651 -7.0446     0.2234    0.3253
Bilirubin      -0.1015  3.0337    -0.1020    0.2697
ALP             0.6886 -0.2478     0.5976    0.2317
ALT            -0.1114  0.1007    -0.1616    0.2258
AST             0.0816 -0.0816     0.0633    0.3401
------------------------------------------------------------
__________________________________________________________________________________________
[26/30] TSubset = CD4grzk
n = 12
obs_r = -0.8173
perm_p = 0.0080
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.5275 -2.8586     0.3662    0.2001
Protein         0.5013 -2.0422     0.2837    0.3649
Bilirubin      -0.1768  1.4853    -0.0939    0.3209
AST             0.6254 -0.1756     0.5399    0.2241
ALT            -0.1480  0.0375    -0.1120    0.3378
ALP            -0.1618  0.0164    -0.1584    0.3447
------------------------------------------------------------
__________________________________________________________________________________________
[27/30] TSubset = CD8grzk
n = 12
obs_r = -0.5607
perm_p = 0.1648
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6515 -8.6534     0.5612    0.1434
Protein         0.6111 -6.1010     0.4464    0.3889
Bilirubin       0.0677 -1.3940     0.1117    0.1980
ALT            -0.3343  0.2079    -0.3174    0.1812
AST             0.2643 -0.1819     0.2451    0.1278
ALP            -0.1262  0.0313    -0.1624    0.3124
------------------------------------------------------------
__________________________________________________________________________________________
[28/30] TSubset = MAITgrzK
n = 12
obs_r = -0.7359
perm_p = 0.0400
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6122 -8.9069     0.5128    0.1875
Bilirubin      -0.3193  7.1988    -0.0830    0.4089
Protein         0.6143 -6.7183     0.6310    0.0549
ALT            -0.2939  0.2002    -0.1471    0.2460
AST             0.1274 -0.0961     0.1360    0.1426
ALP             0.2080 -0.0564     0.2214    0.1316
------------------------------------------------------------
__________________________________________________________________________________________
[29/30] TSubset = GD1TgrzK
n = 12
obs_r = 0.3711
perm_p = 0.3856
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.6362 -16.1261     0.6147    0.0352
Protein         0.5418 -10.3231     0.4910    0.1823
Bilirubin      -0.0702   2.7573    -0.0289    0.1686
AST             0.3780  -0.4964     0.3470    0.1521
ALT            -0.2628   0.3119    -0.2470    0.0718
ALP            -0.2912   0.1376    -0.2950    0.2203
------------------------------------------------------------
__________________________________________________________________________________________
[30/30] TSubset = GD2TgrzK
n = 12
obs_r = -0.1271
perm_p = 0.7812
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.5212 -10.2576     0.4167    0.2197
Protein         0.6257  -9.2577     0.5282    0.1830
Bilirubin      -0.2630   8.0232    -0.2929    0.2435
ALT            -0.3206   0.2954    -0.3439    0.1925
ALP             0.3934  -0.1444     0.3864    0.1729
AST             0.1005  -0.1025     0.0785    0.1637
------------------------------------------------------------

#### 신장

In [150]:
sep = "_" * 90

X_cols = ['BUN', 'Cr']
y_candidates = [
    'CD8_PC1', 'CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1', 'MAIT_1_PC1',
    'GD2T_1_PC1', 'CD8_1_PC1', 'CD8_2_PC1', 'CD8_3_PC1', 'CD4_1_PC1',
    'CD4_2_PC1', 'CD4_3_PC1', 'MAIT_2_PC1', 'MAIT_3_PC1', 'GD1T_1_PC1',
    'GD1T_2_PC1', 'GD1T_3_PC1', 'GD2T_2_PC1', 'GD2T_3_PC1',
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환"""
    n = len(y)
    n_splits = min(n_splits, n)  # 안전
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def perm_pvalue_plsr_cv(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5,
                        n_perm=1000, random_state=42, statistic="abs_r"):
    """
    permutation p-value (CV 포함) 계산
    statistic:
      - "abs_r" : |corr(y, yhat_cv)|
      - "r2"    : corr(y, yhat_cv)^2
    """
    y = y.astype(float).to_numpy()
    y_pred = cv_pred_plsr(X, y, n_components=n_components, n_splits=n_splits, random_state=random_state)
    if y_pred is None:
        return np.nan, np.nan

    # 관측 통계량
    if np.std(y) < 1e-12 or np.std(y_pred) < 1e-12:
        r_obs = np.nan
        stat_obs = np.nan
    else:
        r_obs, _ = pearsonr(y, y_pred)
        stat_obs = abs(r_obs) if statistic == "abs_r" else (r_obs ** 2)

    if not np.isfinite(stat_obs):
        return r_obs, np.nan

    rng = np.random.default_rng(random_state)
    ge = 0

    # permutation: y를 셔플해서 CV를 다시 수행
    for _ in range(n_perm):
        y_perm = rng.permutation(y)
        y_perm_pred = cv_pred_plsr(X, y_perm, n_components=n_components, n_splits=n_splits, random_state=random_state)
        if y_perm_pred is None or np.std(y_perm_pred) < 1e-12:
            stat_perm = 0.0
        else:
            r_perm, _ = pearsonr(y_perm, y_perm_pred)
            stat_perm = abs(r_perm) if statistic == "abs_r" else (r_perm ** 2)

        if stat_perm >= stat_obs:
            ge += 1

    p_perm = (ge + 1) / (n_perm + 1)
    return r_obs, p_perm


def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등할 수 있어서, fold weight는 full-fit weight에 맞춰 부호 정렬합니다.
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    # x_weights_: (p, n_components), coef_: (p, 1)
    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    # 기준 방향(컴포넌트1만 정렬 기준으로 씀)
    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)  # (n_splits, p)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col]

    try:
        r_obs, p_perm = perm_pvalue_plsr_cv(
            X, y,
            n_components=1,
            n_splits=5,
            n_perm=1000,
            random_state=42,
            statistic="abs_r"  
        )

        print(f"obs_r = {r_obs:.4f}" if np.isfinite(r_obs) else "obs_r = NaN")
        print(f"perm_p = {p_perm:.4f}" if np.isfinite(p_perm) else "perm_p = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, y,
            n_components=1,
            n_splits=5,
            random_state=42
        )

        # 보기 좋게 합치기
        w_tbl = full_tbl.join(cv_tbl, how="left")

        # coef 절대값 기준 정렬 (기여 큰 순)
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_obs": r_obs, "p_perm": p_perm, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": f"FAIL: {type(e).__name__}"})

# 마지막 요약: permutation p-value 기준 정렬
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("p_perm", ascending=True, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by permutation p-value)")
print(sep)
print(res_ok[["y_col", "n", "r_obs", "p_perm"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/30] TSubset = CD8_PC1
n = 13
obs_r = 0.2430
perm_p = 0.6234
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.6684 -2.5860    -0.6673    0.2791
BUN       0.7438  0.2456     0.6754    0.2127
------------------------------------------------------------
__________________________________________________________________________________________
[2/30] TSubset = CD4_PC1
n = 13
obs_r = -0.2293
perm_p = 0.6154
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.9934 -1.8004     0.9073    0.1080
BUN      -0.1143  0.0177    -0.0346    0.4558
------------------------------------------------------------
__________________________________________________________________________________________
[3/30] TSubset = MAIT_PC1
n = 13
obs_r = -0.1119
perm_p = 0.7932
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.5653 -1.0665     0.4084    0.4348
BUN       0.8249 -0.1328     0.8047    0.2076
------------------------------------------------------------
__________________________________________________________________________________________
[4/30] TSubset = GD1T_PC1
n = 13
obs_r = 0.2672
perm_p = 0.5634
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.8245 -1.8319     0.8116    0.1165
BUN      -0.5659  0.1073    -0.5581    0.1538
------------------------------------------------------------
__________________________________________________________________________________________
[5/30] TSubset = GD2T_PC1
n = 13
obs_r = -0.5751
perm_p = 0.1778
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.3159  0.4064    -0.2732    0.5452
BUN       0.9488 -0.1042     0.8087    0.2052
------------------------------------------------------------
__________________________________________________________________________________________
[6/30] TSubset = MAIT_1_PC1
n = 13
obs_r = -0.3548
perm_p = 0.4276
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.8261  1.0924     0.7738    0.2192
BUN       0.5635  0.0636     0.3895    0.5137
------------------------------------------------------------
__________________________________________________________________________________________
[7/30] TSubset = GD2T_1_PC1
n = 13
obs_r = -0.3865
perm_p = 0.4226
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.6686 -1.1258    -0.5792    0.2209
BUN       0.7436  0.1069     0.7721    0.1914
------------------------------------------------------------
__________________________________________________________________________________________
[8/30] TSubset = CD8_1_PC1
n = 13
obs_r = 0.2188
perm_p = 0.6424
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.7821 -2.9178     0.7418    0.2877
BUN      -0.6232  0.1984    -0.5837    0.2314
------------------------------------------------------------
__________________________________________________________________________________________
[9/30] TSubset = CD8_2_PC1
n = 13
obs_r = -0.1236
perm_p = 0.7872
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.2267 -0.4778    -0.2069    0.1623
BUN       0.9740  0.1752     0.9670    0.0369
------------------------------------------------------------
__________________________________________________________________________________________
[10/30] TSubset = CD8_3_PC1
n = 13
obs_r = 0.0369
perm_p = 0.9371
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.2218 -0.7973    -0.3074    0.3331
BUN       0.9751  0.2991     0.8787    0.2361
------------------------------------------------------------
__________________________________________________________________________________________
[11/30] TSubset = CD4_1_PC1
n = 13
obs_r = 0.1947
perm_p = 0.6793
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.8092 -2.1898     0.7965    0.1230
BUN      -0.5875  0.1357    -0.5813    0.1394
------------------------------------------------------------
__________________________________________________________________________________________
[12/30] TSubset = CD4_2_PC1
n = 13
obs_r = -0.4550
perm_p = 0.2937
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.9555 -1.3508      0.755    0.3031
BUN       0.2949 -0.0356      0.164    0.6419
------------------------------------------------------------
__________________________________________________________________________________________
[13/30] TSubset = CD4_3_PC1
n = 13
obs_r = -0.4981
perm_p = 0.2278
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.9692 -0.8986     0.8996    0.1390
BUN       0.2465 -0.0195    -0.0533    0.4643
------------------------------------------------------------
__________________________________________________________________________________________
[14/30] TSubset = MAIT_2_PC1
n = 13
obs_r = -0.0396
perm_p = 0.9251
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.2958 -0.5520     0.1906    0.5017
BUN       0.9553 -0.1521     0.8669    0.1164
------------------------------------------------------------
__________________________________________________________________________________________
[15/30] TSubset = MAIT_3_PC1
n = 13
obs_r = -0.2105
perm_p = 0.5704
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.9267 -1.9552     0.6704    0.4689
BUN       0.3758 -0.0677     0.5596    0.2776
------------------------------------------------------------
__________________________________________________________________________________________
[16/30] TSubset = GD1T_1_PC1
n = 13
obs_r = 0.2420
perm_p = 0.6134
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.7426 -1.7769     0.7267    0.1751
BUN      -0.6697  0.1368    -0.6505    0.1736
------------------------------------------------------------
__________________________________________________________________________________________
[17/30] TSubset = GD1T_2_PC1
n = 13
obs_r = -0.5901
perm_p = 0.1369
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.7492 -0.4560     0.5172    0.3567
BUN       0.6623 -0.0344     0.7139    0.3890
------------------------------------------------------------
__________________________________________________________________________________________
[18/30] TSubset = GD1T_3_PC1
n = 13
obs_r = 0.0693
perm_p = 0.8991
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.9965 -1.7883     0.9350    0.1153
BUN      -0.0833  0.0128    -0.1103    0.3589
------------------------------------------------------------
__________________________________________________________________________________________
[19/30] TSubset = GD2T_2_PC1
n = 13
obs_r = -0.6734
perm_p = 0.0709
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.7982 -0.3967     0.8148    0.1937
BUN       0.6024 -0.0255     0.1055    0.6071
------------------------------------------------------------
__________________________________________________________________________________________
[20/30] TSubset = GD2T_3_PC1
n = 13
obs_r = -0.4423
perm_p = 0.3117
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr        0.4734 -0.5702     0.4216    0.4998
BUN       0.8808 -0.0905     0.5841    0.5929
------------------------------------------------------------
__________________________________________________________________________________________
[21/30] TSubset = CD4trm
n = 13
obs_r = -0.0588
perm_p = 0.9011
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr         0.895 -30.6042     0.8487    0.1818
BUN       -0.446   1.3016    -0.4460    0.2605
------------------------------------------------------------
__________________________________________________________________________________________
[22/30] TSubset = CD8trm
n = 13
obs_r = -0.1508
perm_p = 0.7562
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9579 -31.2569     0.9554    0.0223
BUN      -0.2870   0.7991    -0.2868    0.0755
------------------------------------------------------------
__________________________________________________________________________________________
[23/30] TSubset = MAITtrm
n = 13
obs_r = -0.2476
perm_p = 0.6014
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.1665 -3.6935    -0.2586    0.3856
BUN       0.9860  1.8671     0.8819    0.2133
------------------------------------------------------------
__________________________________________________________________________________________
[24/30] TSubset = GD1Ttrm
n = 13
obs_r = -0.4189
perm_p = 0.3357
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.3706 -4.2501    -0.0117    0.7551
BUN       0.9288  0.9090     0.7220    0.1675
------------------------------------------------------------
__________________________________________________________________________________________
[25/30] TSubset = GD2Ttrm
n = 13
obs_r = -0.5374
perm_p = 0.2288
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9721 -20.2947     0.8527    0.1064
BUN      -0.2347   0.4182    -0.3096    0.4583
------------------------------------------------------------
__________________________________________________________________________________________
[26/30] TSubset = CD4grzk
n = 13
obs_r = 0.0572
perm_p = 0.9091
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.6709 -18.0451    -0.6619    0.3419
BUN       0.7415   1.7020     0.6299    0.2991
------------------------------------------------------------
__________________________________________________________________________________________
[27/30] TSubset = CD8grzk
n = 13
obs_r = 0.1687
perm_p = 0.7383
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.6434 -38.7330    -0.6380    0.3078
BUN       0.7655   3.9329     0.6932    0.2141
------------------------------------------------------------
__________________________________________________________________________________________
[28/30] TSubset = MAITgrzK
n = 13
obs_r = -0.1193
perm_p = 0.7872
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9968 -30.7096     0.8725    0.1818
BUN      -0.0799   0.2099    -0.0739    0.5085
------------------------------------------------------------
__________________________________________________________________________________________
[29/30] TSubset = GD1TgrzK
n = 13
obs_r = -0.1495
perm_p = 0.7762
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.8139 -54.9307     0.7650    0.2071
BUN      -0.5810   3.3459    -0.5065    0.3935
------------------------------------------------------------
__________________________________________________________________________________________
[30/30] TSubset = GD2TgrzK
n = 13
obs_r = -0.2055
perm_p = 0.6943
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.3881 -14.3776    -0.4558    0.3868
BUN       0.9216   2.9137     0.7809    0.2801
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by permutation p-value)
__________________________________________________________________________________________
     y_col  n     r_obs   p_perm
GD2T_2_PC1 13 -0.673422 0.070929
GD1T_2_PC1 13 -0.590088 0.136863
  GD2T_PC1 13 -0.575143 0.177822
 CD4_3_PC1 13 -0.498132 0.227772
   GD2Ttrm 13 -0.537411 0.228771
 CD4_2_PC1 13 -0.454961 0.293706
GD2T_3_PC1 13 -0.442330 0.311688
   GD1Ttrm 13 -0.418890 0.335664
GD2T_1_PC1 13 -0.386457 0.422577
MAIT_1_PC1 13 -0.354830 0.427572
  GD1T_PC1 13  0.267163 0.563437
MAIT_3_PC1 13 -0.210524 0.570430
   MAITtrm 13 -0.247577 0.601399
GD1T_1_PC1 13  0.242006 0.613387
   CD4_PC1 13 -0.229304 0.615385
   CD8_PC1 13  0.242997 0.623377
 CD8_1_PC1 13  0.218817 0.642358
 CD4_1_PC1 13  0.194719 0.679321
  GD2TgrzK 13 -0.205484 0.694306
   CD8grzk 13  0.168738 0.738262
    CD8trm 13 -0.150848 0.756244
  GD1TgrzK 13 -0.149550 0.776224
  MAITgrzK 13 -0.119338 0.787213
 CD8_2_PC1 13 -0.123552 0.787213
  MAIT_PC1 13 -0.111931 0.793207
GD1T_3_PC1 13  0.069339 0.899101
    CD4trm 13 -0.058824 0.901099
   CD4grzk 13  0.057153 0.909091
MAIT_2_PC1 13 -0.039628 0.925075
 CD8_3_PC1 13  0.036905 0.937063
__________________________________________________________________________________________

#### df2_간

In [ ]:
sep = "_" * 90

X_cols =  ['AST', 'ALT', 'ALP', 'Bilirubin', 'Albumin', 'PT', 'APTT']

y_candidates = [
    'CD8_PC1', 'CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1', 'MAIT_1_PC1',
    'GD2T_1_PC1', 'CD8_1_PC1', 'CD8_2_PC1', 'CD8_3_PC1', 'CD4_1_PC1',
    'CD4_2_PC1', 'CD4_3_PC1', 'MAIT_2_PC1', 'MAIT_3_PC1', 'GD1T_1_PC1',
    'GD1T_2_PC1', 'GD1T_3_PC1', 'GD2T_2_PC1', 'GD2T_3_PC1',
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환"""
    n = len(y)
    n_splits = min(n_splits, n)  # 안전
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def perm_pvalue_plsr_cv(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5,
                        n_perm=1000, random_state=42, statistic="abs_r"):
    """
    permutation p-value (CV 포함) 계산
    statistic:
      - "abs_r" : |corr(y, yhat_cv)|
      - "r2"    : corr(y, yhat_cv)^2
    """
    y = y.astype(float).to_numpy()
    y_pred = cv_pred_plsr(X, y, n_components=n_components, n_splits=n_splits, random_state=random_state)
    if y_pred is None:
        return np.nan, np.nan

    # 관측 통계량
    if np.std(y) < 1e-12 or np.std(y_pred) < 1e-12:
        r_obs = np.nan
        stat_obs = np.nan
    else:
        r_obs, _ = pearsonr(y, y_pred)
        stat_obs = abs(r_obs) if statistic == "abs_r" else (r_obs ** 2)

    if not np.isfinite(stat_obs):
        return r_obs, np.nan

    rng = np.random.default_rng(random_state)
    ge = 0

    # permutation: y를 셔플해서 CV를 다시 수행
    for _ in range(n_perm):
        y_perm = rng.permutation(y)
        y_perm_pred = cv_pred_plsr(X, y_perm, n_components=n_components, n_splits=n_splits, random_state=random_state)
        if y_perm_pred is None or np.std(y_perm_pred) < 1e-12:
            stat_perm = 0.0
        else:
            r_perm, _ = pearsonr(y_perm, y_perm_pred)
            stat_perm = abs(r_perm) if statistic == "abs_r" else (r_perm ** 2)

        if stat_perm >= stat_obs:
            ge += 1

    p_perm = (ge + 1) / (n_perm + 1)
    return r_obs, p_perm


def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등할 수 있어서, fold weight는 full-fit weight에 맞춰 부호 정렬합니다.
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    # x_weights_: (p, n_components), coef_: (p, 1)
    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    # 기준 방향(컴포넌트1만 정렬 기준으로 씀)
    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)  # (n_splits, p)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df2.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col]

    try:
        r_obs, p_perm = perm_pvalue_plsr_cv(
            X, y,
            n_components=1,
            n_splits=5,
            n_perm=1000,
            random_state=42,
            statistic="abs_r"  
        )

        print(f"obs_r = {r_obs:.4f}" if np.isfinite(r_obs) else "obs_r = NaN")
        print(f"perm_p = {p_perm:.4f}" if np.isfinite(p_perm) else "perm_p = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, y,
            n_components=1,
            n_splits=5,
            random_state=42
        )

        # 보기 좋게 합치기
        w_tbl = full_tbl.join(cv_tbl, how="left")

        # coef 절대값 기준 정렬 (기여 큰 순)
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_obs": r_obs, "p_perm": p_perm, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": f"FAIL: {type(e).__name__}"})

# 마지막 요약: permutation p-value 기준 정렬
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("p_perm", ascending=True, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by permutation p-value)")
print(sep)
print(res_ok[["y_col", "n", "r_obs", "p_perm"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/30] TSubset = CD8_PC1
n = 22
obs_r = 0.1599
perm_p = 0.6414
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.5061  0.7251     0.4681    0.1384
Albumin         0.2404  0.2508     0.2314    0.1334
APTT           -0.5031 -0.0634    -0.4708    0.0841
ALT             0.4105  0.0255     0.4158    0.1550
PT              0.5133  0.0169     0.4613    0.0881
AST             0.0301  0.0025     0.0470    0.2411
ALP            -0.0122 -0.0003    -0.0261    0.1117
------------------------------------------------------------
__________________________________________________________________________________________
[2/30] TSubset = CD4_PC1
n = 22
obs_r = 0.0589
perm_p = 0.8561
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.1595  0.2745    -0.1384    0.0968
APTT            0.6832 -0.1421     0.6242    0.0351
ALT             0.3903 -0.0401     0.3839    0.1537
PT             -0.4783  0.0260    -0.4198    0.1400
AST            -0.1338  0.0185    -0.0691    0.3095
ALP             0.3297 -0.0113     0.2744    0.2580
Bilirubin       0.0015 -0.0037     0.0125    0.1344
------------------------------------------------------------
__________________________________________________________________________________________
[3/30] TSubset = MAIT_PC1
n = 22
obs_r = 0.4024
perm_p = 0.1748
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.3971 -0.8066     0.3740    0.1106
APTT           -0.4787  0.0856    -0.4486    0.0856
PT              0.6688 -0.0312     0.6318    0.0534
Albumin         0.0178 -0.0264    -0.0030    0.1920
AST             0.1268 -0.0150     0.1052    0.1790
ALP            -0.3855  0.0113    -0.3606    0.1953
ALT            -0.0305  0.0027    -0.0503    0.1249
------------------------------------------------------------
__________________________________________________________________________________________
[4/30] TSubset = GD1T_PC1
n = 16
obs_r = -0.3048
perm_p = 0.4266
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.1830  0.4895    -0.1828    0.2092
PT              0.8917 -0.0635     0.7370    0.1434
APTT           -0.1564  0.0366    -0.1178    0.2085
ALT            -0.2353  0.0277    -0.1973    0.2313
ALP            -0.2943  0.0153    -0.2454    0.3690
AST             0.0696 -0.0108     0.0084    0.2493
Bilirubin       0.0033 -0.0090    -0.0271    0.1653
------------------------------------------------------------
__________________________________________________________________________________________
[5/30] TSubset = GD2T_PC1
n = 22
obs_r = 0.4817
perm_p = 0.0909
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.7140 -1.1737     0.6939    0.0957
Bilirubin       0.1626 -0.3672     0.1567    0.1440
ALT             0.3497 -0.0343     0.3340    0.0622
PT              0.4752 -0.0246     0.4384    0.1048
APTT           -0.1096  0.0218    -0.1181    0.1159
AST             0.1365 -0.0180     0.1391    0.0947
ALP             0.2917 -0.0095     0.2873    0.1609
------------------------------------------------------------
__________________________________________________________________________________________
[6/30] TSubset = MAIT_1_PC1
n = 22
obs_r = 0.2072
perm_p = 0.5095
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.4285  0.8654     0.3908    0.1078
APTT           -0.4440 -0.0789    -0.3942    0.1152
Albumin         0.0278  0.0409     0.0032    0.1553
PT              0.7159  0.0332     0.6639    0.0481
AST             0.0912  0.0108     0.0665    0.2301
ALP            -0.3119 -0.0091    -0.2885    0.2847
ALT             0.0199  0.0017    -0.0086    0.1372
------------------------------------------------------------
__________________________________________________________________________________________
[7/30] TSubset = GD2T_1_PC1
n = 22
obs_r = 0.4369
perm_p = 0.1678
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.7308  1.0652     0.7010    0.0809
Bilirubin       0.1399  0.2801     0.1313    0.1597
ALT             0.3699  0.0321     0.3550    0.0684
PT              0.3985  0.0183     0.3559    0.1718
AST             0.1243  0.0145     0.1276    0.1242
ALP             0.3657  0.0106     0.3556    0.1509
APTT           -0.0388 -0.0068    -0.0401    0.1159
------------------------------------------------------------
__________________________________________________________________________________________
[8/30] TSubset = CD8_1_PC1
n = 22
obs_r = 0.1281
perm_p = 0.7073
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.4720  0.6374    -0.4301    0.1579
Albumin        -0.2655  0.2610    -0.2608    0.1350
APTT            0.5165 -0.0614     0.4806    0.0918
ALT            -0.4090  0.0240    -0.4087    0.1215
PT             -0.5163  0.0160    -0.4609    0.0965
AST            -0.0632  0.0050    -0.0765    0.2646
ALP             0.0461 -0.0009     0.0593    0.1154
------------------------------------------------------------
__________________________________________________________________________________________
[9/30] TSubset = CD8_2_PC1
n = 22
obs_r = 0.1517
perm_p = 0.6364
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.5929  0.7234     0.5485    0.1033
Albumin         0.1765  0.1568     0.1651    0.1078
APTT           -0.4339 -0.0466    -0.3893    0.1478
ALT             0.3803  0.0201     0.3858    0.2307
PT              0.5237  0.0147     0.4837    0.0549
ALP             0.0998  0.0018     0.0895    0.1409
AST            -0.0158 -0.0011    -0.0013    0.2043
------------------------------------------------------------
__________________________________________________________________________________________
[10/30] TSubset = CD8_3_PC1
n = 22
obs_r = 0.0340
perm_p = 0.9241
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.5964  0.6147     0.5499    0.0601
Albumin         0.1343  0.1008     0.0833    0.2012
APTT           -0.4643 -0.0421    -0.4246    0.1181
ALT             0.4298  0.0192     0.4381    0.2460
PT              0.4480  0.0106     0.3615    0.1362
AST            -0.1371 -0.0083    -0.1172    0.1817
ALP             0.0799  0.0012     0.0820    0.1976
------------------------------------------------------------
__________________________________________________________________________________________
[11/30] TSubset = CD4_1_PC1
n = 22
obs_r = 0.2776
perm_p = 0.3796
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.1905  0.3856    -0.1762    0.1493
Albumin        -0.1341  0.1976    -0.1292    0.0619
APTT            0.7383 -0.1315     0.6937    0.0346
PT             -0.5263  0.0245    -0.4743    0.1319
ALT             0.2546 -0.0224     0.2646    0.2074
AST            -0.0658  0.0078    -0.0359    0.1763
ALP             0.2333 -0.0068     0.2224    0.1947
------------------------------------------------------------
__________________________________________________________________________________________
[12/30] TSubset = CD4_2_PC1
n = 22
obs_r = -0.0253
perm_p = 0.9321
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.1695  0.2219     0.1221    0.1265
Bilirubin       0.0757  0.1362     0.0482    0.1009
APTT           -0.5792 -0.0916    -0.5064    0.0770
AST             0.2368  0.0249     0.1596    0.4304
PT              0.5797  0.0239     0.5248    0.0782
ALT            -0.3034 -0.0237    -0.3234    0.1074
ALP            -0.3819 -0.0099    -0.3214    0.1921
------------------------------------------------------------
__________________________________________________________________________________________
[13/30] TSubset = CD4_3_PC1
n = 22
obs_r = -0.1606
perm_p = 0.5914
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.4189 -0.9060     0.4057    0.1886
Albumin        -0.1358  0.2139    -0.1202    0.1116
APTT            0.5637 -0.1073     0.4683    0.1364
ALT             0.6225 -0.0585     0.5264    0.1424
ALP             0.2982 -0.0093     0.1900    0.4075
PT             -0.1035  0.0051    -0.0402    0.2084
AST            -0.0353  0.0045     0.0295    0.2471
------------------------------------------------------------
__________________________________________________________________________________________
[14/30] TSubset = MAIT_2_PC1
n = 22
obs_r = 0.4700
perm_p = 0.1019
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.4069 -0.6764     0.3834    0.1232
APTT           -0.5231  0.0765    -0.4962    0.0808
PT              0.6298 -0.0240     0.5975    0.0532
Albumin        -0.0145  0.0175    -0.0334    0.1937
AST             0.1129 -0.0110     0.0962    0.1633
ALP            -0.3755  0.0090    -0.3555    0.1648
ALT            -0.1008  0.0073    -0.1136    0.0963
------------------------------------------------------------
__________________________________________________________________________________________
[15/30] TSubset = MAIT_3_PC1
n = 22
obs_r = 0.2982
perm_p = 0.3197
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.2653 -0.4611     0.2481    0.0820
Albumin         0.1117 -0.1413     0.0884    0.2544
APTT           -0.3504  0.0536    -0.3236    0.0955
PT              0.6574 -0.0262     0.6157    0.0898
AST             0.2383 -0.0242     0.2121    0.1305
ALP            -0.5391  0.0136    -0.5133    0.1222
ALT             0.1217 -0.0092     0.0964    0.2022
------------------------------------------------------------
__________________________________________________________________________________________
[16/30] TSubset = GD1T_1_PC1
n = 16
obs_r = -0.2339
perm_p = 0.5435
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.0939 -0.2338     0.0562    0.1329
Albumin        -0.0883  0.2150    -0.1009    0.1742
PT              0.8722 -0.0566     0.7423    0.1045
APTT           -0.2194  0.0468    -0.1731    0.1943
ALT            -0.3699  0.0396    -0.3206    0.2255
ALP            -0.1937  0.0091    -0.1571    0.3708
AST            -0.0097  0.0014    -0.0608    0.2411
------------------------------------------------------------
__________________________________________________________________________________________
[17/30] TSubset = GD1T_2_PC1
n = 16
obs_r = -0.3360
perm_p = 0.3367
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.5236  1.7807    -0.4331    0.2141
Bilirubin      -0.2279  0.7916    -0.1994    0.2138
PT              0.6307 -0.0571     0.4900    0.1899
AST             0.2577 -0.0507     0.1778    0.2209
ALT             0.2360 -0.0353     0.1786    0.1236
ALP            -0.3902  0.0257    -0.2945    0.5124
APTT           -0.0407  0.0121    -0.0288    0.1503
------------------------------------------------------------
__________________________________________________________________________________________
[18/30] TSubset = GD1T_3_PC1
n = 16
obs_r = -0.3863
perm_p = 0.3107
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.2815  1.1768    -0.2428    0.2365
Albumin        -0.2624  1.0736    -0.2243    0.2245
APTT            0.1889 -0.0677     0.1351    0.2347
PT              0.6175 -0.0673     0.4940    0.2509
AST             0.2815 -0.0666     0.2098    0.2326
ALP            -0.5499  0.0436    -0.4306    0.3677
ALT             0.2309 -0.0416     0.1802    0.2110
------------------------------------------------------------
__________________________________________________________________________________________
[19/30] TSubset = GD2T_2_PC1
n = 22
obs_r = 0.2985
perm_p = 0.3227
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6133 -0.7304     0.5978    0.1180
Bilirubin       0.2005 -0.3279     0.1916    0.1374
APTT           -0.2422  0.0349    -0.2512    0.1597
ALT             0.3541 -0.0251     0.3364    0.0745
PT              0.6106 -0.0229     0.5808    0.0342
AST             0.1417 -0.0135     0.1442    0.0262
ALP             0.0817 -0.0019     0.0789    0.1262
------------------------------------------------------------
__________________________________________________________________________________________
[20/30] TSubset = GD2T_3_PC1
n = 22
obs_r = 0.3886
perm_p = 0.1888
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.7137 -1.1081     0.6916    0.1015
Bilirubin       0.1727 -0.3682     0.1715    0.1371
APTT           -0.1527  0.0287    -0.1644    0.1486
ALT             0.2834 -0.0262     0.2628    0.0731
PT              0.5074 -0.0249     0.4748    0.0710
AST             0.1505 -0.0187     0.1539    0.0906
ALP             0.2776 -0.0086     0.2667    0.1584
------------------------------------------------------------
__________________________________________________________________________________________
[21/30] TSubset = CD4trm
n = 22
obs_r = 0.2493
perm_p = 0.4226
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.3585  9.2093     0.3433    0.1365
Albumin         0.1280  2.3950     0.1126    0.0689
APTT           -0.5931 -1.3407    -0.5558    0.0662
PT              0.6429  0.3793     0.6155    0.0616
AST             0.1596  0.2396     0.1349    0.2448
ALP            -0.2430 -0.0904    -0.2399    0.1239
ALT            -0.0745 -0.0831    -0.0956    0.1191
------------------------------------------------------------
__________________________________________________________________________________________
[22/30] TSubset = CD8trm
n = 22
obs_r = 0.1120
perm_p = 0.7353
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.4859  9.8589     0.4394    0.1651
Albumin         0.2714  4.0091     0.2751    0.1020
APTT           -0.4794 -0.8559    -0.4302    0.1192
ALT             0.3715  0.3273     0.3645    0.1259
PT              0.5553  0.2588     0.5192    0.0662
AST             0.1181  0.1400     0.1070    0.2888
ALP            -0.0090 -0.0027    -0.0174    0.0976
------------------------------------------------------------
__________________________________________________________________________________________
[23/30] TSubset = MAITtrm
n = 22
obs_r = 0.1625
perm_p = 0.5734
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.4945  12.8947     0.4390    0.1366
APTT           -0.5318  -1.2202    -0.4649    0.1465
Albumin        -0.0601  -1.1407    -0.0738    0.1128
PT              0.6468   0.3874     0.6048    0.0647
ALT            -0.1339  -0.1516    -0.1399    0.0927
ALP            -0.1811  -0.0684    -0.1761    0.2831
AST             0.0007   0.0010     0.0006    0.2568
------------------------------------------------------------
__________________________________________________________________________________________
[24/30] TSubset = GD1Ttrm
n = 16
obs_r = 0.0335
perm_p = 0.9321
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.2657  7.0324    -0.2589    0.1225
Bilirubin       0.1732 -4.6837     0.1444    0.1088
APTT           -0.4266  0.9884    -0.3872    0.0716
PT              0.7538 -0.5311     0.6807    0.0885
ALT            -0.3792  0.4414    -0.3652    0.1990
AST            -0.0682  0.1044    -0.1050    0.2224
ALP             0.0259 -0.0133     0.0139    0.2530
------------------------------------------------------------
__________________________________________________________________________________________
[25/30] TSubset = GD2Ttrm
n = 22
obs_r = 0.2259
perm_p = 0.4505
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.6424  10.6543     0.6037    0.0968
Bilirubin       0.1703   3.8780     0.1316    0.2500
ALT             0.4946   0.4892     0.4858    0.1265
PT              0.5098   0.2667     0.4400    0.1987
APTT           -0.1177  -0.2359    -0.1029    0.1517
AST             0.1113   0.1481     0.1160    0.0919
ALP             0.1662   0.0548     0.1598    0.1223
------------------------------------------------------------
__________________________________________________________________________________________
[26/30] TSubset = CD4grzk
n = 22
obs_r = -0.1173
perm_p = 0.7203
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.1542 -4.5815     0.1334    0.2634
Albumin        -0.1095  2.3698    -0.1126    0.1203
APTT            0.7994 -2.0901     0.6996    0.0987
ALT             0.5038 -0.6500     0.4197    0.2945
AST             0.1161 -0.2016     0.1226    0.0736
PT             -0.1837  0.1254    -0.1490    0.1974
ALP             0.1552 -0.0668     0.1142    0.3037
------------------------------------------------------------
__________________________________________________________________________________________
[27/30] TSubset = CD8grzk
n = 22
obs_r = 0.0303
perm_p = 0.9371
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.4422  6.1520    -0.3964    0.1587
Albumin        -0.2516  2.5490    -0.2103    0.2259
APTT            0.5649 -0.6915     0.5515    0.1556
ALT            -0.4599  0.2778    -0.4383    0.1142
PT             -0.4467  0.1427    -0.3335    0.2255
ALP             0.1026 -0.0207     0.1175    0.1439
AST             0.0230 -0.0187     0.0055    0.1914
------------------------------------------------------------
__________________________________________________________________________________________
[28/30] TSubset = MAITgrzK
n = 22
obs_r = 0.1417
perm_p = 0.6613
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.3189 -7.4164     0.2890    0.0731
Albumin         0.1225 -2.0744     0.0915    0.2013
APTT           -0.3091  0.6325    -0.2657    0.1370
PT              0.7309 -0.3904     0.6718    0.0612
AST             0.1834 -0.2492     0.1489    0.1902
ALT             0.1880 -0.1899     0.1496    0.2184
ALP            -0.4296  0.1447    -0.3987    0.2756

#### df2+신장

In [ ]:
# df2 + 신장
sep = "_" * 90

X_cols =  ['BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl']

y_candidates = [
    'CD8_PC1', 'CD4_PC1', 'MAIT_PC1', 'GD1T_PC1', 'GD2T_PC1', 'MAIT_1_PC1',
    'GD2T_1_PC1', 'CD8_1_PC1', 'CD8_2_PC1', 'CD8_3_PC1', 'CD4_1_PC1',
    'CD4_2_PC1', 'CD4_3_PC1', 'MAIT_2_PC1', 'MAIT_3_PC1', 'GD1T_1_PC1',
    'GD1T_2_PC1', 'GD1T_3_PC1', 'GD2T_2_PC1', 'GD2T_3_PC1',
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환"""
    n = len(y)
    n_splits = min(n_splits, n)  # 안전
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def perm_pvalue_plsr_cv(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5,
                        n_perm=1000, random_state=42, statistic="abs_r"):
    """
    permutation p-value (CV 포함) 계산
    statistic:
      - "abs_r" : |corr(y, yhat_cv)|
      - "r2"    : corr(y, yhat_cv)^2
    """
    y = y.astype(float).to_numpy()
    y_pred = cv_pred_plsr(X, y, n_components=n_components, n_splits=n_splits, random_state=random_state)
    if y_pred is None:
        return np.nan, np.nan

    # 관측 통계량
    if np.std(y) < 1e-12 or np.std(y_pred) < 1e-12:
        r_obs = np.nan
        stat_obs = np.nan
    else:
        r_obs, _ = pearsonr(y, y_pred)
        stat_obs = abs(r_obs) if statistic == "abs_r" else (r_obs ** 2)

    if not np.isfinite(stat_obs):
        return r_obs, np.nan

    rng = np.random.default_rng(random_state)
    ge = 0

    # permutation: y를 셔플해서 CV를 다시 수행
    for _ in range(n_perm):
        y_perm = rng.permutation(y)
        y_perm_pred = cv_pred_plsr(X, y_perm, n_components=n_components, n_splits=n_splits, random_state=random_state)
        if y_perm_pred is None or np.std(y_perm_pred) < 1e-12:
            stat_perm = 0.0
        else:
            r_perm, _ = pearsonr(y_perm, y_perm_pred)
            stat_perm = abs(r_perm) if statistic == "abs_r" else (r_perm ** 2)

        if stat_perm >= stat_obs:
            ge += 1

    p_perm = (ge + 1) / (n_perm + 1)
    return r_obs, p_perm


def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등할 수 있어서, fold weight는 full-fit weight에 맞춰 부호 정렬합니다.
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    # x_weights_: (p, n_components), coef_: (p, 1)
    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    # 기준 방향(컴포넌트1만 정렬 기준으로 씀)
    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)  # (n_splits, p)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df2.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col]

    try:
        r_obs, p_perm = perm_pvalue_plsr_cv(
            X, y,
            n_components=1,
            n_splits=5,
            n_perm=1000,
            random_state=42,
            statistic="abs_r"  
        )

        print(f"obs_r = {r_obs:.4f}" if np.isfinite(r_obs) else "obs_r = NaN")
        print(f"perm_p = {p_perm:.4f}" if np.isfinite(p_perm) else "perm_p = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, y,
            n_components=1,
            n_splits=5,
            random_state=42
        )

        # 보기 좋게 합치기
        w_tbl = full_tbl.join(cv_tbl, how="left")

        # coef 절대값 기준 정렬 (기여 큰 순)
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_obs": r_obs, "p_perm": p_perm, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": f"FAIL: {type(e).__name__}"})

# 마지막 요약: permutation p-value 기준 정렬
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("p_perm", ascending=True, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by permutation p-value)")
print(sep)
print(res_ok[["y_col", "n", "r_obs", "p_perm"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/30] TSubset = CD8_PC1
n = 22
obs_r = -0.1455
perm_p = 0.6803
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.0711  0.2037     0.0264    0.3688
BUN               -0.3862 -0.0346    -0.4001    0.2409
GFR(CKD_EPI)      -0.6156 -0.0206    -0.5690    0.1496
CrCl               0.6832  0.0121     0.5479    0.2293
------------------------------------------------------------
__________________________________________________________________________________________
[2/30] TSubset = CD4_PC1
n = 22
obs_r = -0.0144
perm_p = 0.9650
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
BUN                0.5309  0.0383     0.5216    0.2361
Cr                 0.0069  0.0160     0.0426    0.1119
GFR(CKD_EPI)      -0.5001 -0.0135    -0.3749    0.2795
CrCl               0.6841  0.0098     0.6704    0.1541
------------------------------------------------------------
__________________________________________________________________________________________
[3/30] TSubset = MAIT_PC1
n = 22
obs_r = 0.0883
perm_p = 0.7862
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.1859  0.4442    -0.1342    0.1930
GFR(CKD_EPI)      -0.5960  0.0167    -0.5612    0.0784
CrCl               0.7777 -0.0115     0.7387    0.0906
BUN               -0.0729  0.0055    -0.0941    0.2985
------------------------------------------------------------
__________________________________________________________________________________________
[4/30] TSubset = GD1T_PC1
n = 16
obs_r = -0.5066
perm_p = 0.1588
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.8475  2.5312     0.6080    0.3280
GFR(CKD_EPI)       0.4059  0.0157     0.2310    0.5606
BUN               -0.1476 -0.0145    -0.1245    0.1104
CrCl               0.3086  0.0057     0.2126    0.4596
------------------------------------------------------------
__________________________________________________________________________________________
[5/30] TSubset = GD2T_PC1
n = 22
obs_r = -0.5105
perm_p = 0.0979
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.1061  0.1409    -0.1650    0.5352
GFR(CKD_EPI)       0.9264 -0.0144     0.7191    0.1484
BUN               -0.1044  0.0043     0.0583    0.3157
CrCl               0.3459 -0.0028     0.2198    0.3111
------------------------------------------------------------
__________________________________________________________________________________________
[6/30] TSubset = MAIT_1_PC1
n = 22
obs_r = 0.3464
perm_p = 0.2967
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.2207 -0.8788    -0.1950    0.0993
CrCl               0.9075  0.0224     0.8788    0.0433
GFR(CKD_EPI)      -0.3528 -0.0164    -0.3374    0.0976
BUN               -0.0579 -0.0072    -0.0714    0.2592
------------------------------------------------------------
__________________________________________________________________________________________
[7/30] TSubset = GD2T_1_PC1
n = 22
obs_r = -0.3996
perm_p = 0.2008
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.2454 -0.3976    -0.1457    0.4898
GFR(CKD_EPI)       0.9200  0.0174     0.7293    0.2139
BUN                0.1830  0.0093     0.1730    0.2290
CrCl              -0.2447 -0.0025    -0.2097    0.3581
------------------------------------------------------------
__________________________________________________________________________________________
[8/30] TSubset = CD8_1_PC1
n = 22
obs_r = -0.1052
perm_p = 0.7493
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.0498  0.1327     0.0201    0.3343
BUN               -0.2621 -0.0218    -0.2833    0.2369
GFR(CKD_EPI)      -0.6024 -0.0188    -0.5745    0.1768
CrCl               0.7523  0.0124     0.6438    0.1390
------------------------------------------------------------
__________________________________________________________________________________________
[9/30] TSubset = CD8_2_PC1
n = 22
obs_r = -0.1831
perm_p = 0.5904
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.1264  0.3700    -0.0506    0.4034
BUN                0.6315 -0.0578     0.5727    0.1478
GFR(CKD_EPI)       0.6641 -0.0227     0.5678    0.0478
CrCl              -0.3797  0.0069    -0.2785    0.3873
------------------------------------------------------------
__________________________________________________________________________________________
[10/30] TSubset = CD8_3_PC1
n = 22
obs_r = -0.2714
perm_p = 0.4316
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.1349  0.2837    -0.0312    0.5303
BUN                0.8677 -0.0571     0.7004    0.1505
GFR(CKD_EPI)       0.4028 -0.0099     0.2863    0.2445
CrCl              -0.2581  0.0034    -0.1693    0.3656
------------------------------------------------------------
__________________________________________________________________________________________
[11/30] TSubset = CD4_1_PC1
n = 22
obs_r = -0.1225
perm_p = 0.7103
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.0161 -0.0333     0.0675    0.3914
BUN                0.4351  0.0282     0.3529    0.2081
GFR(CKD_EPI)      -0.6179 -0.0150    -0.5526    0.1286
CrCl               0.6546  0.0084     0.6146    0.1469
------------------------------------------------------------
__________________________________________________________________________________________
[12/30] TSubset = CD4_2_PC1
n = 22
obs_r = -0.0400
perm_p = 0.9061
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.1650  0.3178    -0.2417    0.2787
BUN               -0.4569  0.0275    -0.4497    0.2481
GFR(CKD_EPI)       0.6229 -0.0140     0.5259    0.1711
CrCl              -0.6132  0.0073    -0.5678    0.0836
------------------------------------------------------------
__________________________________________________________________________________________
[13/30] TSubset = CD4_3_PC1
n = 22
obs_r = -0.2681
perm_p = 0.4326
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.2022 -0.4266    -0.2130    0.3301
BUN                0.6625  0.0437     0.5223    0.2001
CrCl               0.7131  0.0093     0.5855    0.2713
GFR(CKD_EPI)      -0.1082 -0.0027     0.0112    0.4484
------------------------------------------------------------
__________________________________________________________________________________________
[14/30] TSubset = MAIT_2_PC1
n = 22
obs_r = -0.0444
perm_p = 0.8841
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.0289  0.0456    -0.0196    0.2988
GFR(CKD_EPI)       0.8890  0.0164     0.8124    0.1018
BUN                0.1077  0.0053     0.1159    0.2994
CrCl              -0.4442 -0.0043    -0.3986    0.1407
------------------------------------------------------------
__________________________________________________________________________________________
[15/30] TSubset = MAIT_3_PC1
n = 22
obs_r = -0.2972
perm_p = 0.3826
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.4435  0.6902    -0.3429    0.2527
CrCl               0.8765 -0.0084     0.7708    0.1879
GFR(CKD_EPI)      -0.1854  0.0034    -0.1408    0.3850
BUN                0.0286 -0.0014     0.0165    0.2964
------------------------------------------------------------
__________________________________________________________________________________________
[16/30] TSubset = GD1T_1_PC1
n = 16
obs_r = -0.4927
perm_p = 0.1758
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.6414  1.4747     0.3710    0.5208
GFR(CKD_EPI)       0.7339  0.0219     0.5113    0.3814
BUN               -0.2226 -0.0168    -0.0991    0.2006
CrCl               0.0208  0.0003    -0.2437    0.4556
------------------------------------------------------------
__________________________________________________________________________________________
[17/30] TSubset = GD1T_2_PC1
n = 16
obs_r = -0.0085
perm_p = 0.9820
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.8171  4.0759     0.7673    0.1510
CrCl               0.5759  0.0177     0.4837    0.2894
BUN               -0.0218 -0.0036    -0.0282    0.1279
GFR(CKD_EPI)      -0.0143 -0.0009    -0.0109    0.3122
------------------------------------------------------------
__________________________________________________________________________________________
[18/30] TSubset = GD1T_3_PC1
n = 16
obs_r = -0.2386
perm_p = 0.5255
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.8119  3.3013     0.7043    0.1148
GFR(CKD_EPI)      -0.2519 -0.0133    -0.2030    0.3025
CrCl               0.5266  0.0132     0.4105    0.4971
BUN                0.0074  0.0010     0.0017    0.1266
------------------------------------------------------------
__________________________________________________________________________________________
[19/30] TSubset = GD2T_2_PC1
n = 22
obs_r = -0.4544
perm_p = 0.1499
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.2084 -0.4074     0.1353    0.4223
BUN               -0.6331  0.0387    -0.4758    0.2910
CrCl               0.7240 -0.0088     0.6506    0.2752
GFR(CKD_EPI)       0.1775 -0.0041     0.1095    0.2476
------------------------------------------------------------
__________________________________________________________________________________________
[20/30] TSubset = GD2T_3_PC1
n = 22
obs_r = -0.5580
perm_p = 0.0689
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.0404 -0.0764     0.0368    0.3785
CrCl               0.8818 -0.0103     0.6971    0.3947
GFR(CKD_EPI)       0.4612 -0.0102     0.3283    0.3434
BUN               -0.0904  0.0053    -0.0196    0.2978
------------------------------------------------------------
__________________________________________________________________________________________
[21/30] TSubset = CD4trm
n = 22
obs_r = -0.0490
perm_p = 0.8731
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.2283  7.1559    -0.2674    0.3379
GFR(CKD_EPI)       0.8199 -0.3006     0.7399    0.1168
BUN               -0.2327  0.2282    -0.1941    0.2451
CrCl              -0.4706  0.0913    -0.4075    0.1838
------------------------------------------------------------
__________________________________________________________________________________________
[22/30] TSubset = CD8trm
n = 22
obs_r = -0.0097
perm_p = 0.9740
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.0558  2.4360    -0.0551    0.2650
GFR(CKD_EPI)       0.6919 -0.3534     0.6793    0.1469
BUN                0.1996 -0.2726     0.2051    0.1984
CrCl              -0.6916  0.1869    -0.6040    0.1724
------------------------------------------------------------
__________________________________________________________________________________________
[23/30] TSubset = MAITtrm
n = 22
obs_r = 0.2083
perm_p = 0.5235
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.0549 -2.3987    -0.0316    0.1787
GFR(CKD_EPI)      -0.6410 -0.3276    -0.6214    0.1400
CrCl               0.7568  0.2046     0.7051    0.0857
BUN               -0.1154 -0.1577    -0.1272    0.2561
------------------------------------------------------------
__________________________________________________________________________________________
[24/30] TSubset = GD1Ttrm
n = 16
obs_r = -0.3676
perm_p = 0.3327
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1     coef  cv_w_mean  cv_w_std
Cr                 0.5406  23.1394     0.4720    0.3458
GFR(CKD_EPI)       0.8034   0.4457     0.6604    0.3224
BUN               -0.1881  -0.2639    -0.1742    0.0698
CrCl               0.1642   0.0434     0.2276    0.3087
------------------------------------------------------------
__________________________________________________________________________________________
[25/30] TSubset = GD2Ttrm
n = 22
obs_r = -0.5777
perm_p = 0.0639
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.0579 -0.9639    -0.0412    0.5351
BUN               -0.5218 -0.2717    -0.3726    0.1716
GFR(CKD_EPI)       0.7664  0.1492     0.5519    0.2550
CrCl              -0.3701 -0.0381    -0.3042    0.4439
------------------------------------------------------------
__________________________________________________________________________________________
[26/30] TSubset = CD4grzk
n = 22
obs_r = -0.5422
perm_p = 0.0909
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.3749 -9.4074    -0.3139    0.3979
BUN                0.5895  0.4628     0.3987    0.3898
CrCl               0.7073  0.1098     0.5327    0.3043
GFR(CKD_EPI)      -0.1074 -0.0315     0.0023    0.4129
------------------------------------------------------------
__________________________________________________________________________________________
[27/30] TSubset = CD8grzk
n = 22
obs_r = -0.2690
perm_p = 0.4515
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.0366  0.8436    -0.0191    0.4477
BUN               -0.3675 -0.2647    -0.3757    0.2937
CrCl               0.8336  0.1188     0.6470    0.1505
GFR(CKD_EPI)      -0.4107 -0.1106    -0.3189    0.3367
------------------------------------------------------------
__________________________________________________________________________________________
[28/30] TSubset = MAITgrzK
n = 22
obs_r = 0.2309
perm_p = 0.4915
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1     coef  cv_w_mean  cv_w_std
Cr                -0.3333  16.5918    -0.2970    0.1251
CrCl               0.9391  -0.2893     0.8915    0.0559
GFR(CKD_EPI)      -0.0834   0.0486    -0.0788    0.2574
BUN               -0.0054   0.0084    -0.0045    0.2311
------------------------------------------------------------
__________________________________________________________________________________________
[29/30] TSubset = GD1TgrzK
n = 16
obs_r = -0.5547
perm_p = 0.0879
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1     coef  cv_w_mean  cv_w_std
Cr                 0.7904  15.0530     0.3349    0.5441
BUN               -0.2728  -0.1703    -0.1255    0.0980
GFR(CKD_EPI)       0.4041   0.0997     0.3797    0.5873
CrCl              -0.3709  -0.0436    -0.2000    0.4574
------------------------------------------------------------
__________________________________________________________________________________________
[30/30] TSubset = GD2TgrzK
n = 22
obs_r = -0.1073
perm_p = 0.7233
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1     coef  cv_w_mean  cv_w_std
Cr                -0.2917 -15.0000    -0.2320    0.2571
BUN                0.5361   0.8623     0.4986    0.1965
GFR(CKD_EPI)       0.7838   0.4714     0.6879    0.2551
CrCl              -0.1147  -0.0365    -0.1212    0.3039
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by permutation p-value)
__________________________________________________________________________________________
     y_col  n     r_obs   p_perm
   GD2Ttrm 22 -0.577717 0.063936
GD2T_3_PC1 22 -0.557951 0.068931
  GD1TgrzK 16 -0.554684 0.087912
   CD4grzk 22 -0.542216 0.090909
  GD2T_PC1 22 -0.510451 0.097902
GD2T_2_PC1 22 -0.454448 0.149850
  GD1T_PC1 16 -0.506579 0.158841
GD1T_1_PC1 16 -0.492671 0.175824
GD2T_1_PC1 22 -0.399637 0.200799
MAIT_1_PC1 22  0.346442 0.296703
   GD1Ttrm 16 -0.367562 0.332667
MAIT_3_PC1 22 -0.297237 0.382617
 CD8_3_PC1 22 -0.271450 0.431568
 CD4_3_PC1 22 -0.268072 0.432567
   CD8grzk 22 -0.268988 0.451548
  MAITgrzK 22  0.230894 0.491508
   MAITtrm 22  0.208329 0.523477
GD1T_3_PC1 16 -0.238636 0.525475
 CD8_2_PC1 22 -0.183106 0.590410
   CD8_PC1 22 -0.145543 0.680320
 CD4_1_PC1 22 -0.122455 0.710290
  GD2TgrzK 22 -0.107343 0.723277
 CD8_1_PC1 22 -0.105247 0.749251
  MAIT_PC1 22  0.088324 0.786214
    CD4trm 22 -0.049034 0.873127
MAIT_2_PC1 22 -0.044448 0.884116
 CD4_2_PC1 22 -0.039997 0.906094
   CD4_PC1 22 -0.014444 0.965035
    CD8trm 22 -0.009743 0.974026
GD1T_2_PC1 16 -0.008471 0.982018
__________________________________________________________________________________________

### 다시 해볼거 - trm grzk 묶은 조합만 남기고 + CV

In [72]:
sep = "_" * 90

X_cols = ['AST', 'ALT', 'ALP', 'Bilirubin', 'Protein', 'Albumin']

y_candidates = [
    'MAIT_1_PC1','GD2T_1_PC1', 'CD8_1_PC1', 'GD1T_1_PC1','CD4_1_PC1',
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환"""
    n = len(y)
    n_splits = min(n_splits, n)  # 안전
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def perm_pvalue_plsr_cv(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5,
                        n_perm=1000, random_state=42, statistic="abs_r"):
    """
    permutation p-value (CV 포함) 계산
    statistic:
      - "abs_r" : |corr(y, yhat_cv)|
      - "r2"    : corr(y, yhat_cv)^2
    """
    y = y.astype(float).to_numpy()
    y_pred = cv_pred_plsr(X, y, n_components=n_components, n_splits=n_splits, random_state=random_state)
    if y_pred is None:
        return np.nan, np.nan

    # 관측 통계량
    if np.std(y) < 1e-12 or np.std(y_pred) < 1e-12:
        r_obs = np.nan
        stat_obs = np.nan
    else:
        r_obs, _ = pearsonr(y, y_pred)
        stat_obs = abs(r_obs) if statistic == "abs_r" else (r_obs ** 2)

    if not np.isfinite(stat_obs):
        return r_obs, np.nan

    rng = np.random.default_rng(random_state)
    ge = 0

    # permutation: y를 셔플해서 CV를 다시 수행
    for _ in range(n_perm):
        y_perm = rng.permutation(y)
        y_perm_pred = cv_pred_plsr(X, y_perm, n_components=n_components, n_splits=n_splits, random_state=random_state)
        if y_perm_pred is None or np.std(y_perm_pred) < 1e-12:
            stat_perm = 0.0
        else:
            r_perm, _ = pearsonr(y_perm, y_perm_pred)
            stat_perm = abs(r_perm) if statistic == "abs_r" else (r_perm ** 2)

        if stat_perm >= stat_obs:
            ge += 1

    p_perm = (ge + 1) / (n_perm + 1)
    return r_obs, p_perm


def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등할 수 있어서, fold weight는 full-fit weight에 맞춰 부호 정렬합니다.
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    # x_weights_: (p, n_components), coef_: (p, 1)
    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    # 기준 방향(컴포넌트1만 정렬 기준으로 씀)
    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)  # (n_splits, p)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col]

    try:
        r_obs, p_perm = perm_pvalue_plsr_cv(
            X, y,
            n_components=1,
            n_splits=5,
            n_perm=1000,
            random_state=42,
            statistic="abs_r"  
        )

        print(f"obs_r = {r_obs:.4f}" if np.isfinite(r_obs) else "obs_r = NaN")
        print(f"perm_p = {p_perm:.4f}" if np.isfinite(p_perm) else "perm_p = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, y,
            n_components=1,
            n_splits=5,
            random_state=42
        )

        # 보기 좋게 합치기
        w_tbl = full_tbl.join(cv_tbl, how="left")

        # coef 절대값 기준 정렬 (기여 큰 순)
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_obs": r_obs, "p_perm": p_perm, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": f"FAIL: {type(e).__name__}"})

# 마지막 요약: permutation p-value 기준 정렬
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("p_perm", ascending=True, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by permutation p-value)")
print(sep)
print(res_ok[["y_col", "n", "r_obs", "p_perm"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/15] TSubset = MAIT_1_PC1
n = 12
obs_r = -0.8470
perm_p = 0.0030
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6533  0.2659     0.4946    0.2250
Protein         0.6918  0.2117     0.6519    0.0585
Bilirubin       0.0207  0.0131    -0.0164    0.1655
ALT            -0.2355 -0.0045    -0.0585    0.3227
AST             0.1256  0.0026     0.1834    0.1274
ALP             0.1512  0.0011     0.2591    0.2841
------------------------------------------------------------
__________________________________________________________________________________________
[2/15] TSubset = GD2T_1_PC1
n = 12
obs_r = -0.3416
perm_p = 0.4565
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6297 -0.5425     0.5024    0.1919
Albumin         0.4611 -0.5285     0.3314    0.2852
Bilirubin      -0.1944  0.3453    -0.2087    0.2350
ALT            -0.2313  0.0124    -0.2720    0.2279
ALP             0.5392 -0.0115     0.5006    0.1859
AST             0.0941 -0.0056     0.0723    0.2659
------------------------------------------------------------
__________________________________________________________________________________________
[3/15] TSubset = CD8_1_PC1
n = 12
obs_r = -0.7417
perm_p = 0.0190
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6612 -0.5082     0.5254    0.1906
Protein         0.5590 -0.3229     0.3388    0.4837
Bilirubin       0.0883 -0.1052     0.1203    0.2626
ALT            -0.4476  0.0161    -0.4030    0.1694
AST             0.1695 -0.0067     0.1541    0.1729
ALP            -0.1164  0.0017    -0.1372    0.2987
------------------------------------------------------------
__________________________________________________________________________________________
[4/15] TSubset = GD1T_1_PC1
n = 12
obs_r = 0.4220
perm_p = 0.3397
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6195 -0.6537     0.5737    0.0762
Protein         0.6274 -0.4977     0.5940    0.0324
Bilirubin       0.0592 -0.0968     0.0722    0.2855
AST             0.4447 -0.0243     0.4370    0.0980
ALT            -0.1461  0.0072    -0.1034    0.1304
ALP            -0.0067  0.0001    -0.0168    0.1536
------------------------------------------------------------
__________________________________________________________________________________________
[5/15] TSubset = CD4_1_PC1
n = 12
obs_r = -0.6603
perm_p = 0.0629
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6594 -0.3203     0.5178    0.1146
Protein         0.5061 -0.1848     0.2922    0.3940
Bilirubin       0.0367 -0.0276     0.0568    0.3421
ALT            -0.4901  0.0111    -0.4122    0.2992
AST             0.2467 -0.0062     0.2183    0.1832
ALP            -0.0819  0.0007    -0.0810    0.3398
------------------------------------------------------------
__________________________________________________________________________________________
[6/15] TSubset = CD4trm
n = 12
obs_r = -0.3849
perm_p = 0.3556
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6381 -4.8556     0.5512    0.0705
Protein         0.4336 -2.4800     0.2627    0.3682
Bilirubin       0.1556 -1.8352     0.1289    0.2905
ALT            -0.6164  0.2196    -0.5349    0.2344
AST            -0.0105  0.0041    -0.0063    0.1555
ALP            -0.0232  0.0033     0.0108    0.3182
------------------------------------------------------------
__________________________________________________________________________________________
[7/15] TSubset = CD8trm
n = 12
obs_r = -0.6169
perm_p = 0.1009
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.6215 -3.9907    -0.4336    0.2506
Protein        -0.3905 -1.8847    -0.1689    0.5352
Bilirubin      -0.1262 -1.2560    -0.0953    0.3144
ALT             0.6595  0.1983     0.4710    0.1983
AST             0.0585  0.0195     0.0302    0.2077
ALP             0.0835  0.0100     0.0072    0.3988
------------------------------------------------------------
__________________________________________________________________________________________
[8/15] TSubset = MAITtrm
n = 12
obs_r = -0.4407
perm_p = 0.3097
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.7467  10.8235     0.6009    0.2418
Albumin        -0.3994  -3.7354    -0.2773    0.3032
Protein        -0.3467  -2.4375    -0.1927    0.4212
ALT             0.3081   0.1349     0.2642    0.3081
AST            -0.0986  -0.0478    -0.0511    0.2142
ALP            -0.2410  -0.0420    -0.1980    0.2190
------------------------------------------------------------
__________________________________________________________________________________________
[9/15] TSubset = GD1Ttrm
n = 12
obs_r = -0.0088
perm_p = 0.9840
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6040 -6.1454     0.5535    0.0835
Albumin         0.4413 -5.9730     0.3807    0.1913
Bilirubin       0.2428 -5.0933     0.1671    0.3372
AST             0.4375 -0.3068     0.3738    0.1752
ALP             0.4306 -0.1087     0.3797    0.2012
ALT             0.0687 -0.0435     0.0602    0.2514
------------------------------------------------------------
__________________________________________________________________________________________
[10/15] TSubset = GD2Ttrm
n = 12
obs_r = -0.5446
perm_p = 0.1918
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6026 -8.7398     0.4446    0.2112
Albumin         0.3651 -7.0446     0.2234    0.3253
Bilirubin      -0.1015  3.0337    -0.1020    0.2697
ALP             0.6886 -0.2478     0.5976    0.2317
ALT            -0.1114  0.1007    -0.1616    0.2258
AST             0.0816 -0.0816     0.0633    0.3401
------------------------------------------------------------
__________________________________________________________________________________________
[11/15] TSubset = CD4grzk
n = 12
obs_r = -0.8173
perm_p = 0.0080
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.5275 -2.8586     0.3662    0.2001
Protein         0.5013 -2.0422     0.2837    0.3649
Bilirubin      -0.1768  1.4853    -0.0939    0.3209
AST             0.6254 -0.1756     0.5399    0.2241
ALT            -0.1480  0.0375    -0.1120    0.3378
ALP            -0.1618  0.0164    -0.1584    0.3447
------------------------------------------------------------
__________________________________________________________________________________________
[12/15] TSubset = CD8grzk
n = 12
obs_r = -0.5607
perm_p = 0.1648
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6515 -8.6534     0.5612    0.1434
Protein         0.6111 -6.1010     0.4464    0.3889
Bilirubin       0.0677 -1.3940     0.1117    0.1980
ALT            -0.3343  0.2079    -0.3174    0.1812
AST             0.2643 -0.1819     0.2451    0.1278
ALP            -0.1262  0.0313    -0.1624    0.3124
------------------------------------------------------------
__________________________________________________________________________________________
[13/15] TSubset = MAITgrzK
n = 12
obs_r = -0.7359
perm_p = 0.0400
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6122 -8.9069     0.5128    0.1875
Bilirubin      -0.3193  7.1988    -0.0830    0.4089
Protein         0.6143 -6.7183     0.6310    0.0549
ALT            -0.2939  0.2002    -0.1471    0.2460
AST             0.1274 -0.0961     0.1360    0.1426
ALP             0.2080 -0.0564     0.2214    0.1316
------------------------------------------------------------
__________________________________________________________________________________________
[14/15] TSubset = GD1TgrzK
n = 12
obs_r = 0.3711
perm_p = 0.3856
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.6362 -16.1261     0.6147    0.0352
Protein         0.5418 -10.3231     0.4910    0.1823
Bilirubin      -0.0702   2.7573    -0.0289    0.1686
AST             0.3780  -0.4964     0.3470    0.1521
ALT            -0.2628   0.3119    -0.2470    0.0718
ALP            -0.2912   0.1376    -0.2950    0.2203
------------------------------------------------------------
__________________________________________________________________________________________
[15/15] TSubset = GD2TgrzK
n = 12
obs_r = -0.1271
perm_p = 0.7812
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.5212 -10.2576     0.4167    0.2197
Protein         0.6257  -9.2577     0.5282    0.1830
Bilirubin      -0.2630   8.0232    -0.2929    0.2435
ALT            -0.3206   0.2954    -0.3439    0.1925
ALP             0.3934  -0.1444     0.3864    0.1729
AST             0.1005  -0.1025     0.0785    0.1637
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by permutation p-value)
__________________________________________________________________________________________
     y_col  n     r_obs   p_perm
MAIT_1_PC1 12 -0.846981 0.002997
   CD4grzk 12 -0.817328 0.007992
 CD8_1_PC1 12 -0.741683 0.018981
  MAITgrzK 12 -0.735946 0.039960
 CD4_1_PC1 12 -0.660257 0.062937
    CD8trm 12 -0.616897 0.100899
   CD8grzk 12 -0.560739 0.164835
   GD2Ttrm 12 -0.544572 0.191808
   MAITtrm 12 -0.440716 0.309690
GD1T_1_PC1 12  0.422010 0.339660
    CD4trm 12 -0.384944 0.355644
  GD1TgrzK 12  0.371081 0.385614
GD2T_1_PC1 12 -0.341579 0.456543
  GD2TgrzK 12 -0.127099 0.781219
   GD1Ttrm 12 -0.008848 0.984016
__________________________________________________________________________________________

In [93]:
sep = "_" * 90

X_cols = ['BUN', 'Cr']
y_candidates = [
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환"""
    n = len(y)
    n_splits = min(n_splits, n)  # 안전
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def perm_pvalue_plsr_cv(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5,
                        n_perm=1000, random_state=42, statistic="abs_r"):
    """
    permutation p-value (CV 포함) 계산
    statistic:
      - "abs_r" : |corr(y, yhat_cv)|
      - "r2"    : corr(y, yhat_cv)^2
    """
    y = y.astype(float).to_numpy()
    y_pred = cv_pred_plsr(X, y, n_components=n_components, n_splits=n_splits, random_state=random_state)
    if y_pred is None:
        return np.nan, np.nan

    # 관측 통계량
    if np.std(y) < 1e-12 or np.std(y_pred) < 1e-12:
        r_obs = np.nan
        stat_obs = np.nan
    else:
        r_obs, _ = pearsonr(y, y_pred)
        stat_obs = abs(r_obs) if statistic == "abs_r" else (r_obs ** 2)

    if not np.isfinite(stat_obs):
        return r_obs, np.nan

    rng = np.random.default_rng(random_state)
    ge = 0

    # permutation: y를 셔플해서 CV를 다시 수행
    for _ in range(n_perm):
        y_perm = rng.permutation(y)
        y_perm_pred = cv_pred_plsr(X, y_perm, n_components=n_components, n_splits=n_splits, random_state=random_state)
        if y_perm_pred is None or np.std(y_perm_pred) < 1e-12:
            stat_perm = 0.0
        else:
            r_perm, _ = pearsonr(y_perm, y_perm_pred)
            stat_perm = abs(r_perm) if statistic == "abs_r" else (r_perm ** 2)

        if stat_perm >= stat_obs:
            ge += 1

    p_perm = (ge + 1) / (n_perm + 1)
    return r_obs, p_perm


def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등할 수 있어서, fold weight는 full-fit weight에 맞춰 부호 정렬합니다.
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    # x_weights_: (p, n_components), coef_: (p, 1)
    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    # 기준 방향(컴포넌트1만 정렬 기준으로 씀)
    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)  # (n_splits, p)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col]

    try:
        r_obs, p_perm = perm_pvalue_plsr_cv(
            X, y,
            n_components=1,
            n_splits=5,
            n_perm=1000,
            random_state=42,
            statistic="abs_r"  
        )

        print(f"obs_r = {r_obs:.4f}" if np.isfinite(r_obs) else "obs_r = NaN")
        print(f"perm_p = {p_perm:.4f}" if np.isfinite(p_perm) else "perm_p = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, y,
            n_components=1,
            n_splits=5,
            random_state=42
        )

        # 보기 좋게 합치기
        w_tbl = full_tbl.join(cv_tbl, how="left")

        # coef 절대값 기준 정렬 (기여 큰 순)
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_obs": r_obs, "p_perm": p_perm, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_obs": np.nan, "p_perm": np.nan, "status": f"FAIL: {type(e).__name__}"})

# 마지막 요약: permutation p-value 기준 정렬
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("p_perm", ascending=True, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by permutation p-value)")
print(sep)
print(res_ok[["y_col", "n", "r_obs", "p_perm"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 13
obs_r = -0.0588
perm_p = 0.9011
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr         0.895 -30.6042     0.8487    0.1818
BUN       -0.446   1.3016    -0.4460    0.2605
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 13
obs_r = -0.1508
perm_p = 0.7562
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9579 -31.2569     0.9554    0.0223
BUN      -0.2870   0.7991    -0.2868    0.0755
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 13

KeyboardInterrupt:

In [78]:
df.columns

Index(['ID', 'Sex', 'Age', 'BMI', 'AST', 'ALT', 'ALP', 'Bilirubin', 'Protein',
       'Albumin', 'PT', 'APTT', 'Cholesterol', 'TG', 'LDL', 'HDL', 'R_Glucose',
       'F_Glucose', 'HbA1c', 'BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl', 'Amylase',
       'CRP', 'B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T', 'NKT2', 'MAIT', 'gd1T',
       'gd2T', 'ConvT%', 'CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg', 'CD20T',
       'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm', 'CD4grzk',
       'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK', 'Transitional B',
       'Memory B', 'Early Plasma B ', 'Plasma B', 'ABC', 'CD11c+CD206-',
       'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1',
       'Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4', 'Gulucose', 'Sex_01',
       'CD8_PC1', 'CD8_1_PC1', 'CD8_2_PC1', 'CD8_3_PC1', 'CD4_PC1',
       'CD4_1_PC1', 'CD4_2_PC1', 'CD4_3_PC1', 'MAIT_PC1', 'MAIT_1_PC1',
       'MAIT_2_PC1', 'MAIT_3_PC1', 'GD1T_PC1', 'GD1T_1_PC1', 'GD1T_2_PC1',
       'GD1T_3_PC1', 'GD2T_PC1', 'GD2T_1_PC1', 'GD2T_2_PC1', 'GD2T_3_PC1'],
      dtype='object')

In [79]:
# df2 + 간 - 안나와야댐
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

# =========================
# df2 간(liver)
# =========================
X_cols = ['AST', 'ALT', 'ALP', 'Bilirubin', 'Albumin', 'PT', 'APTT']

y_candidates = [ 'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등 → fold weight는 full-fit weight에 맞춰 부호 정렬
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df2.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, pd.Series(y, index=df_xy.index),
            n_components=1,
            n_splits=5,
            random_state=42
        )

        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


# 마지막 요약: CV Q2 기준 정렬(내림차순)
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 22
r_cv   = 0.2493
Q2     = -0.0183
RMSECV = 15.8088
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.3585  9.2093     0.3433    0.1365
Albumin         0.1280  2.3950     0.1126    0.0689
APTT           -0.5931 -1.3407    -0.5558    0.0662
PT              0.6429  0.3793     0.6155    0.0616
AST             0.1596  0.2396     0.1349    0.2448
ALP            -0.2430 -0.0904    -0.2399    0.1239
ALT            -0.0745 -0.0831    -0.0956    0.1191
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 22
r_cv   = 0.1120
Q2     = -0.0769
RMSECV = 19.0989
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.4859  9.8589     0.4394    0.1651
Albumin         0.2714  4.0091     0.2751    0.1020
APTT           -0.4794 -0.8559    -0.4302    0.1192
ALT             0.3715  0.3273     0.3645    0.1259
PT              0.5553  0.2588     0.5192    0.0662
AST             0.1181  0.1400     0.1070    0.2888
ALP            -0.0090 -0.0027    -0.0174    0.0976
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 22
r_cv   = 0.1625
Q2     = -0.1261
RMSECV = 16.3475
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.4945  12.8947     0.4390    0.1366
APTT           -0.5318  -1.2202    -0.4649    0.1465
Albumin        -0.0601  -1.1407    -0.0738    0.1128
PT              0.6468   0.3874     0.6048    0.0647
ALT            -0.1339  -0.1516    -0.1399    0.0927
ALP            -0.1811  -0.0684    -0.1761    0.2831
AST             0.0007   0.0010     0.0006    0.2568
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 16
r_cv   = 0.0335
Q2     = -0.3062
RMSECV = 15.8042
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.2657  7.0324    -0.2589    0.1225
Bilirubin       0.1732 -4.6837     0.1444    0.1088
APTT           -0.4266  0.9884    -0.3872    0.0716
PT              0.7538 -0.5311     0.6807    0.0885
ALT            -0.3792  0.4414    -0.3652    0.1990
AST            -0.0682  0.1044    -0.1050    0.2224
ALP             0.0259 -0.0133     0.0139    0.2530
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 22
r_cv   = 0.2259
Q2     = -0.0702
RMSECV = 14.7225
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.6424  10.6543     0.6037    0.0968
Bilirubin       0.1703   3.8780     0.1316    0.2500
ALT             0.4946   0.4892     0.4858    0.1265
PT              0.5098   0.2667     0.4400    0.1987
APTT           -0.1177  -0.2359    -0.1029    0.1517
AST             0.1113   0.1481     0.1160    0.0919
ALP             0.1662   0.0548     0.1598    0.1223
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 22
r_cv   = -0.1173
Q2     = -0.3505
RMSECV = 16.5720
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.1542 -4.5815     0.1334    0.2634
Albumin        -0.1095  2.3698    -0.1126    0.1203
APTT            0.7994 -2.0901     0.6996    0.0987
ALT             0.5038 -0.6500     0.4197    0.2945
AST             0.1161 -0.2016     0.1226    0.0736
PT             -0.1837  0.1254    -0.1490    0.1974
ALP             0.1552 -0.0668     0.1142    0.3037
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 22
r_cv   = 0.0303
Q2     = -0.0771
RMSECV = 14.3633
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.4422  6.1520    -0.3964    0.1587
Albumin        -0.2516  2.5490    -0.2103    0.2259
APTT            0.5649 -0.6915     0.5515    0.1556
ALT            -0.4599  0.2778    -0.4383    0.1142
PT             -0.4467  0.1427    -0.3335    0.2255
ALP             0.1026 -0.0207     0.1175    0.1439
AST             0.0230 -0.0187     0.0055    0.1914
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 22
r_cv   = 0.1417
Q2     = -0.0938
RMSECV = 14.6118
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.3189 -7.4164     0.2890    0.0731
Albumin         0.1225 -2.0744     0.0915    0.2013
APTT           -0.3091  0.6325    -0.2657    0.1370
PT              0.7309 -0.3904     0.6718    0.0612
AST             0.1834 -0.2492     0.1489    0.1902
ALT             0.1880 -0.1899     0.1496    0.2184
ALP            -0.4296  0.1447    -0.3987    0.2756
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 16
r_cv   = -0.4771
Q2     = -1.2483
RMSECV = 38.8108
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.0939 -4.8812     0.0490    0.1668
PT              0.8660 -1.1981     0.6679    0.1333
ALT            -0.3102  0.7091    -0.2232    0.3282
ALP            -0.3777  0.3806    -0.2616    0.4317
Bilirubin       0.0050 -0.2678    -0.0308    0.1649
AST             0.0477 -0.1433    -0.0009    0.2316
APTT            0.0093 -0.0425     0.0437    0.3427
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 22
r_cv   = 0.4759
Q2     = 0.1870
RMSECV = 18.6487
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.7547  25.2671     0.7264    0.0756
Bilirubin       0.1167   5.3645     0.1173    0.1187
ALT             0.2822   0.5634     0.2679    0.0573
AST             0.1272   0.3418     0.1333    0.1564
PT              0.3177   0.3355     0.2904    0.1500
ALP             0.4691   0.3125     0.4503    0.1361
APTT            0.0091   0.0368     0.0044    0.1175
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
GD2TgrzK 22  0.475898  0.187046 18.648695
  CD4trm 22  0.249337 -0.018309 15.808807
 GD2Ttrm 22  0.225870 -0.070191 14.722526
  CD8trm 22  0.112011 -0.076950 19.098855
 CD8grzk 22  0.030273 -0.077148 14.363322
MAITgrzK 22  0.141680 -0.093767 14.611821
 MAITtrm 22  0.162482 -0.126069 16.347494
 GD1Ttrm 16  0.033537 -0.306196 15.804185
 CD4grzk 22 -0.117302 -0.350488 16.571996
GD1TgrzK 16 -0.477141 -1.248290 38.810838
__________________________________________________________________________________________

In [91]:
df2.columns

Index(['ID', 'Sex', 'Age', 'BMI', 'AST', 'ALT', 'ALP', 'Bilirubin', 'Protein',
       'Albumin', 'PT', 'APTT', 'Cholesterol', 'TG', 'LDL', 'HDL', 'R_Glucose',
       'F_Glucose', 'HbA1c', 'BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl', 'Amylase',
       'CRP', 'B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T', 'NKT2', 'MAIT', 'gd1T',
       'gd2T', 'ConvT%', 'CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg', 'CD20T',
       'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm', 'CD4grzk',
       'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK', 'Transitional B',
       'Memory B', 'Early Plasma B ', 'Plasma B', 'ABC', 'CD11c+CD206-',
       'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1',
       'Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4', 'Gulucose', 'Sex_01',
       'CD8_PC1', 'CD8_1_PC1', 'CD8_2_PC1', 'CD8_3_PC1', 'CD4_PC1',
       'CD4_1_PC1', 'CD4_2_PC1', 'CD4_3_PC1', 'MAIT_PC1', 'MAIT_1_PC1',
       'MAIT_2_PC1', 'MAIT_3_PC1', 'GD1T_PC1', 'GD1T_1_PC1', 'GD1T_2_PC1',
       'GD1T_3_PC1', 'GD2T_PC1', 'GD2T_1_PC1', 'GD2T_2_PC1', 'GD2T_3_PC1'],
      dtype='object')

In [92]:
# df2 +신장 cv

import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

X_cols = [ 'BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl']

y_candidates = [ 'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]


def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 인덱스 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)

    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))

    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    """
    import statsmodels.api as sm  # 혹시 안 쓰면 삭제해도 됨 (여기선 사용 안 함)

    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()

        # 부호 정렬
        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 성능 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df2.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(X, pd.Series(y, index=df_xy.index), n_components=1, n_splits=5, random_state=42)
        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 22
r_cv   = -0.0490
Q2     = -0.1893
RMSECV = 17.0846
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.2283  7.1559    -0.2674    0.3379
GFR(CKD_EPI)       0.8199 -0.3006     0.7399    0.1168
BUN               -0.2327  0.2282    -0.1941    0.2451
CrCl              -0.4706  0.0913    -0.4075    0.1838
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 22
r_cv   = -0.0097
Q2     = -0.2825
RMSECV = 20.8421
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.0558  2.4360    -0.0551    0.2650
GFR(CKD_EPI)       0.6919 -0.3534     0.6793    0.1469
BUN                0.1996 -0.2726     0.2051    0.1984
CrCl              -0.6916  0.1869    -0.6040    0.1724
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 22
r_cv   = 0.2083
Q2     = -0.0186
RMSECV = 15.5482
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.0549 -2.3987    -0.0316    0.1787
GFR(CKD_EPI)      -0.6410 -0.3276    -0.6214    0.1400
CrCl               0.7568  0.2046     0.7051    0.0857
BUN               -0.1154 -0.1577    -0.1272    0.2561
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 16
r_cv   = -0.3676
Q2     = -0.6487
RMSECV = 17.7560
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1     coef  cv_w_mean  cv_w_std
Cr                 0.5406  23.1394     0.4720    0.3458
GFR(CKD_EPI)       0.8034   0.4457     0.6604    0.3224
BUN               -0.1881  -0.2639    -0.1742    0.0698
CrCl               0.1642   0.0434     0.2276    0.3087
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 22
r_cv   = -0.5777
Q2     = -0.7651
RMSECV = 18.9076
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.0579 -0.9639    -0.0412    0.5351
BUN               -0.5218 -0.2717    -0.3726    0.1716
GFR(CKD_EPI)       0.7664  0.1492     0.5519    0.2550
CrCl              -0.3701 -0.0381    -0.3042    0.4439
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 22
r_cv   = -0.5422
Q2     = -0.6626
RMSECV = 18.3877
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                -0.3749 -9.4074    -0.3139    0.3979
BUN                0.5895  0.4628     0.3987    0.3898
CrCl               0.7073  0.1098     0.5327    0.3043
GFR(CKD_EPI)      -0.1074 -0.0315     0.0023    0.4129
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 22
r_cv   = -0.2690
Q2     = -0.4627
RMSECV = 16.7376
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1    coef  cv_w_mean  cv_w_std
Cr                 0.0366  0.8436    -0.0191    0.4477
BUN               -0.3675 -0.2647    -0.3757    0.2937
CrCl               0.8336  0.1188     0.6470    0.1505
GFR(CKD_EPI)      -0.4107 -0.1106    -0.3189    0.3367
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 22
r_cv   = 0.2309
Q2     = -0.0107
RMSECV = 14.0457
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1     coef  cv_w_mean  cv_w_std
Cr                -0.3333  16.5918    -0.2970    0.1251
CrCl               0.9391  -0.2893     0.8915    0.0559
GFR(CKD_EPI)      -0.0834   0.0486    -0.0788    0.2574
BUN               -0.0054   0.0084    -0.0045    0.2311
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 16
r_cv   = -0.5547
Q2     = -1.0959
RMSECV = 37.4724
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1     coef  cv_w_mean  cv_w_std
Cr                 0.7904  15.0530     0.3349    0.5441
BUN               -0.2728  -0.1703    -0.1255    0.0980
GFR(CKD_EPI)       0.4041   0.0997     0.3797    0.5873
CrCl              -0.3709  -0.0436    -0.2000    0.4574
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 22
r_cv   = -0.1073
Q2     = -0.2251
RMSECV = 22.8932
------------------------------------------------------------
PLSR Weights / Coefs
              x_weight_c1     coef  cv_w_mean  cv_w_std
Cr                -0.2917 -15.0000    -0.2320    0.2571
BUN                0.5361   0.8623     0.4986    0.1965
GFR(CKD_EPI)       0.7838   0.4714     0.6879    0.2551
CrCl              -0.1147  -0.0365    -0.1212    0.3039
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
MAITgrzK 22  0.230894 -0.010657 14.045710
 MAITtrm 22  0.208329 -0.018649 15.548231
  CD4trm 22 -0.049034 -0.189301 17.084619
GD2TgrzK 22 -0.107343 -0.225129 22.893191
  CD8trm 22 -0.009743 -0.282519 20.842098
 CD8grzk 22 -0.268988 -0.462694 16.737634
 GD1Ttrm 16 -0.367562 -0.648750 17.756006
 CD4grzk 22 -0.542216 -0.662631 18.387702
 GD2Ttrm 22 -0.577717 -0.765108 18.907637
GD1TgrzK 16 -0.554684 -1.095894 37.472401
__________________________________________________________________________________________

In [94]:
# df1 + 신장
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

X_cols = ['BUN', 'Cr']
y_candidates = [
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 인덱스 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)

    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))

    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    """
    import statsmodels.api as sm  # 혹시 안 쓰면 삭제해도 됨 (여기선 사용 안 함)

    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()

        # 부호 정렬
        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 성능 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(X, pd.Series(y, index=df_xy.index), n_components=1, n_splits=5, random_state=42)
        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 13
r_cv   = -0.0588
Q2     = -0.3979
RMSECV = 19.9140
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr         0.895 -30.6042     0.8487    0.1818
BUN       -0.446   1.3016    -0.4460    0.2605
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 13
r_cv   = -0.1508
Q2     = -0.4136
RMSECV = 20.6309
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9579 -31.2569     0.9554    0.0223
BUN      -0.2870   0.7991    -0.2868    0.0755
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 13
r_cv   = -0.2476
Q2     = -0.1992
RMSECV = 17.8190
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.1665 -3.6935    -0.2586    0.3856
BUN       0.9860  1.8671     0.8819    0.2133
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 13
r_cv   = -0.4189
Q2     = -0.9793
RMSECV = 24.7220
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.3706 -4.2501    -0.0117    0.7551
BUN       0.9288  0.9090     0.7220    0.1675
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 13
r_cv   = -0.5374
Q2     = -0.5074
RMSECV = 39.2759
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9721 -20.2947     0.8527    0.1064
BUN      -0.2347   0.4182    -0.3096    0.4583
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 13
r_cv   = 0.0572
Q2     = -0.3462
RMSECV = 11.6865
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.6709 -18.0451    -0.6619    0.3419
BUN       0.7415   1.7020     0.6299    0.2991
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 13
r_cv   = 0.1687
Q2     = -0.3429
RMSECV = 22.6532
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.6434 -38.7330    -0.6380    0.3078
BUN       0.7655   3.9329     0.6932    0.2141
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 13
r_cv   = -0.1193
Q2     = -0.2739
RMSECV = 19.8466
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9968 -30.7096     0.8725    0.1818
BUN      -0.0799   0.2099    -0.0739    0.5085
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 13
r_cv   = -0.1495
Q2     = -0.9246
RMSECV = 31.6419
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.8139 -54.9307     0.7650    0.2071
BUN      -0.5810   3.3459    -0.5065    0.3935
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 13
r_cv   = -0.2055
Q2     = -0.1434
RMSECV = 28.0151
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.3881 -14.3776    -0.4558    0.3868
BUN       0.9216   2.9137     0.7809    0.2801
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
GD2TgrzK 13 -0.205484 -0.143379 28.015051
 MAITtrm 13 -0.247577 -0.199216 17.818984
MAITgrzK 13 -0.119338 -0.273944 19.846581
 CD8grzk 13  0.168738 -0.342857 22.653206
 CD4grzk 13  0.057153 -0.346225 11.686476
  CD4trm 13 -0.058824 -0.397920 19.914003
  CD8trm 13 -0.150848 -0.413583 20.630931
 GD2Ttrm 13 -0.537411 -0.507443 39.275902
GD1TgrzK 13 -0.149550 -0.924636 31.641932
 GD1Ttrm 13 -0.418890 -0.979299 24.721986
__________________________________________________________________________________________

In [95]:
# df1 + 간
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

X_cols =  ['AST', 'ALT', 'ALP', 'Bilirubin', 'Protein', 'Albumin']
y_candidates = [
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 인덱스 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)

    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))

    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    """
    import statsmodels.api as sm  # 혹시 안 쓰면 삭제해도 됨 (여기선 사용 안 함)

    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()

        # 부호 정렬
        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 성능 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(X, pd.Series(y, index=df_xy.index), n_components=1, n_splits=5, random_state=42)
        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 12
r_cv   = -0.3849
Q2     = -0.4430
RMSECV = 20.9134
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6381 -4.8556     0.5512    0.0705
Protein         0.4336 -2.4800     0.2627    0.3682
Bilirubin       0.1556 -1.8352     0.1289    0.2905
ALT            -0.6164  0.2196    -0.5349    0.2344
AST            -0.0105  0.0041    -0.0063    0.1555
ALP            -0.0232  0.0033     0.0108    0.3182
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 12
r_cv   = -0.6169
Q2     = -1.3436
RMSECV = 27.6238
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin        -0.6215 -3.9907    -0.4336    0.2506
Protein        -0.3905 -1.8847    -0.1689    0.5352
Bilirubin      -0.1262 -1.2560    -0.0953    0.3144
ALT             0.6595  0.1983     0.4710    0.1983
AST             0.0585  0.0195     0.0302    0.2077
ALP             0.0835  0.0100     0.0072    0.3988
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 12
r_cv   = -0.4407
Q2     = -1.5384
RMSECV = 24.8775
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.7467  10.8235     0.6009    0.2418
Albumin        -0.3994  -3.7354    -0.2773    0.3032
Protein        -0.3467  -2.4375    -0.1927    0.4212
ALT             0.3081   0.1349     0.2642    0.3081
AST            -0.0986  -0.0478    -0.0511    0.2142
ALP            -0.2410  -0.0420    -0.1980    0.2190
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 12
r_cv   = -0.0088
Q2     = -0.9126
RMSECV = 24.4258
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6040 -6.1454     0.5535    0.0835
Albumin         0.4413 -5.9730     0.3807    0.1913
Bilirubin       0.2428 -5.0933     0.1671    0.3372
AST             0.4375 -0.3068     0.3738    0.1752
ALP             0.4306 -0.1087     0.3797    0.2012
ALT             0.0687 -0.0435     0.0602    0.2514
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 12
r_cv   = -0.5446
Q2     = -0.7361
RMSECV = 42.6305
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Protein         0.6026 -8.7398     0.4446    0.2112
Albumin         0.3651 -7.0446     0.2234    0.3253
Bilirubin      -0.1015  3.0337    -0.1020    0.2697
ALP             0.6886 -0.2478     0.5976    0.2317
ALT            -0.1114  0.1007    -0.1616    0.2258
AST             0.0816 -0.0816     0.0633    0.3401
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 12
r_cv   = -0.8173
Q2     = -1.1260
RMSECV = 14.4275
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.5275 -2.8586     0.3662    0.2001
Protein         0.5013 -2.0422     0.2837    0.3649
Bilirubin      -0.1768  1.4853    -0.0939    0.3209
AST             0.6254 -0.1756     0.5399    0.2241
ALT            -0.1480  0.0375    -0.1120    0.3378
ALP            -0.1618  0.0164    -0.1584    0.3447
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 12
r_cv   = -0.5607
Q2     = -0.7048
RMSECV = 23.4762
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6515 -8.6534     0.5612    0.1434
Protein         0.6111 -6.1010     0.4464    0.3889
Bilirubin       0.0677 -1.3940     0.1117    0.1980
ALT            -0.3343  0.2079    -0.3174    0.1812
AST             0.2643 -0.1819     0.2451    0.1278
ALP            -0.1262  0.0313    -0.1624    0.3124
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 12
r_cv   = -0.7359
Q2     = -2.7116
RMSECV = 34.0893
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin         0.6122 -8.9069     0.5128    0.1875
Bilirubin      -0.3193  7.1988    -0.0830    0.4089
Protein         0.6143 -6.7183     0.6310    0.0549
ALT            -0.2939  0.2002    -0.1471    0.2460
AST             0.1274 -0.0961     0.1360    0.1426
ALP             0.2080 -0.0564     0.2214    0.1316
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 12
r_cv   = 0.3711
Q2     = -0.0286
RMSECV = 24.0693
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.6362 -16.1261     0.6147    0.0352
Protein         0.5418 -10.3231     0.4910    0.1823
Bilirubin      -0.0702   2.7573    -0.0289    0.1686
AST             0.3780  -0.4964     0.3470    0.1521
ALT            -0.2628   0.3119    -0.2470    0.0718
ALP            -0.2912   0.1376    -0.2950    0.2203
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 12
r_cv   = -0.1271
Q2     = -0.2794
RMSECV = 30.8386
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin         0.5212 -10.2576     0.4167    0.2197
Protein         0.6257  -9.2577     0.5282    0.1830
Bilirubin      -0.2630   8.0232    -0.2929    0.2435
ALT            -0.3206   0.2954    -0.3439    0.1925
ALP             0.3934  -0.1444     0.3864    0.1729
AST             0.1005  -0.1025     0.0785    0.1637
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
GD1TgrzK 12  0.371081 -0.028568 24.069255
GD2TgrzK 12 -0.127099 -0.279431 30.838630
  CD4trm 12 -0.384944 -0.442974 20.913367
 CD8grzk 12 -0.560739 -0.704849 23.476170
 GD2Ttrm 12 -0.544572 -0.736120 42.630495
 GD1Ttrm 12 -0.008848 -0.912638 24.425803
 CD4grzk 12 -0.817328 -1.125956 14.427482
  CD8trm 12 -0.616897 -1.343571 27.623813
 MAITtrm 12 -0.440716 -1.538419 24.877498
MAITgrzK 12 -0.735946 -2.711634 34.089270
__________________________________________________________________________________________

### PLSR X cols나눠서 해보깅. . .

In [26]:

# df 2 1번간

# df2 + 간 - 안나와야댐
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

# =========================
# df2 간(liver)
# =========================
X_cols = ['AST', 'ALT', 'ALP', 'Bilirubin', 'PT', 'APTT']

y_candidates = [ 'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등 → fold weight는 full-fit weight에 맞춰 부호 정렬
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df2.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, pd.Series(y, index=df_xy.index),
            n_components=1,
            n_splits=5,
            random_state=42
        )

        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


# 마지막 요약: CV Q2 기준 정렬(내림차순)
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 22
r_cv   = 0.2585
Q2     = -0.0072
RMSECV = 15.7220
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.3615  9.5052     0.3464    0.1375
APTT           -0.5980 -1.3838    -0.5607    0.0689
PT              0.6482  0.3915     0.6207    0.0625
AST             0.1610  0.2473     0.1360    0.2460
ALP            -0.2450 -0.0933    -0.2418    0.1240
ALT            -0.0751 -0.0858    -0.0959    0.1192
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 22
r_cv   = 0.0897
Q2     = -0.0822
RMSECV = 19.1455
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.5049  10.2151     0.4590    0.1709
APTT           -0.4981  -0.8869    -0.4486    0.1167
ALT             0.3860   0.3391     0.3808    0.1292
PT              0.5770   0.2681     0.5439    0.0788
AST             0.1227   0.1450     0.1088    0.3047
ALP            -0.0094  -0.0028    -0.0180    0.1019
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 22
r_cv   = 0.1626
Q2     = -0.1410
RMSECV = 16.4554
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.4954  12.6290     0.4413    0.1343
APTT           -0.5327  -1.1951    -0.4675    0.1443
PT              0.6480   0.3794     0.6102    0.0709
ALT            -0.1342  -0.1485    -0.1413    0.0937
ALP            -0.1814  -0.0670    -0.1794    0.2875
AST             0.0007   0.0010     0.0023    0.2599
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 16
r_cv   = 0.0295
Q2     = -0.2585
RMSECV = 15.5132
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.1797 -4.4040     0.1523    0.1178
APTT           -0.4425  0.9293    -0.4038    0.0746
PT              0.7819 -0.4994     0.7089    0.0832
ALT            -0.3934  0.4151    -0.3796    0.2037
AST            -0.0708  0.0981    -0.1127    0.2331
ALP             0.0269 -0.0125     0.0131    0.2659
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 22
r_cv   = 0.0141
Q2     = -0.2941
RMSECV = 16.1897
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.2222  3.9098     0.1648    0.3088
ALT             0.6454  0.4932     0.6106    0.1299
PT              0.6652  0.2689     0.5641    0.2639
APTT           -0.1536 -0.2378    -0.1241    0.1820
AST             0.1452  0.1494     0.1391    0.1148
ALP             0.2169  0.0553     0.2106    0.1587
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 22
r_cv   = -0.1040
Q2     = -0.3466
RMSECV = 16.5484
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.1551 -4.5470     0.1314    0.2675
APTT            0.8043 -2.0743     0.7092    0.1060
ALT             0.5069 -0.6451     0.4215    0.2983
AST             0.1168 -0.2001     0.1246    0.0755
PT             -0.1848  0.1244    -0.1519    0.1989
ALP             0.1561 -0.0663     0.1121    0.3107
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 22
r_cv   = 0.0842
Q2     = -0.0468
RMSECV = 14.1594
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.4569  6.3768    -0.4187    0.1738
APTT            0.5836 -0.7168     0.5732    0.1408
ALT            -0.4752  0.2880    -0.4598    0.1182
PT             -0.4615  0.1480    -0.3534    0.2377
ALP             0.1060 -0.0214     0.1215    0.1445
AST             0.0238 -0.0194     0.0125    0.1994
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 22
r_cv   = 0.2054
Q2     = -0.0487
RMSECV = 14.3074
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.3213 -7.7464     0.2953    0.0746
APTT           -0.3114  0.6607    -0.2730    0.1441
PT              0.7364 -0.4078     0.6858    0.0574
AST             0.1848 -0.2603     0.1535    0.1966
ALT             0.1894 -0.1983     0.1539    0.2265
ALP            -0.4329  0.1512    -0.4034    0.2790
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 16
r_cv   = -0.4334
Q2     = -1.2526
RMSECV = 38.8482
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
PT              0.8698 -1.2620     0.6773    0.1409
ALT            -0.3116  0.7470    -0.2235    0.3326
ALP            -0.3794  0.4009    -0.2617    0.4380
Bilirubin       0.0051 -0.2821    -0.0299    0.1660
AST             0.0479 -0.1509     0.0003    0.2329
APTT            0.0094 -0.0448     0.0449    0.3477
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 22
r_cv   = 0.0864
Q2     = -0.2428
RMSECV = 23.0581
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin       0.1778  5.1826     0.1670    0.1644
ALT             0.4301  0.5443     0.3928    0.0614
AST             0.1939  0.3302     0.1796    0.2001
PT              0.4842  0.3241     0.4318    0.2207
ALP             0.7150  0.3019     0.6700    0.2081
APTT            0.0139  0.0356     0.0157    0.1569
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
  CD4trm 22  0.258510 -0.007161 15.722039
 CD8grzk 22  0.084196 -0.046779 14.159398
MAITgrzK 22  0.205446 -0.048669 14.307409
  CD8trm 22  0.089745 -0.082216 19.145491
 MAITtrm 22  0.162554 -0.140986 16.455413
GD2TgrzK 22  0.086392 -0.242846 23.058127
 GD1Ttrm 16  0.029476 -0.258533 15.513160
 GD2Ttrm 22  0.014061 -0.294112 16.189654
 CD4grzk 22 -0.103958 -0.346647 16.548414
GD1TgrzK 16 -0.433372 -1.252622 38.848210
__________________________________________________________________________________________

In [ ]:
# df2 + 간 - 안나와야댐 -2번 간
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

# =========================
# df2 간(liver)
# =========================
X_cols = ['Albumin']

y_candidates = [ 'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등 → fold weight는 full-fit weight에 맞춰 부호 정렬
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df2.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, pd.Series(y, index=df_xy.index),
            n_components=1,
            n_splits=5,
            random_state=42
        )

        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


# 마지막 요약: CV Q2 기준 정렬(내림차순)
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 22
r_cv   = 0.3648
Q2     = 0.1017
RMSECV = 14.8483
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1   coef  cv_w_mean  cv_w_std
APTT      -0.6781 -1.753    -0.6675    0.0731
PT         0.7350  0.496     0.7392    0.0677
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 22
r_cv   = 0.1737
Q2     = -0.0244
RMSECV = 18.6269
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
APTT      -0.6535 -1.4801    -0.6247    0.1028
PT         0.7569  0.4475     0.7707    0.0954
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 22
r_cv   = 0.3583
Q2     = 0.0788
RMSECV = 14.7856
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
APTT      -0.6351 -1.5037    -0.5936    0.1612
PT         0.7724  0.4774     0.7851    0.1142
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 16
r_cv   = 0.2470
Q2     = 0.0317
RMSECV = 13.6073
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
APTT      -0.4925  0.8413    -0.4930    0.0519
PT         0.8703 -0.4520     0.8684    0.0285
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 22
r_cv   = -0.0142
Q2     = -0.2094
RMSECV = 15.6505
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
PT         0.9744  0.4773     0.8793    0.1537
APTT      -0.2249 -0.4221    -0.0713    0.5035
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 22
r_cv   = 0.2257
Q2     = 0.0451
RMSECV = 13.9354
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
APTT       0.9746 -1.5943     0.9508    0.0115
PT        -0.2240  0.0956    -0.1822    0.2798
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 22
r_cv   = 0.0548
Q2     = -0.0491
RMSECV = 14.1753
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
APTT       0.7844 -1.0510     0.7977    0.1575
PT        -0.6203  0.2169    -0.5025    0.3378
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 22
r_cv   = 0.3971
Q2     = 0.1522
RMSECV = 12.8646
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
APTT      -0.3895  0.8507    -0.3606    0.1830
PT         0.9210 -0.5251     0.9162    0.0686
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 16
r_cv   = -0.0396
Q2     = -0.4243
RMSECV = 30.8908
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
PT         0.9999 -1.1459     0.9097    0.0769
APTT       0.0108 -0.0407     0.0972    0.4448
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 22
r_cv   = -0.0708
Q2     = -0.1558
RMSECV = 22.2359
------------------------------------------------------------
PLSR Weights / Coefs
      x_weight_c1    coef  cv_w_mean  cv_w_std
PT         0.9996  0.6354     0.9018    0.1299
APTT       0.0286  0.0697     0.1267    0.4432
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
MAITgrzK 22  0.397146  0.152165 12.864636
  CD4trm 22  0.364833  0.101670 14.848324
 MAITtrm 22  0.358280  0.078833 14.785557
 CD4grzk 22  0.225662  0.045055 13.935374
 GD1Ttrm 16  0.246995  0.031706 13.607287
  CD8trm 22  0.173690 -0.024384 18.626916
 CD8grzk 22  0.054837 -0.049127 14.175268
GD2TgrzK 22 -0.070814 -0.155792 22.235929
 GD2Ttrm 22 -0.014198 -0.209358 15.650531
GD1TgrzK 16 -0.039590 -0.424314 30.890839
__________________________________________________________________________________________

In [27]:
df1.columns

Index(['ID', 'Sex', 'Age', 'BMI', 'AST', 'ALT', 'ALP', 'Bilirubin', 'Protein',
       'Albumin', 'PT', 'APTT', 'Cholesterol', 'TG', 'LDL', 'HDL', 'R_Glucose',
       'F_Glucose', 'HbA1c', 'BUN', 'Cr', 'GFR(CKD_EPI)', 'CrCl', 'Amylase',
       'CRP', 'B', 'CD11b', 'HLADR', 'NK', 'NKT1', 'T', 'NKT2', 'MAIT', 'gd1T',
       'gd2T', 'ConvT%', 'CD8+T', 'CD4+T', 'CD8+Treg', 'CD4+Treg', 'CD20T',
       'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm', 'CD4grzk',
       'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK', 'Transitional B',
       'Memory B', 'Early Plasma B ', 'Plasma B', 'ABC', 'CD11c+CD206-',
       'CD11c+CD206+', 'CD11c-CD206+', 'CD11c-CD206-', 'Dectin-1+1',
       'Dectin-1+2', 'Dectin-1+3', 'Dectin-1+4', 'Gulucose', 'Sex_01',
       'CD8_PC1', 'CD8_1_PC1', 'CD8_2_PC1', 'CD8_3_PC1', 'CD4_PC1',
       'CD4_1_PC1', 'CD4_2_PC1', 'CD4_3_PC1', 'MAIT_PC1', 'MAIT_1_PC1',
       'MAIT_2_PC1', 'MAIT_3_PC1', 'GD1T_PC1', 'GD1T_1_PC1', 'GD1T_2_PC1',
       'GD1T_3_PC1', 'GD2T_PC1', 'GD2T_1_PC1', 'GD2T_2_PC1', 'GD2T_3_PC1'],
      dtype='object')

In [28]:
# df1 + 간 1
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

# =========================
# df2 간(liver)
# =========================
X_cols = ['AST', 'ALT', 'ALP', 'Bilirubin']

y_candidates = [ 'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등 → fold weight는 full-fit weight에 맞춰 부호 정렬
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, pd.Series(y, index=df_xy.index),
            n_components=1,
            n_splits=5,
            random_state=42
        )

        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


# 마지막 요약: CV Q2 기준 정렬(내림차순)
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 12
r_cv   = -0.5621
Q2     = -0.7001
RMSECV = 22.7000
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.2446 -3.6666    -0.1707    0.3729
ALT             0.9688  0.4387     0.7354    0.2968
AST             0.0164  0.0082     0.0034    0.2230
ALP             0.0364  0.0066    -0.0775    0.5031
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 12
r_cv   = -0.6943
Q2     = -0.8002
RMSECV = 24.2103
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.1858 -2.2732    -0.1290    0.3855
ALT             0.9710  0.3588     0.6655    0.2745
AST             0.0861  0.0352     0.0497    0.2760
ALP             0.1230  0.0181    -0.0474    0.6080
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 12
r_cv   = -0.3703
Q2     = -0.5071
RMSECV = 19.1688
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.8798  16.7561     0.7361    0.2343
ALT             0.3631   0.2089     0.3423    0.3893
AST            -0.1162  -0.0740    -0.0621    0.2575
ALP            -0.2840  -0.0651    -0.2529    0.2620
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 12
r_cv   = -0.4801
Q2     = -0.7678
RMSECV = 23.4830
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.3658 -11.3025     0.2151    0.4075
AST             0.6592  -0.6808     0.5262    0.2091
ALP             0.6488  -0.2412     0.5709    0.3002
ALT             0.1035  -0.0966     0.0386    0.3699
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 12
r_cv   = -0.4952
Q2     = -0.8116
RMSECV = 43.5470
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.1430  5.5441    -0.0995    0.3489
ALP             0.9704 -0.4528     0.7507    0.2500
ALT            -0.1570  0.1839    -0.2062    0.2421
AST             0.1150 -0.1491     0.1356    0.4628
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 12
r_cv   = -0.7510
Q2     = -1.0832
RMSECV = 14.2817
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.2578  3.0667    -0.1482    0.4079
AST             0.9118 -0.3625     0.6844    0.2402
ALT            -0.2157  0.0775    -0.1595    0.4188
ALP            -0.2359  0.0338    -0.1910    0.4000
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 12
r_cv   = -0.5451
Q2     = -1.2575
RMSECV = 27.0144
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.1506 -3.6466    -0.1936    0.4146
ALT             0.7435  0.5437     0.5630    0.2695
AST            -0.5879 -0.4758    -0.4971    0.2833
ALP             0.2807  0.0818     0.1971    0.3533
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 12
r_cv   = -0.3642
Q2     = -0.6900
RMSECV = 23.0029
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin       0.6413  21.0595     0.5591    0.2744
ALT             0.5905   0.5857     0.4968    0.1182
AST            -0.2560  -0.2810    -0.1847    0.3946
ALP            -0.4178  -0.1651    -0.3598    0.3184
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 12
r_cv   = -0.3103
Q2     = -0.5406
RMSECV = 29.4575
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1    coef  cv_w_mean  cv_w_std
Bilirubin      -0.1278  5.9939    -0.0382    0.3283
AST             0.6882 -1.0791     0.6101    0.2766
ALT            -0.4785  0.6779    -0.4400    0.1541
ALP            -0.5301  0.2992    -0.4675    0.2442
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 12
r_cv   = -0.2536
Q2     = -0.5411
RMSECV = 33.8458
------------------------------------------------------------
PLSR Weights / Coefs
           x_weight_c1     coef  cv_w_mean  cv_w_std
Bilirubin      -0.4532  21.1725    -0.3920    0.2775
ALT            -0.5525   0.7796    -0.5154    0.2331
ALP             0.6778  -0.3811     0.5937    0.2553
AST             0.1732  -0.2706     0.1559    0.2413
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
 MAITtrm 12 -0.370282 -0.507087 19.168767
GD1TgrzK 12 -0.310303 -0.540637 29.457532
GD2TgrzK 12 -0.253611 -0.541119 33.845796
MAITgrzK 12 -0.364153 -0.690031 23.002894
  CD4trm 12 -0.562058 -0.700057 22.700029
 GD1Ttrm 12 -0.480138 -0.767840 23.483019
  CD8trm 12 -0.694313 -0.800157 24.210279
 GD2Ttrm 12 -0.495177 -0.811568 43.546960
 CD4grzk 12 -0.750961 -1.083196 14.281654
 CD8grzk 12 -0.545086 -1.257478 27.014448
__________________________________________________________________________________________

In [ ]:
# df1 + 간 2
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

# =========================
# df2 간(liver)
# =========================
X_cols = ["Protein", "Albumin"]

y_candidates = [ 'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등 → fold weight는 full-fit weight에 맞춰 부호 정렬
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, pd.Series(y, index=df_xy.index),
            n_components=1,
            n_splits=5,
            random_state=42
        )

        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


# 마지막 요약: CV Q2 기준 정렬(내림차순)
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 13
r_cv   = 0.0558
Q2     = -0.0615
RMSECV = 17.3531
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin       0.8377 -5.1418     0.8445    0.1007
Protein       0.5462 -2.5223     0.4791    0.2476
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 13
r_cv   = 0.1012
Q2     = -0.0200
RMSECV = 17.5254
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin       0.8414 -4.7462     0.8323    0.0828
Protein       0.5404 -2.2931     0.4042    0.4161
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 13
r_cv   = -0.2913
Q2     = -0.1860
RMSECV = 17.7205
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin       0.7402 -4.1798     0.7541    0.1334
Protein       0.6724 -2.8567     0.4346    0.5340
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 13
r_cv   = -0.0332
Q2     = -0.1482
RMSECV = 18.8297
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1    coef  cv_w_mean  cv_w_std
Protein       0.8280 -4.4512     0.8356    0.1032
Albumin       0.5608 -4.0068     0.5152    0.1863
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 13
r_cv   = 0.0783
Q2     = -0.1911
RMSECV = 34.9129
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1    coef  cv_w_mean  cv_w_std
Protein       0.8319 -9.0198     0.8149    0.0821
Albumin       0.5550 -7.9978     0.5651    0.1185
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 13
r_cv   = 0.0198
Q2     = -0.2873
RMSECV = 11.4278
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1    coef  cv_w_mean  cv_w_std
Albumin       0.7220 -3.2631     0.7190    0.1162
Protein       0.6919 -2.3528     0.6784    0.1228
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 13
r_cv   = 0.3939
Q2     = 0.0783
RMSECV = 18.7676
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin       0.7263 -11.6574     0.7286    0.0406
Protein       0.6874  -8.3018     0.6830    0.0413
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 13
r_cv   = 0.4677
Q2     = 0.2181
RMSECV = 15.5481
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin       0.7064 -10.1367     0.7064    0.0421
Protein       0.7078  -7.6414     0.7058    0.0417
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 13
r_cv   = 0.3668
Q2     = -0.2175
RMSECV = 25.1664
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin       0.7614 -15.9642     0.7607    0.0369
Protein       0.6482 -10.2251     0.6470    0.0447
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 13
r_cv   = 0.2087
Q2     = -0.0677
RMSECV = 27.0716
------------------------------------------------------------
PLSR Weights / Coefs
         x_weight_c1     coef  cv_w_mean  cv_w_std
Albumin       0.6405 -10.4397     0.6331    0.0924
Protein       0.7680  -9.4179     0.7662    0.0810
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
MAITgrzK 13  0.467747  0.218135 15.548074
 CD8grzk 13  0.393927  0.078305 18.767582
  CD8trm 13  0.101197 -0.020042 17.525372
  CD4trm 13  0.055841 -0.061501 17.353116
GD2TgrzK 13  0.208748 -0.067664 27.071577
 GD1Ttrm 13 -0.033220 -0.148235 18.829682
 MAITtrm 13 -0.291261 -0.185992 17.720465
 GD2Ttrm 13  0.078276 -0.191135 34.912913
GD1TgrzK 13  0.366775 -0.217489 25.166404
 CD4grzk 13  0.019822 -0.287295 11.427832
__________________________________________________________________________________________

In [ ]:
# df2 + 간 - 안나와야댐
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

# =========================
# df2 간(liver)
# =========================
X_cols = ['AST', 'ALT', 'ALP', 'Bilirubin']

y_candidates = [ 'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등 → fold weight는 full-fit weight에 맞춰 부호 정렬
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 기준)
# =========================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df2.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, pd.Series(y, index=df_xy.index),
            n_components=1,
            n_splits=5,
            random_state=42
        )

        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


# 마지막 요약: CV Q2 기준 정렬(내림차순)
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

In [15]:
# df1 + 간 1
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from scipy.stats import pearsonr

sep = "_" * 90

# =========================
# df2 간(liver)
# =========================
X_cols = ['BUN', 'Cr']

y_candidates = [ 'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

def cv_pred_plsr(X: pd.DataFrame, y: np.ndarray, n_components=1, n_splits=5, random_state=42):
    """PLSR로 K-fold CV 예측값 반환(원래 순서대로)"""
    n = len(y)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(X):
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X.iloc[tr_idx], y[tr_idx])
        y_pred[te_idx] = model.predict(X.iloc[te_idx]).reshape(-1)

    return y_pred

def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return r, Q2, rmse

def plsr_weight_tables(X: pd.DataFrame, y: pd.Series, n_components=1, n_splits=5, random_state=42):
    """
    1) 전체 데이터로 fit한 x_weights_, coef_ 테이블
    2) CV fold별 x_weights_ 요약(mean±std) 테이블
    ※ PLS weight는 부호가 뒤집혀도 동등 → fold weight는 full-fit weight에 맞춰 부호 정렬
    """
    y_arr = y.astype(float).to_numpy().reshape(-1, 1)

    # (1) Full fit
    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X, y_arr)

    w_full = full.x_weights_
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X.columns
    )
    full_tbl["coef"] = coef

    # (2) CV weights summary
    n = len(X)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X.columns, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(X):
        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])

        w = m.x_weights_[:, 0].copy()  # component1

        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X.columns
    )

    return full_tbl, cv_tbl


# =========================
# 실행 (CV 기준)
# =========================
rows = []
###############################################
for i, y_col in enumerate(y_candidates, start=1):
    df_xy = df1.dropna(subset=X_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    X = df_xy[X_cols]
    y = df_xy[y_col].astype(float).to_numpy()

    try:
        y_pred = cv_pred_plsr(X, y, n_components=1, n_splits=5, random_state=42)
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        full_tbl, cv_tbl = plsr_weight_tables(
            X, pd.Series(y, index=df_xy.index),
            n_components=1,
            n_splits=5,
            random_state=42
        )

        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


# 마지막 요약: CV Q2 기준 정렬(내림차순)
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)")
print(sep)
print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 13
r_cv   = -0.0588
Q2     = -0.3979
RMSECV = 19.9140
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr         0.895 -30.6042     0.8487    0.1818
BUN       -0.446   1.3016    -0.4460    0.2605
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 13
r_cv   = -0.1508
Q2     = -0.4136
RMSECV = 20.6309
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9579 -31.2569     0.9554    0.0223
BUN      -0.2870   0.7991    -0.2868    0.0755
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 13
r_cv   = -0.2476
Q2     = -0.1992
RMSECV = 17.8190
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.1665 -3.6935    -0.2586    0.3856
BUN       0.9860  1.8671     0.8819    0.2133
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 13
r_cv   = -0.4189
Q2     = -0.9793
RMSECV = 24.7220
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.3706 -4.2501    -0.0117    0.7551
BUN       0.9288  0.9090     0.7220    0.1675
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 13
r_cv   = -0.5374
Q2     = -0.5074
RMSECV = 39.2759
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9721 -20.2947     0.8527    0.1064
BUN      -0.2347   0.4182    -0.3096    0.4583
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 13
r_cv   = 0.0572
Q2     = -0.3462
RMSECV = 11.6865
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.6709 -18.0451    -0.6619    0.3419
BUN       0.7415   1.7020     0.6299    0.2991
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 13
r_cv   = 0.1687
Q2     = -0.3429
RMSECV = 22.6532
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.6434 -38.7330    -0.6380    0.3078
BUN       0.7655   3.9329     0.6932    0.2141
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 13
r_cv   = -0.1193
Q2     = -0.2739
RMSECV = 19.8466
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9968 -30.7096     0.8725    0.1818
BUN      -0.0799   0.2099    -0.0739    0.5085
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 13
r_cv   = -0.1495
Q2     = -0.9246
RMSECV = 31.6419
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.8139 -54.9307     0.7650    0.2071
BUN      -0.5810   3.3459    -0.5065    0.3935
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 13
r_cv   = -0.2055
Q2     = -0.1434
RMSECV = 28.0151
------------------------------------------------------------
PLSR Weights / Coefs
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.3881 -14.3776    -0.4558    0.3868
BUN       0.9216   2.9137     0.7809    0.2801
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)
__________________________________________________________________________________________
   y_col  n      r_cv        Q2    RMSECV
GD2TgrzK 13 -0.205484 -0.143379 28.015051
 MAITtrm 13 -0.247577 -0.199216 17.818984
MAITgrzK 13 -0.119338 -0.273944 19.846581
 CD8grzk 13  0.168738 -0.342857 22.653206
 CD4grzk 13  0.057153 -0.346225 11.686476
  CD4trm 13 -0.058824 -0.397920 19.914003
  CD8trm 13 -0.150848 -0.413583 20.630931
 GD2Ttrm 13 -0.537411 -0.507443 39.275902
GD1TgrzK 13 -0.149550 -0.924636 31.641932
 GD1Ttrm 13 -0.418890 -0.979299 24.721986
__________________________________________________________________________________________

bmi 통제 + 간신장 나누기 + pls

In [18]:
# ======================================================
# PLSR (BUN/Cr) with covariate control (BMI, Sex_01)
# - CV prediction metrics: r_cv, Q2, RMSECV
# - Full-fit weights/coef + CV-fold weights summary (mean±std)
# ======================================================

import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from scipy.stats import pearsonr

sep = "_" * 90

# =========================
# 설정
# =========================
# 주효과(설명변수): 간/신장 지표 등
X_cols = ['BUN', 'Cr']

# 통제변수(공변량)
C_cols = ['BMI']   # Sex_01은 0/1 인코딩되어 있다고 가정

# 반응변수 후보
y_candidates = [
    'CD4trm', 'CD8trm', 'MAITtrm', 'GD1Ttrm', 'GD2Ttrm',
    'CD4grzk', 'CD8grzk', 'MAITgrzK', 'GD1TgrzK', 'GD2TgrzK',
]

# ======================================================
# 1) 유틸: CV metric
# ======================================================
def cv_metrics(y_true, y_pred):
    """r_cv, Q2, RMSECV 계산"""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    if (np.std(y_true) < 1e-12) or (np.std(y_pred) < 1e-12):
        r = np.nan
    else:
        r, _ = pearsonr(y_true, y_pred)

    sse = np.sum((y_true - y_pred) ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    Q2 = np.nan if sst < 1e-12 else (1.0 - sse / sst)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return r, Q2, rmse

# ======================================================
# 2) 잔차화(residualization) 함수
#    - train에서 공변량 회귀 fit
#    - train/test에 동일 모델로 적용
# ======================================================
def residualize_X_train_test(X_tr: pd.DataFrame, X_te: pd.DataFrame,
                             C_tr: pd.DataFrame, C_te: pd.DataFrame):
    """
    X의 각 컬럼을 공변량 C로 선형회귀 후, 잔차 반환
    """
    X_tr_res = X_tr.copy()
    X_te_res = X_te.copy()

    # 안정성: numpy로 변환
    Ctr = np.asarray(C_tr, dtype=float)
    Cte = np.asarray(C_te, dtype=float)

    for col in X_tr.columns:
        yx_tr = np.asarray(X_tr[col], dtype=float)
        lr = LinearRegression()
        lr.fit(Ctr, yx_tr)

        X_tr_res[col] = yx_tr - lr.predict(Ctr)
        X_te_res[col] = np.asarray(X_te[col], dtype=float) - lr.predict(Cte)

    return X_tr_res, X_te_res

def residualize_y_train_test(y_tr: np.ndarray, y_te: np.ndarray,
                             C_tr: pd.DataFrame, C_te: pd.DataFrame):
    """
    y를 공변량 C로 선형회귀 후, 잔차 반환
    """
    Ctr = np.asarray(C_tr, dtype=float)
    Cte = np.asarray(C_te, dtype=float)

    lr = LinearRegression()
    lr.fit(Ctr, np.asarray(y_tr, dtype=float))

    y_tr_res = np.asarray(y_tr, dtype=float) - lr.predict(Ctr)
    y_te_res = np.asarray(y_te, dtype=float) - lr.predict(Cte)
    return y_tr_res, y_te_res

# ======================================================
# 3) CV 예측 (통제 포함, 누수 방지)
# ======================================================
def cv_pred_plsr_controlled(df_xy: pd.DataFrame,
                            X_cols, y_col, C_cols,
                            n_components=1, n_splits=5, random_state=42):
    """
    K-fold CV에서:
      (1) train에서 공변량 통제(잔차화) 모델 학습
      (2) train/test를 잔차화
      (3) 잔차화된 X로 PLSR 학습 → test 예측
    반환: 원래 인덱스 순서의 y_pred (np.ndarray)
    """
    n = len(df_xy)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        return None

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)

    y_all = df_xy[y_col].astype(float).to_numpy()
    y_pred = np.empty(n, dtype=float)

    for tr_idx, te_idx in cv.split(df_xy):
        X_tr = df_xy.iloc[tr_idx][X_cols]
        X_te = df_xy.iloc[te_idx][X_cols]
        C_tr = df_xy.iloc[tr_idx][C_cols]
        C_te = df_xy.iloc[te_idx][C_cols]

        y_tr = y_all[tr_idx]
        y_te = y_all[te_idx]

        # ✅ fold 내부 통제(잔차화)
        X_tr_res, X_te_res = residualize_X_train_test(X_tr, X_te, C_tr, C_te)
        y_tr_res, _ = residualize_y_train_test(y_tr, y_te, C_tr, C_te)

        # ✅ PLSR
        model = PLSRegression(n_components=n_components, scale=True)
        model.fit(X_tr_res, y_tr_res.reshape(-1, 1))
        y_pred[te_idx] = model.predict(X_te_res).reshape(-1)

    return y_pred

# ======================================================
# 4) weight/coef 테이블 (통제 포함)
#    - Full-fit: 전체 데이터로 공변량 회귀 fit → 잔차화 → PLSR fit
#    - CV fold weights: 각 fold에서 train 기반 잔차화 후 weights 추출
#      (PLS weight 부호는 뒤집혀도 동등 → full-fit weight에 맞춰 sign align)
# ======================================================
def residualize_X_full(X: pd.DataFrame, C: pd.DataFrame):
    """전체 데이터 기준으로 X 잔차화"""
    X_res = X.copy()
    Cmat = np.asarray(C, dtype=float)

    for col in X.columns:
        lr = LinearRegression().fit(Cmat, np.asarray(X[col], dtype=float))
        X_res[col] = np.asarray(X[col], dtype=float) - lr.predict(Cmat)
    return X_res

def residualize_y_full(y: pd.Series, C: pd.DataFrame):
    """전체 데이터 기준으로 y 잔차화"""
    Cmat = np.asarray(C, dtype=float)
    yv = np.asarray(y.astype(float), dtype=float)
    lr = LinearRegression().fit(Cmat, yv)
    return yv - lr.predict(Cmat)

def plsr_weight_tables_controlled(df_xy: pd.DataFrame,
                                  X_cols, y_col, C_cols,
                                  n_components=1, n_splits=5, random_state=42):
    """
    반환:
      full_tbl: x_weight_c1.., coef (전체 잔차화 후 full fit)
      cv_tbl  : cv_w_mean, cv_w_std (fold별 x_weights_ 요약, sign align)
    """
    X = df_xy[X_cols]
    C = df_xy[C_cols]
    y = df_xy[y_col].astype(float)

    # (1) Full fit (전체 기준 잔차화)
    X_res_full = residualize_X_full(X, C)
    y_res_full = residualize_y_full(y, C).reshape(-1, 1)

    full = PLSRegression(n_components=n_components, scale=True)
    full.fit(X_res_full, y_res_full)

    w_full = full.x_weights_  # (p, n_components)
    coef = full.coef_.reshape(-1)

    full_tbl = pd.DataFrame(
        {f"x_weight_c{k+1}": w_full[:, k] for k in range(n_components)},
        index=X_cols
    )
    full_tbl["coef"] = coef

    # (2) CV fold weights summary
    n = len(df_xy)
    n_splits = min(n_splits, n)
    if n_splits < 2:
        cv_tbl = pd.DataFrame(index=X_cols, data={"cv_w_mean": np.nan, "cv_w_std": np.nan})
        return full_tbl, cv_tbl

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    fold_ws = []

    # sign align reference: full-fit component1 weight
    ref = w_full[:, 0].copy()

    for tr_idx, te_idx in cv.split(df_xy):
        X_tr = df_xy.iloc[tr_idx][X_cols]
        C_tr = df_xy.iloc[tr_idx][C_cols]
        y_tr = df_xy.iloc[tr_idx][y_col].astype(float)

        # train 기준 잔차화
        X_tr_res = residualize_X_full(X_tr, C_tr)   # train-only fit이지만 함수는 내부에서 train만 사용
        y_tr_res = residualize_y_full(y_tr, C_tr).reshape(-1, 1)

        m = PLSRegression(n_components=n_components, scale=True)
        m.fit(X_tr_res, y_tr_res)

        w = m.x_weights_[:, 0].copy()

        # sign align
        if np.dot(w, ref) < 0:
            w *= -1
        fold_ws.append(w)

    fold_ws = np.vstack(fold_ws)
    cv_tbl = pd.DataFrame(
        {
            "cv_w_mean": fold_ws.mean(axis=0),
            "cv_w_std": fold_ws.std(axis=0, ddof=1) if fold_ws.shape[0] > 1 else np.zeros(fold_ws.shape[1]),
        },
        index=X_cols
    )

    return full_tbl, cv_tbl

# ======================================================
# 5) 실행 루프
# ======================================================
rows = []

for i, y_col in enumerate(y_candidates, start=1):
    # df2가 이미 존재한다고 가정
    df_xy = df1.dropna(subset=X_cols + C_cols + [y_col]).copy()
    n = len(df_xy)

    print(sep)
    print(f"[{i}/{len(y_candidates)}] TSubset = {y_col}")
    print(f"n = {n}")

    if n < 6:
        print("→ SKIP (n too small)")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": "SKIP"})
        continue

    try:
        # ✅ 통제 포함 CV 예측
        y_true = df_xy[y_col].astype(float).to_numpy()
        y_pred = cv_pred_plsr_controlled(
            df_xy=df_xy,
            X_cols=X_cols,
            y_col=y_col,
            C_cols=C_cols,
            n_components=1,
            n_splits=5,
            random_state=42
        )
        if y_pred is None:
            raise ValueError("CV split too small")

        r_cv, Q2, rmse = cv_metrics(y_true, y_pred)

        print(f"r_cv   = {r_cv:.4f}" if np.isfinite(r_cv) else "r_cv   = NaN")
        print(f"Q2     = {Q2:.4f}" if np.isfinite(Q2) else "Q2     = NaN")
        print(f"RMSECV = {rmse:.4f}" if np.isfinite(rmse) else "RMSECV = NaN")

        # ✅ 통제 포함 weight/coef
        full_tbl, cv_tbl = plsr_weight_tables_controlled(
            df_xy=df_xy,
            X_cols=X_cols,
            y_col=y_col,
            C_cols=C_cols,
            n_components=1,
            n_splits=5,
            random_state=42
        )

        w_tbl = full_tbl.join(cv_tbl, how="left")
        w_tbl = w_tbl.reindex(w_tbl["coef"].abs().sort_values(ascending=False).index)

        print("-" * 60)
        print("PLSR Weights / Coefs (controlled for BMI, Sex_01)")
        print(w_tbl.round(4).to_string())
        print("-" * 60)

        rows.append({"y_col": y_col, "n": n, "r_cv": r_cv, "Q2": Q2, "RMSECV": rmse, "status": "OK"})

    except Exception as e:
        print(f"→ FAIL: {type(e).__name__}: {str(e)[:120]}")
        rows.append({"y_col": y_col, "n": n, "r_cv": np.nan, "Q2": np.nan, "RMSECV": np.nan, "status": f"FAIL: {type(e).__name__}"})


# ======================================================
# 6) 마지막 요약: CV Q2 기준 정렬(내림차순)
# ======================================================
res = pd.DataFrame(rows)
res_ok = res.query("status == 'OK'").sort_values("Q2", ascending=False, na_position="last")

print(sep)
print("FINAL SUMMARY (sorted by CV Q2, desc)  [controlled: BMI, Sex_01]")
print(sep)
if len(res_ok) == 0:
    print("No OK results.")
else:
    print(res_ok[["y_col", "n", "r_cv", "Q2", "RMSECV"]].to_string(index=False))
print(sep)

__________________________________________________________________________________________
[1/10] TSubset = CD4trm
n = 13
r_cv   = -0.1027
Q2     = -13.1079
RMSECV = 63.2627
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.8966 -30.8005     0.7473    0.3962
BUN      -0.4429   1.3604    -0.3652    0.4777
------------------------------------------------------------
__________________________________________________________________________________________
[2/10] TSubset = CD8trm
n = 13
r_cv   = -0.2830
Q2     = -9.7546
RMSECV = 56.9056
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9614 -31.3096     0.7778    0.2752
BUN      -0.2751   0.8010    -0.4873    0.3483
------------------------------------------------------------
__________________________________________________________________________________________
[3/10] TSubset = MAITtrm
n = 13
r_cv   = -0.3571
Q2     = -9.8329
RMSECV = 53.5557
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.2552 -3.3814    -0.1672    0.7103
BUN       0.9669  1.1453     0.6365    0.4517
------------------------------------------------------------
__________________________________________________________________________________________
[4/10] TSubset = GD1Ttrm
n = 13
r_cv   = -0.2395
Q2     = -7.1526
RMSECV = 50.1736
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1    coef  cv_w_mean  cv_w_std
Cr       -0.2827 -4.3385     0.1125    0.7103
BUN       0.9592  1.3161     0.7417    0.2051
------------------------------------------------------------
__________________________________________________________________________________________
[5/10] TSubset = GD2Ttrm
n = 13
r_cv   = -0.6107
Q2     = -3.0108
RMSECV = 64.0652
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9291 -17.3739     0.8392    0.1634
BUN       0.3698  -0.6181    -0.2165    0.5332
------------------------------------------------------------
__________________________________________________________________________________________
[6/10] TSubset = CD4grzk
n = 13
r_cv   = 0.1048
Q2     = -6.7262
RMSECV = 27.9967
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.6634 -18.2034    -0.5401    0.5319
BUN       0.7482   1.8353     0.6672    0.2147
------------------------------------------------------------
__________________________________________________________________________________________
[7/10] TSubset = CD8grzk
n = 13
r_cv   = 0.3263
Q2     = -8.3236
RMSECV = 59.6906
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.6050 -39.1194    -0.5490    0.3631
BUN       0.7963   4.6031     0.7546    0.1720
------------------------------------------------------------
__________________________________________________________________________________________
[8/10] TSubset = MAITgrzK
n = 13
r_cv   = -0.1018
Q2     = -5.6623
RMSECV = 45.3860
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.9999 -29.9753     0.7985    0.3193
BUN       0.0121  -0.0325     0.3010    0.4878
------------------------------------------------------------
__________________________________________________________________________________________
[9/10] TSubset = GD1TgrzK
n = 13
r_cv   = 0.3559
Q2     = -5.7110
RMSECV = 59.0858
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr        0.7324 -56.2505     0.7146    0.1905
BUN      -0.6809   4.6752    -0.6142    0.3221
------------------------------------------------------------
__________________________________________________________________________________________
[10/10] TSubset = GD2TgrzK
n = 13
r_cv   = -0.1917
Q2     = -6.1715
RMSECV = 70.1619
------------------------------------------------------------
PLSR Weights / Coefs (controlled for BMI, Sex_01)
     x_weight_c1     coef  cv_w_mean  cv_w_std
Cr       -0.4546 -14.3469    -0.2867    0.6873
BUN       0.8907   2.5129     0.6517    0.3796
------------------------------------------------------------
__________________________________________________________________________________________
FINAL SUMMARY (sorted by CV Q2, desc)  [controlled: BMI, Sex_01]
__________________________________________________________________________________________
   y_col  n      r_cv         Q2    RMSECV
 GD2Ttrm 13 -0.610700  -3.010822 64.065230
MAITgrzK 13 -0.101794  -5.662289 45.386044
GD1TgrzK 13  0.355903  -5.711028 59.085812
GD2TgrzK 13 -0.191736  -6.171509 70.161929
 CD4grzk 13  0.104805  -6.726173 27.996712
 GD1Ttrm 13 -0.239534  -7.152571 50.173563
 CD8grzk 13  0.326257  -8.323575 59.690606
  CD8trm 13 -0.283045  -9.754578 56.905583
 MAITtrm 13 -0.357150  -9.832859 53.555710
  CD4trm 13 -0.102742 -13.107852 63.262710
__________________________________________________________________________________________